<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Controller
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @license   http://www.unister.de  Unister License
 * @version   SVN: $Id$
 * @link      todo
 */
?>
<td class="btn<?php if ($this->internal) { ?> internal<?php } ?>"
    onclick="<?php echo $this->goto; ?>"
    onmousedown="logThisClick('<?php echo $this->sparte; ?>_<?php echo $this->kreditinstitut; ?>');"
    title="Weiter zum Kredit Antrag <?php echo $this->kreditInstitutTitle; ?>">
    &nbsp;
</td>