<?php

return [
    'test-00122-04848' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 5.0; P1032X Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '51',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '5.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00122-04849' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; FSTE)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.0',
            'Platform_Codename'       => 'Windows NT 6.1',
            'Platform_Marketingname'  => 'Windows 7',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'test-00122-04851' => [
        'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/33.0.1750.154 Anonymisiert durch AlMiSoft Browser-Maulkorb 63971600',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '33',
            'Platform_Codename'       => 'Windows NT 6.1',
            'Platform_Marketingname'  => 'Windows 7',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00122-04854' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.1; .NET4.0C; Tablet PC 2.0; OfficeLiveConnector.1.5; OfficeLivePatch.1.3; .NET4.0E; GWX:DOWNLOADED; GWX:QUALIFIED)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '7.0',
            'Platform_Codename'       => 'Windows NT 6.1',
            'Platform_Marketingname'  => 'Windows 7',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'test-00122-04855' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; InfoPath.3; .NET4.0E; ms-office; MSOffice 14)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '7.0',
            'Platform_Codename'       => 'Windows NT 6.1',
            'Platform_Marketingname'  => 'Windows 7',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
];
