<?php

namespace BrowserDetectorTest\Detector\Browser;

use BrowserDetector\Detector\Browser\GoogleWebPreview;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:39:39.
 */
class GoogleWebPreviewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GoogleWebPreview
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GoogleWebPreview('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getEngine
     * @todo   Implement testGetEngine().
     */
    public function testGetEngine()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getBits
     * @todo   Implement testGetBits().
     */
    public function testGetBits()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getCanSkipAlignedLinkRow
     * @todo   Implement testGetCanSkipAlignedLinkRow().
     */
    public function testGetCanSkipAlignedLinkRow()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getClaimsWebSupport
     * @todo   Implement testGetClaimsWebSupport().
     */
    public function testGetClaimsWebSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getModus
     * @todo   Implement testGetModus().
     */
    public function testGetModus()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getPdfSupport
     * @todo   Implement testGetPdfSupport().
     */
    public function testGetPdfSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getRssSupport
     * @todo   Implement testGetRssSupport().
     */
    public function testGetRssSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getSupportsBasicAuthentication
     * @todo   Implement testGetSupportsBasicAuthentication().
     */
    public function testGetSupportsBasicAuthentication()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getSupportsEmptyOptionValues
     * @todo   Implement testGetSupportsEmptyOptionValues().
     */
    public function testGetSupportsEmptyOptionValues()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getSupportsPostMethod
     * @todo   Implement testGetSupportsPostMethod().
     */
    public function testGetSupportsPostMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Browser\GoogleWebPreview::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
