<?php
/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2024, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace BrowserDetectorTest\Header;

use BrowserDetector\Header\SecChUaModel;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\ExpectationFailedException;
use PHPUnit\Framework\TestCase;

use function sprintf;

final class SecChUaModelTest extends TestCase
{
    /** @throws ExpectationFailedException */
    #[DataProvider('providerUa')]
    public function testData(string $ua, bool $hasModel, string | null $model): void
    {
        $header = new SecChUaModel($ua);

        self::assertSame($ua, $header->getValue(), sprintf('value mismatch for ua "%s"', $ua));
        self::assertSame(
            $ua,
            $header->getNormalizedValue(),
            sprintf('value mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasDeviceArchitecture(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getDeviceArchitecture(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasDeviceBitness(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getDeviceBitness(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasDeviceIsMobile(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getDeviceIsMobile(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertSame(
            $hasModel,
            $header->hasDeviceCode(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertSame(
            $model,
            $header->getDeviceCode(),
            sprintf('device info mismatch for ua "%s"', $ua),
        );
        self::assertFalse($header->hasClientCode(), sprintf('browser info mismatch for ua "%s"', $ua));
        self::assertNull(
            $header->getClientCode(),
            sprintf('browser info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasClientVersion(),
            sprintf('browser info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getClientVersion(),
            sprintf('browser info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasPlatformCode(),
            sprintf('platform info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getPlatformCode(),
            sprintf('platform info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasPlatformVersion(),
            sprintf('platform info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getPlatformVersion(),
            sprintf('platform info mismatch for ua "%s"', $ua),
        );
        self::assertFalse($header->hasEngineCode(), sprintf('engine info mismatch for ua "%s"', $ua));
        self::assertNull(
            $header->getEngineCode(),
            sprintf('engine info mismatch for ua "%s"', $ua),
        );
        self::assertFalse(
            $header->hasEngineVersion(),
            sprintf('engine info mismatch for ua "%s"', $ua),
        );
        self::assertNull(
            $header->getEngineVersion(),
            sprintf('engine info mismatch for ua "%s"', $ua),
        );
    }

    /**
     * @return array<int, array<int, bool|string|null>>
     *
     * @throws void
     */
    public static function providerUa(): array
    {
        return [
            // LG
            ['"LM-G710"', true, 'lg=lg lm-g710'],
            ['"LM-G910"', true, 'lg=lg lm-g910'],
            ['"LM-G900"', true, 'lg=lg lm-g900'],
            ['"LM-G850"', true, 'lg=lg lm-g850'],
            ['"LM-Q630"', true, 'lg=lg lm-q630'],
            ['"LG-M700"', true, 'lg=lg m700'],
            ['"LM-V405"', true, 'lg=lg lm-v405'],
            ['"LG-H870"', true, 'lg=lg h870'],
            ['"LG-H850"', true, 'lg=lg h850'],
            ['"LM-K410"', true, 'lg=lg lm-k410'],
            ['"LG-M200"', true, 'lg=lg m200'],
            ['"LM-Q617.FGN"', true, 'lg=lg lm-q617.fgn'],
            ['"LM-K420"', true, 'lg=lg lm-k420'],
            ['"LM-X210"', true, 'lg=lg lm-x210'],
            // Acer
            ['"A100"', true, 'acer=acer a100'],
            ['"B1-860A"', true, 'acer=acer b1-860a'],
            ['"A1-734"', true, 'acer=acer a1-734'],
            ['"A3-A40"', true, 'acer=acer a3-a40'],
            ['"B1-7A0"', true, 'acer=acer b1-7a0'],
            ['"B1-860A"', true, 'acer=acer b1-860a'],
            ['"B3-A32"', true, 'acer=acer b3-a32'],
            ['"B3-A40"', true, 'acer=acer b3-a40'],
            // AllCall
            ['"Atom"', true, 'allcall=allcall atom'],
            // Amazon
            ['"KFKAWI"', true, 'amazon=amazon kfkawi'],
            ['"KFGIWI"', true, 'amazon=amazon kfgiwi'],
            ['"KFFOWI"', true, 'amazon=amazon kffowi'],
            ['"KFMUWI"', true, 'amazon=amazon kfmuwi'],
            ['"KFDOWI"', true, 'amazon=amazon kfdowi'],
            ['"KFTRWI"', true, 'amazon=amazon kftrwi'],
            ['"KFTRPWI"', true, 'amazon=amazon kftrpwi'],
            ['"KFRAPWI"', true, 'amazon=amazon kfrapwi'],
            ['"KFONWI"', true, 'amazon=amazon kfonwi'],
            ['"KFMAWI"', true, 'amazon=amazon kfmawi'],
            ['"KFSUWI"', true, 'amazon=amazon kfsuwi'],
            ['"AFTMM"', true, 'amazon=amazon aftmm'],
            ['"AFTSSS"', true, 'amazon=amazon aftsss'],
            ['"KFTBWI"', true, 'amazon=amazon kftbwi'],
            ['"KFAUWI"', true, 'amazon=amazon kfauwi'],
            ['"KFSAWI"', true, 'amazon=amazon kfsawi'],
            ['"KFQUWI"', true, 'amazon=amazon kfquwi'],
            ['"AFTT"', true, 'amazon=amazon aftt'],
            // Asus
            ['"P024"', true, 'asus=asus p024'],
            ['"ASUS_X00DD"', true, 'asus=asus x00dd'],
            ['"ASUS_I005DA"', true, 'asus=asus i005da'],
            ['"ASUS_I003D"', true, 'asus=asus i003d'],
            ['"ASUS_I003DD"', true, 'asus=asus i003dd'],
            ['"ASUS_I006D"', true, 'asus=asus i006d'],
            ['"ZC554KL"', true, 'asus=asus x00id'],
            ['"ASUS_Z008D"', true, 'asus=asus z008d'],
            ['"ASUS_AI2302"', true, 'asus=asus ai2302'],
            ['"ASUS_AI2202"', true, 'asus=asus ai2202'],
            // Google
            ['"Nexus 7"', true, 'google=google nexus 7'],
            ['"Pixel 7 Pro"', true, 'google=google pixel 7 pro'],
            ['"Pixel 4 XL"', true, 'google=google pixel 4 xl'],
            ['"Pixel 6"', true, 'google=google pixel 6'],
            ['"Pixel 6 Pro"', true, 'google=google pixel 6 pro'],
            ['"Pixel 6a"', true, 'google=google pixel 6a'],
            ['"Pixel 4a (5G)"', true, 'google=google pixel 4a 5g'],
            ['"Pixel 7"', true, 'google=google pixel 7'],
            ['"Pixel 3a"', true, 'google=google pixel 3a'],
            ['"Pixel 3"', true, 'google=google pixel 3'],
            ['"Pixel 5"', true, 'google=google pixel 5'],
            ['"Pixel 7a"', true, 'google=google pixel 7a'],
            ['"Pixel 4"', true, 'google=google pixel 4'],
            ['"Pixel 8"', true, 'google=google pixel 8'],
            ['"kukui"', true, 'google=google kukui'],
            ['"Nexus 5"', true, 'google=google nexus 5'],
            ['"Pixel 4a"', true, 'google=google pixel 4a'],
            ['"Pixel 9 Pro XL"', true, 'google=google pixel 9 pro xl'],
            ['"Pixel 8a"', true, 'google=google pixel 8a'],
            // OnePlus
            ['"AC2003"', true, 'oneplus=oneplus ac2003'],
            ['"IN2023"', true, 'oneplus=oneplus in2023'],
            ['"NE2213"', true, 'oneplus=oneplus ne2213'],
            ['"LE2113"', true, 'oneplus=oneplus le2113'],
            ['"LE2115"', true, 'oneplus=oneplus le2115'],
            ['"IN2013"', true, 'oneplus=oneplus in2013'],
            ['"HD1903"', true, 'oneplus=oneplus hd1903'],
            ['"KB2003"', true, 'oneplus=oneplus kb2003'],
            ['"BE2013"', true, 'oneplus=oneplus be2013'],
            ['"LE2123"', true, 'oneplus=oneplus le2123'],
            ['"LE2125"', true, 'oneplus=oneplus le2125'],
            ['"LE2120"', true, 'oneplus=oneplus le2120'],
            ['"GM1913"', true, 'oneplus=oneplus gm1913'],
            ['"BE2029"', true, 'oneplus=oneplus be2029'],
            ['"CPH2399"', true, 'oneplus=oneplus cph2399'],
            ['"DN2103"', true, 'oneplus=oneplus dn2103'],
            ['"CPH2415"', true, 'oneplus=oneplus cph2415'],
            ['"EB2103"', true, 'oneplus=oneplus eb2103'],
            ['"IN2015"', true, 'oneplus=oneplus in2015'],
            ['"CPH2409"', true, 'oneplus=oneplus cph2409'],
            ['"ONEPLUS A6003"', true, 'oneplus=oneplus a6003'],
            ['"ONEPLUS A3003"', true, 'oneplus=oneplus a3003'],
            ['"ONEPLUS A5010"', true, 'oneplus=oneplus a5010'],
            ['"CPH2551"', true, 'oneplus=oneplus cph2551'],
            ['"CPH2581"', true, 'oneplus=oneplus cph2581'],
            // Oppo
            ['"CPH2065"', true, 'oppo=oppo cph2065'],
            ['"CPH2211"', true, 'oppo=oppo cph2211'],
            ['"CPH2271"', true, 'oppo=oppo cph2271'],
            ['"CPH2339"', true, 'oppo=oppo cph2339'],
            ['"CPH2385"', true, 'oppo=oppo cph2385'],
            ['"CPH2195"', true, 'oppo=oppo cph2195'],
            ['"CPH2251"', true, 'oppo=oppo cph2251'],
            ['"CPH2197"', true, 'oppo=oppo cph2197'],
            ['"CPH2145"', true, 'oppo=oppo cph2145'],
            ['"CPH2135"', true, 'oppo=oppo cph2135'],
            ['"CPH2269"', true, 'oppo=oppo cph2269'],
            ['"CPH2173"', true, 'oppo=oppo cph2173'],
            ['"CPH2179"', true, 'oppo=oppo cph2179'],
            ['"CPH2219"', true, 'oppo=oppo cph2219'],
            ['"CPH2333"', true, 'oppo=oppo cph2333'],
            ['"CPH2305"', true, 'oppo=oppo cph2305'],
            ['"CPH2247"', true, 'oppo=oppo cph2247'],
            ['"CPH2375"', true, 'oppo=oppo cph2375'],
            ['"CPH2307"', true, 'oppo=oppo cph2307'],
            ['"CPH2161"', true, 'oppo=oppo cph2161'],
            ['"CPH2207"', true, 'oppo=oppo cph2207'],
            ['"CPH2091"', true, 'oppo=oppo cph2091'],
            ['"CPH2371"', true, 'oppo=oppo cph2371'],
            ['"CPH1907"', true, 'oppo=oppo cph1907'],
            ['"CPH2185"', true, 'oppo=oppo cph2185'],
            ['"CPH2343"', true, 'oppo=oppo cph2343'],
            ['"CPH2273"', true, 'oppo=oppo cph2273'],
            ['"CPH2127"', true, 'oppo=oppo cph2127'],
            ['"OPD2202"', true, 'oppo=oppo opd2202'],
            ['"CPH2005"', true, 'oppo=oppo cph2005'],
            // Xiaomi
            ['"Redmi Note 9 Pro"', true, 'xiaomi=xiaomi redmi note 9 pro'],
            ['"M2103K19G"', true, 'xiaomi=xiaomi m2103k19g'],
            ['"M2103K19C"', true, 'xiaomi=xiaomi m2103k19c'],
            ['"M2102K1AC"', true, 'xiaomi=xiaomi m2102k1ac'],
            ['"M2101K9AG"', true, 'xiaomi=xiaomi m2101k9ag'],
            ['"M2101K9AI"', true, 'xiaomi=xiaomi m2101k9ai'],
            ['"M2101K9G"', true, 'xiaomi=xiaomi m2101k9g'],
            ['"M2101K9C"', true, 'xiaomi=xiaomi m2101k9c'],
            ['"M2101K9R"', true, 'xiaomi=xiaomi m2101k9r'],
            ['"M2101K6G"', true, 'xiaomi=xiaomi m2101k6g'],
            ['"M2101K6R"', true, 'xiaomi=xiaomi m2101k6r'],
            ['"M2101K6P"', true, 'xiaomi=xiaomi m2101k6p'],
            ['"M2011K2G"', true, 'xiaomi=xiaomi m2011k2g'],
            ['"M2011K2C"', true, 'xiaomi=xiaomi m2011k2c'],
            ['"M2101K7BNY"', true, 'xiaomi=xiaomi m2101k7bny'],
            ['"M2101K7BG"', true, 'xiaomi=xiaomi m2101k7bg'],
            ['"M2101K7BI"', true, 'xiaomi=xiaomi m2101k7bi'],
            ['"M2101K7BL"', true, 'xiaomi=xiaomi m2101k7bl'],
            ['"M2010J19SG"', true, 'xiaomi=xiaomi m2010j19sg'],
            ['"M2010J19SY"', true, 'xiaomi=xiaomi m2010j19sy'],
            ['"M2101K7AG"', true, 'xiaomi=xiaomi m2101k7ag'],
            ['"M2101K7AI"', true, 'xiaomi=xiaomi m2101k7ai'],
            ['"M2007J22G"', true, 'xiaomi=xiaomi m2007j22g'],
            ['"M2012K11AG"', true, 'xiaomi=xiaomi m2012k11ag'],
            ['"M2102J20SG"', true, 'xiaomi=xiaomi m2102j20sg'],
            ['"M2102J20SI"', true, 'xiaomi=xiaomi m2102j20si'],
            ['"M1908C3JGG"', true, 'xiaomi=xiaomi m1908c3jgg'],
            ['"2201123G"', true, 'xiaomi=xiaomi 2201123g'],
            ['"2201123C"', true, 'xiaomi=xiaomi 2201123c'],
            ['"2201117TY"', true, 'xiaomi=xiaomi 2201117ty'],
            ['"2201117TG"', true, 'xiaomi=xiaomi 2201117tg'],
            ['"2201117TI"', true, 'xiaomi=xiaomi 2201117ti'],
            ['"2201117TL"', true, 'xiaomi=xiaomi 2201117tl'],
            ['"21091116AC"', true, 'xiaomi=xiaomi 21091116ac'],
            ['"21121119SC"', true, 'xiaomi=xiaomi 21121119sc'],
            ['"M2102K1G"', true, 'xiaomi=xiaomi m2102k1g'],
            ['"M2102K1C"', true, 'xiaomi=xiaomi m2102k1c'],
            ['"220333QNY"', true, 'xiaomi=xiaomi 220333qny'],
            ['Redmi Note 8 Pro', true, 'xiaomi=xiaomi redmi note 8 pro'],
            ['"Mi 9 SE"', true, 'xiaomi=xiaomi mi 9 se'],
            ['"21081111RG"', true, 'xiaomi=xiaomi 21081111rg'],
            ['"2201116SG"', true, 'xiaomi=xiaomi 2201116sg'],
            ['"2109119DG"', true, 'xiaomi=xiaomi 2109119dg'],
            ['"2107113SG"', true, 'xiaomi=xiaomi 2107113sg'],
            ['"2201117SY"', true, 'xiaomi=xiaomi 2201117sy'],
            ['"21061119DG"', true, 'xiaomi=xiaomi 21061119dg'],
            ['"21061119AG"', true, 'xiaomi=xiaomi 21061119ag'],
            ['"M2003J15SC"', true, 'xiaomi=xiaomi m2003j15sc'],
            ['"2210132G"', true, 'xiaomi=xiaomi 2210132g'],
            ['"22081212UG"', true, 'xiaomi=xiaomi 22081212ug'],
            ['"M2010J19CG"', true, 'xiaomi=xiaomi m2010j19cg'],
            ['"21051182G"', true, 'xiaomi=xiaomi 21051182g'],
            ['"22011119UY"', true, 'xiaomi=xiaomi 22011119uy'],
            ['"220733SG"', true, 'xiaomi=xiaomi 220733sg'],
            ['"Mi Note 10 Lite"', true, 'xiaomi=xiaomi mi note 10 lite'],
            ['"Mi Note 10 Pro"', true, 'xiaomi=xiaomi mi note 10 pro'],
            ['"22101316UG"', true, 'xiaomi=xiaomi 22101316ug'],
            ['"23028RN4DG"', true, 'xiaomi=xiaomi 23028rn4dg'],
            ['"23021RAA2Y"', true, 'xiaomi=xiaomi 23021raa2y'],
            ['"22126RN91Y"', true, 'xiaomi=xiaomi 22126rn91y'],
            ['"2211133G"', true, 'xiaomi=xiaomi 2211133g'],
            ['"2112123AG"', true, 'xiaomi=xiaomi 2112123ag'],
            ['"21091116UG"', true, 'xiaomi=xiaomi 21091116ug'],
            ['"POCO F2 Pro"', true, 'xiaomi=xiaomi pocophone f2 pro'],
            ['"M2002J9G"', true, 'xiaomi=xiaomi m2002j9g'],
            ['"2209116AG"', true, 'xiaomi=xiaomi 2209116ag'],
            ['"M2004J19C"', true, 'xiaomi=xiaomi m2004j19c'],
            ['"M2012K11G"', true, 'xiaomi=xiaomi m2012k11g'],
            ['"M2007J17G"', true, 'xiaomi=xiaomi m2007j17g'],
            ['"M2006C3MNG"', true, 'xiaomi=xiaomi m2006c3mng'],
            ['"2201117PG"', true, 'xiaomi=xiaomi 2201117pg'],
            ['"22071212AG"', true, 'xiaomi=xiaomi 22071212ag'],
            ['"2201116PG"', true, 'xiaomi=xiaomi 2201116pg'],
            ['"2203129G"', true, 'xiaomi=xiaomi 2203129g'],
            ['"21051182C"', true, 'xiaomi=xiaomi 21051182c'],
            ['"22111317PG"', true, 'xiaomi=xiaomi 22111317pg'],
            ['"M2103K19PG"', true, 'xiaomi=xiaomi m2103k19pg'],
            ['"Mi 10 Pro"', true, 'xiaomi=xiaomi mi 10 pro 5g'],
            ['"21121210G"', true, 'xiaomi=xiaomi 21121210g'],
            ['"22101320G"', true, 'xiaomi=xiaomi 22101320g'],
            ['"220233L2G"', true, 'xiaomi=xiaomi 220233l2g'],
            ['"M2007J3SG"', true, 'xiaomi=xiaomi m2007j3sg'],
            ['"Mi Note 2"', true, 'xiaomi=xiaomi mi note 2'],
            ['"Redmi Note 8T"', true, 'xiaomi=xiaomi redmi note 8t'],
            ['"2405CRPFDC"', true, 'xiaomi=xiaomi 2405crpfdc'],
            ['"Redmi Note 9S"', true, 'xiaomi=xiaomi redmi note 9s'],
            ['"Mi A2 Lite"', true, 'xiaomi=xiaomi mi a2 lite'],
            ['"Redmi 5A"', true, 'xiaomi=xiaomi redmi 5a'],
            ['"M2007J20CG"', true, 'xiaomi=xiaomi m2007j20cg'],
            ['"Redmi 6"', true, 'xiaomi=xiaomi redmi 6'],
            ['"Mi Note 10"', true, 'xiaomi=xiaomi mi note 10'],
            ['"Mi 10"', true, 'xiaomi=xiaomi mi 10'],
            ['"POCOPHONE F1"', true, 'xiaomi=xiaomi pocophone f1'],
            ['"Redmi 7"', true, 'xiaomi=xiaomi redmi 7'],
            ['"M2007J3SY"', true, 'xiaomi=xiaomi m2007j3sy'],
            ['"Redmi 8"', true, 'xiaomi=xiaomi redmi 8'],
            ['"Mi 9T Pro"', true, 'xiaomi=xiaomi mi 9t pro'],
            ['"MI 9"', true, 'xiaomi=xiaomi mi 9'],
            ['"M2006C3LG"', true, 'xiaomi=xiaomi m2006c3lg'],
            ['"2407FPN8EG"', true, 'xiaomi=xiaomi 2407fpn8eg'],
            ['"23117RA68G"', true, 'xiaomi=xiaomi 23117ra68g'],
            ['"23013PC75G"', true, 'xiaomi=xiaomi 23013pc75g'],
            ['"23046RP50C"', true, 'xiaomi=xiaomi 23046rp50c'],
            ['"2312DRAABG"', true, 'xiaomi=xiaomi 2312draabg'],
            ['"23127PN0CG"', true, 'xiaomi=xiaomi 23127pn0cg'],
            ['"22031116BG"', true, 'xiaomi=xiaomi 22031116bg'],
            ['"23108RN04Y"', true, 'xiaomi=xiaomi 23108rn04y'],
            ['"23124RA7EO"', true, 'xiaomi=xiaomi 23124ra7eo'],
            ['"23106RN0DA"', true, 'xiaomi=xiaomi 23106rn0da'],
            ['"23090RA98G"', true, 'xiaomi=xiaomi 23090ra98g'],
            // ZTE
            ['"ZTE A2121E"', true, 'zte=zte a2121e'],
            ['"ZTE Blade 10 Vita"', true, 'zte=zte blade 10 vita'],
            ['"ZTE Blade A3 2020"', true, 'zte=zte blade a3 2020'],
            ['"ZTE 8045"', true, 'zte=zte 8045'],
            ['"ZTE A2322G"', true, 'zte=zte a2322g'],
            ['"ZTE A7030"', true, 'zte=zte a7030'],
            ['"ZTE A7020"', true, 'zte=zte a7020'],
            ['"ZTE Blade A5 2020"', true, 'zte=zte blade a5 2020'],
            ['"ZTE 8030"', true, 'zte=zte 8030'],
            ['"ZTE BLADE A0620"', true, 'zte=zte blade a0620'],
            ['"ZTE 8050"', true, 'zte=zte 8050'],
            ['"ZTE 7060"', true, 'zte=zte 7060'],
            // Samsung
            ['"SM-A415F"', true, 'samsung=samsung sm-a415f'],
            ['"SM-A505FN"', true, 'samsung=samsung sm-a505fn'],
            ['"SM-A515F"', true, 'samsung=samsung sm-a515f'],
            ['"SM-G960F"', true, 'samsung=samsung sm-g960f'],
            ['"SM-A405FN"', true, 'samsung=samsung sm-a405fn'],
            ['"SM-S901B"', true, 'samsung=samsung sm-s901b'],
            ['"SM-S901U"', true, 'samsung=samsung sm-s901u'],
            ['"SM-S901U1"', true, 'samsung=samsung sm-s901u1'],
            ['"SM-S918B"', true, 'samsung=samsung sm-s918b'],
            ['"SM-S908B"', true, 'samsung=samsung sm-s908b'],
            ['"SM-S908U"', true, 'samsung=samsung sm-s908u'],
            ['"SM-S908U1"', true, 'samsung=samsung sm-s908u1'],
            ['"SM-G780G"', true, 'samsung=samsung sm-g780g'],
            ['"SM-A536B"', true, 'samsung=samsung sm-a536b'],
            ['"SM-A528B"', true, 'samsung=samsung sm-a528b'],
            ['"SM-A135F"', true, 'samsung=samsung sm-a135f'],
            ['"SM-T510"', true, 'samsung=samsung sm-t510'],
            ['"SM-T970"', true, 'samsung=samsung sm-t970'],
            ['"SM-T580"', true, 'samsung=samsung sm-t580'],
            ['"SM-T550"', true, 'samsung=samsung sm-t550'],
            ['"SM-T813"', true, 'samsung=samsung sm-t813'],
            ['"SM-A336B"', true, 'samsung=samsung sm-a336b'],
            ['"SM-A336E"', true, 'samsung=samsung sm-a336e'],
            ['"SM-A127F"', true, 'samsung=samsung sm-a127f'],
            ['"SM-G525F"', true, 'samsung=samsung sm-g525f'],
            ['"SM-A226BR"', true, 'samsung=samsung sm-a226br'],
            ['"SM-A226B"', true, 'samsung=samsung sm-a226b'],
            ['"SM-A546B"', true, 'samsung=samsung sm-a546b'],
            ['"SM-T220"', true, 'samsung=samsung sm-t220'],
            ['"SM-T225"', true, 'samsung=samsung sm-t225'],
            ['"SM-T225N"', true, 'samsung=samsung sm-t225n'],
            ['"SM-A326B"', true, 'samsung=samsung sm-a326b'],
            ['"SM-A326U"', true, 'samsung=samsung sm-a326u'],
            ['"SM-A725F"', true, 'samsung=samsung sm-a725f'],
            ['"SM-G990B"', true, 'samsung=samsung sm-g990b'],
            ['"SM-G990B2"', true, 'samsung=samsung sm-g990b2'],
            ['"SM-G990E"', true, 'samsung=samsung sm-g990e'],
            ['"SM-A125F"', true, 'samsung=samsung sm-a125f'],
            ['"SM-P619"', true, 'samsung=samsung sm-p619'],
            ['"SM-P613"', true, 'samsung=samsung sm-p613'],
            ['"SM-A136B"', true, 'samsung=samsung sm-a136b'],
            ['"SM-G736B"', true, 'samsung=samsung sm-g736b'],
            ['"SM-F711B"', true, 'samsung=samsung sm-f711b'],
            ['"SM-F711U"', true, 'samsung=samsung sm-f711u'],
            ['"SM-A225F"', true, 'samsung=samsung sm-a225f'],
            ['"SM-A137F"', true, 'samsung=samsung sm-a137f'],
            ['"SM-A146P"', true, 'samsung=samsung sm-a146p'],
            ['"SM-A236B"', true, 'samsung=samsung sm-a236b'],
            ['"SM-A525F"', true, 'samsung=samsung sm-a525f'],
            ['"SM-F731B"', true, 'samsung=samsung sm-f731b'],
            ['"SM-F926B"', true, 'samsung=samsung sm-f926b'],
            ['"SM-S906B"', true, 'samsung=samsung sm-s906b'],
            ['"SM-S911B"', true, 'samsung=samsung sm-s911b'],
            ['"SM-S916B"', true, 'samsung=samsung sm-s916b'],
            ['"SM-X706B"', true, 'samsung=samsung sm-x706b'],
            ['"SM-X700"', true, 'samsung=samsung sm-x700'],
            ['"SM-X200"', true, 'samsung=samsung sm-x200'],
            ['"SM-X205"', true, 'samsung=samsung sm-x205'],
            ['"SM-T976B"', true, 'samsung=samsung sm-t976b'],
            ['"SM-T870"', true, 'samsung=samsung sm-t870'],
            ['"SM-T875"', true, 'samsung=samsung sm-t875'],
            ['"SM-T575"', true, 'samsung=samsung sm-t575'],
            ['"SM-M325FV"', true, 'samsung=samsung sm-m325fv'],
            ['"SM-M325F"', true, 'samsung=samsung sm-m325f'],
            ['"SM-M236B"', true, 'samsung=samsung sm-m236b'],
            ['"SM-G985F"', true, 'samsung=samsung sm-g985f'],
            ['"SM-G770F"', true, 'samsung=samsung sm-g770f'],
            ['"SM-F721B"', true, 'samsung=samsung sm-f721b'],
            ['"SM-A526B"', true, 'samsung=samsung sm-a526b'],
            ['"SM-A526U"', true, 'samsung=samsung sm-a526u'],
            ['"SM-A235F"', true, 'samsung=samsung sm-a235f'],
            ['"SM-A047F"', true, 'samsung=samsung sm-a047f'],
            ['"SM-A325F"', true, 'samsung=samsung sm-a325f'],
            ['"SM-M536B"', true, 'samsung=samsung sm-m536b'],
            ['"SM-M526BR"', true, 'samsung=samsung sm-m526br'],
            ['"SM-M127F"', true, 'samsung=samsung sm-m127f'],
            ['"SM-F936B"', true, 'samsung=samsung sm-f936b'],
            ['"SM-A145R"', true, 'samsung=samsung sm-a145r'],
            ['"SM-A145P"', true, 'samsung=samsung sm-a145p'],
            ['"SM-A045F"', true, 'samsung=samsung sm-a045f'],
            ['"SM-A037G"', true, 'samsung=samsung sm-a037g'],
            ['"SM-A037F"', true, 'samsung=samsung sm-a037f'],
            ['"SM-A426B"', true, 'samsung=samsung sm-a426b'],
            ['"SM-A042F"', true, 'samsung=samsung sm-a042f'],
            ['"SM-A025G"', true, 'samsung=samsung sm-a025g'],
            ['"SM-A025F"', true, 'samsung=samsung sm-a025f'],
            ['"SM-M135F"', true, 'samsung=samsung sm-m135f'],
            ['"SM-A035F"', true, 'samsung=samsung sm-a035f'],
            ['"SM-A035M"', true, 'samsung=samsung sm-a035m'],
            ['"SM-A035G"', true, 'samsung=samsung sm-a035g'],
            ['"SM-M225FV"', true, 'samsung=samsung sm-m225fv'],
            ['"SM-A022G"', true, 'samsung=samsung sm-a022g'],
            ['"SM-A022F"', true, 'samsung=samsung sm-a022f'],
            ['"SM-M336B"', true, 'samsung=samsung sm-m336b'],
            ['"SM-M336BU"', true, 'samsung=samsung sm-m336bu'],
            ['"SM-M115F"', true, 'samsung=samsung sm-m115f'],
            ['"SM-T595"', true, 'samsung=samsung sm-t595'],
            ['"SM-T830"', true, 'samsung=samsung sm-t830'],
            ['"SM-T835"', true, 'samsung=samsung sm-t835'],
            ['"SM-T733"', true, 'samsung=samsung sm-t733'],
            ['"SM-T736B"', true, 'samsung=samsung sm-t736b'],
            ['"SM-X900"', true, 'samsung=samsung sm-x900'],
            ['"SM-X906B"', true, 'samsung=samsung sm-x906b'],
            ['"SM-G965F"', true, 'samsung=samsung sm-g965f'],
            ['"SM-G975F"', true, 'samsung=samsung sm-g975f'],
            ['"SM-A217F"', true, 'samsung=samsung sm-a217f'],
            ['"SM-G988B"', true, 'samsung=samsung sm-g988b'],
            ['"SM-A750FN"', true, 'samsung=samsung sm-a750fn'],
            ['"SM-N960F"', true, 'samsung=samsung sm-n960f'],
            ['"SM-G781B"', true, 'samsung=samsung sm-g781b'],
            ['"SM-A105FN"', true, 'samsung=samsung sm-a105fn'],
            ['SM-G920F', true, 'samsung=samsung sm-g920f'],
            ['SM-G955F', true, 'samsung=samsung sm-g955f'],
            ['SM-A715F', true, 'samsung=samsung sm-a715f'],
            ['SM-P610', true, 'samsung=samsung sm-p610'],
            ['SM-G998B', true, 'samsung=samsung sm-g998b'],
            ['SM-G973U1', true, 'samsung=samsung sm-g973u1'],
            ['SM-J415FN', true, 'samsung=samsung sm-j415fn'],
            ['SM-T585', true, 'samsung=samsung sm-t585'],
            ['SM-T725', true, 'samsung=samsung sm-t725'],
            ['SM-A202F', true, 'samsung=samsung sm-a202f'],
            ['SM-A320FL', true, 'samsung=samsung sm-a320fl'],
            ['SM-T590', true, 'samsung=samsung sm-t590'],
            ['SM-T720', true, 'samsung=samsung sm-t720'],
            ['SM-M315F', true, 'samsung=samsung sm-m315f'],
            ['SM-G973F', true, 'samsung=samsung sm-g973f'],
            ['SM-T719', true, 'samsung=samsung sm-t719'],
            ['SM-G980F', true, 'samsung=samsung sm-g980f'],
            ['SM-T860', true, 'samsung=samsung sm-t860'],
            ['SM-A600FN', true, 'samsung=samsung sm-a600fn'],
            ['SM-A346B', true, 'samsung=samsung sm-a346b'],
            ['SM-A520F', true, 'samsung=samsung sm-a520f'],
            ['SM-G935F', true, 'samsung=samsung sm-g935f'],
            ['SM-G991B', true, 'samsung=samsung sm-g991b'],
            ['SM-G981B', true, 'samsung=samsung sm-g981b'],
            ['SCG22', true, 'samsung=samsung scg22'],
            ['SM-G900F', true, 'samsung=samsung sm-g900f'],
            ['SM-A605FN', true, 'samsung=samsung sm-a605fn'],
            ['SM-T805', true, 'samsung=samsung sm-t805'],
            ['SM-S921B', true, 'samsung=samsung sm-s921b'],
            ['SM-G781V', true, 'samsung=samsung sm-g781v'],
            ['SM-T500', true, 'samsung=samsung sm-t500'],
            ['SM-N770F', true, 'samsung=samsung sm-n770f'],
            ['SM-T865', true, 'samsung=samsung sm-t865'],
            ['SM-A920F', true, 'samsung=samsung sm-a920f'],
            ['SM-S928B', true, 'samsung=samsung sm-s928b'],
            ['SM-G970F', true, 'samsung=samsung sm-g970f'],
            ['SM-J600FN', true, 'samsung=samsung sm-j600fn'],
            ['SM-N950F', true, 'samsung=samsung sm-n950f'],
            ['SM-G780F', true, 'samsung=samsung sm-g780f'],
            ['SM-G950F', true, 'samsung=samsung sm-g950f'],
            ['SM-N986B', true, 'samsung=samsung sm-n986b'],
            ['SM-P600', true, 'samsung=samsung sm-p600'],
            ['SM-J330F', true, 'samsung=samsung sm-j330f'],
            ['SM-A310F', true, 'samsung=samsung sm-a310f'],
            ['SM-A315F', true, 'samsung=samsung sm-a315f'],
            ['SM-G930F', true, 'samsung=samsung sm-g930f'],
            ['SM-F7110', true, 'samsung=samsung sm-f7110'],
            ['SM-N9005', true, 'samsung=samsung sm-n9005'],
            ['SM-J510FN', true, 'samsung=samsung sm-j510fn'],
            ['SM-G903F', true, 'samsung=samsung sm-g903f'],
            ['SM-A315G', true, 'samsung=samsung sm-a315g'],
            ['SM-N975F', true, 'samsung=samsung sm-n975f'],
            ['SM-A805F', true, 'samsung=samsung sm-a805f'],
            ['SM-T535', true, 'samsung=samsung sm-t535'],
            ['SM-T555', true, 'samsung=samsung sm-t555'],
            ['SM-G996B', true, 'samsung=samsung sm-g996b'],
            ['SM-A510F', true, 'samsung=samsung sm-a510f'],
            ['SM-J530F', true, 'samsung=samsung sm-j530f'],
            ['SM-A705FN', true, 'samsung=samsung sm-a705fn'],
            ['SM-N980F', true, 'samsung=samsung sm-n980f'],
            ['SM-N970F', true, 'samsung=samsung sm-n970f'],
            ['SM-G986B', true, 'samsung=samsung sm-g986b'],
            ['SM-G928F', true, 'samsung=samsung sm-g928f'],
            ['SM-A107F', true, 'samsung=samsung sm-a107f'],
            ['SM-J730F', true, 'samsung=samsung sm-j730f'],
            ['SM-T515', true, 'samsung=samsung sm-t515'],
            ['SM-G998N', true, 'samsung=samsung sm-g998n'],
            ['SM-G925F', true, 'samsung=samsung sm-g925f'],
            ['SM-J610FN', true, 'samsung=samsung sm-j610fn'],
            ['SM-P615', true, 'samsung=samsung sm-p615'],
            ['SM-T819', true, 'samsung=samsung sm-t819'],
            ['SM-M215F', true, 'samsung=samsung sm-m215f'],
            ['GT-I9515', true, 'samsung=samsung gt-i9515'],
            ['SM-G398FN', true, 'samsung=samsung sm-g398fn'],
            ['SM-T815', true, 'samsung=samsung sm-t815'],
            ['SM-A207F', true, 'samsung=samsung sm-a207f'],
            ['SM-S928U', true, 'samsung=samsung sm-s928u'],
            ['SM-A156B', true, 'samsung=samsung sm-a156b'],
            ['SM-A155F', true, 'samsung=samsung sm-a155f'],
            ['SM-A346E', true, 'samsung=samsung sm-a346e'],
            ['SM-X216B', true, 'samsung=samsung sm-x216b'],
            ['SM-A145F', true, 'samsung=samsung sm-a145f'],
            ['SM-A546E', true, 'samsung=samsung sm-a546e'],
            ['SM-A256E', true, 'samsung=samsung sm-a256e'],
            ['SM-A256B', true, 'samsung=samsung sm-a256b'],
            ['SM-F956B', true, 'samsung=samsung sm-f956b'],
            ['SM-A536E', true, 'samsung=samsung sm-a536e'],
            ['SM-X110', true, 'samsung=samsung sm-x110'],
            ['SM-S711B', true, 'samsung=samsung sm-s711b'],
            ['SM-A556B', true, 'samsung=samsung sm-a556b'],
            ['SM-G986U', true, 'samsung=samsung sm-g986u'],
            ['SM-T295', true, 'samsung=samsung sm-t295'],
            ['SM-G973F/G973FXXU9DTJA', true, 'samsung=samsung sm-g973f'],
            ['"SM-A515F/A515FXXU8HWI1"', true, 'samsung=samsung sm-a515f'],
            ['SM-F711U1', true, 'samsung=samsung sm-f711u1'],
            ['SM-J530FM', true, 'samsung=samsung sm-j530fm'],
            ['SM-T900', true, 'samsung=samsung sm-t900'],
            ['SM-S127DL', true, 'samsung=samsung sm-s127dl'],
            ['SM-G9980', true, 'samsung=samsung sm-g9980'],
            ['SM-J810Y', true, 'samsung=samsung sm-j810y'],
            ['SM-G900I', true, 'samsung=samsung sm-g900i'],
            ['SM-G955U', true, 'samsung=samsung sm-g955u'],
            ['SM-J610F', true, 'samsung=samsung sm-j610f'],
            ['SM-S9080', true, 'samsung=samsung sm-s9080'],
            ['SM-G950W', true, 'samsung=samsung sm-g950w'],
            ['SM-G965U1', true, 'samsung=samsung sm-g965u1'],
            ['SM-J120FN', true, 'samsung=samsung sm-j120fn'],
            ['SM-N960U1', true, 'samsung=samsung sm-n960u1'],
            ['SM-P905', true, 'samsung=samsung sm-p905'],
            ['SM-G920I', true, 'samsung=samsung sm-g920i'],
            ['SM-G531F', true, 'samsung=samsung sm-g531f'],
            ['SM-P605', true, 'samsung=samsung sm-p605'],
            ['SM-E700F', true, 'samsung=samsung sm-e700f'],
            ['SM-G970U', true, 'samsung=samsung sm-g970u'],
            ['SM-A7050', true, 'samsung=samsung sm-a7050'],
            ['SM-J727V', true, 'samsung=samsung sm-j727v'],
            ['SM-A8000', true, 'samsung=samsung sm-a8000'],
            ['SM-A516B', true, 'samsung=samsung sm-a516b'],
            ['SM-X806B', true, 'samsung=samsung sm-x806b'],
            ['SM-J111F', true, 'samsung=samsung sm-j111f'],
            ['GT-I9506', true, 'samsung=samsung gt-i9506'],
            ['SM-M305F', true, 'samsung=samsung sm-m305f'],
            ['SM-G998U', true, 'samsung=samsung sm-g998u'],
            ['SM-A908B', true, 'samsung=samsung sm-a908b'],
            ['SM-N985F', true, 'samsung=samsung sm-n985f'],
            ['SM-G960U1', true, 'samsung=samsung sm-g960u1'],
            ['SM-S908E', true, 'samsung=samsung sm-s908e'],
            ['SM-A307G', true, 'samsung=samsung sm-a307g'],
            ['SM-N9500', true, 'samsung=samsung sm-n9500'],
            ['SM-J410F', true, 'samsung=samsung sm-j410f'],
            ['SM-G991N', true, 'samsung=samsung sm-g991n'],
            ['SM-A260F', true, 'samsung=samsung sm-a260f'],
            ['SM-G981U1', true, 'samsung=samsung sm-g981u1'],
            ['SM-G9750', true, 'samsung=samsung sm-g9750'],
            ['SM-X710', true, 'samsung=samsung sm-x710'],
            ['SM-A305FN', true, 'samsung=samsung sm-a305fn'],
            ['SM-J250F', true, 'samsung=samsung sm-j250f'],
            ['SM-A736B', true, 'samsung=samsung sm-a736b'],
            ['SM-S906E', true, 'samsung=samsung sm-s906e'],
            // Huawei
            ['"LGE-NX9"', true, 'huawei=huawei lge-nx9'],
            ['"VOG-L29"', true, 'huawei=huawei vog-l29'],
            ['"MAR-LX1B"', true, 'huawei=huawei mar-lx1b'],
            ['"LYA-L09"', true, 'huawei=huawei lya-l09'],
            ['"NEN-LX1"', true, 'huawei=huawei nen-lx1'],
            ['"PPA-LX1"', true, 'huawei=huawei ppa-lx1'],
            ['"JAD-LX9"', true, 'huawei=huawei jad-lx9'],
            ['"REA-NX9"', true, 'huawei=huawei rea-nx9'],
            ['"NTN-LX1"', true, 'huawei=huawei ntn-lx1'],
            ['"DBY-W09"', true, 'huawei=huawei dby-w09'],
            ['"NAM-LX9"', true, 'huawei=huawei nam-lx9'],
            ['"STK-LX1"', true, 'huawei=huawei stk-lx1'],
            ['"PPA-LX2"', true, 'huawei=huawei ppa-lx2'],
            ['"AGR-W09"', true, 'huawei=huawei agr-w09'],
            ['"AGS3K-W09"', true, 'huawei=huawei ags3k-w09'],
            ['"NTH-NX9"', true, 'huawei=huawei nth-nx9'],
            ['"NOH-AN01"', true, 'huawei=huawei noh-an01'],
            ['"HLK-L41"', true, 'huawei=huawei hlk-l41'],
            ['"BAH3-W59"', true, 'huawei=huawei bah3-w59'],
            ['"BAH3-W09"', true, 'huawei=huawei bah3-w09'],
            ['"BAH3-L09"', true, 'huawei=huawei bah3-l09'],
            ['"HRY-LX1T"', true, 'huawei=huawei hry-lx1t'],
            ['"HRY-LX1"', true, 'huawei=huawei hry-lx1'],
            ['"JSN-L21"', true, 'huawei=huawei jsn-l21'],
            ['"JKM-LX2"', true, 'huawei=huawei jkm-lx2'],
            ['"STK-L21"', true, 'huawei=huawei stk-l21'],
            ['"SNE-LX1"', true, 'huawei=huawei sne-lx1'],
            ['"INE-LX1"', true, 'huawei=huawei ine-lx1'],
            ['"INE-LX1r"', true, 'huawei=huawei ine-lx1r'],
            ['"FNE-NX9"', true, 'huawei=huawei fne-nx9'],
            ['"PGT-N19"', true, 'huawei=huawei pgt-n19'],
            ['"AGS2-W09"', true, 'huawei=huawei ags2-w09'],
            ['"ELS-NX9"', true, 'huawei=huawei els-nx9'],
            ['"ANE-LX1"', true, 'huawei=huawei ane-lx1'],
            ['"YAL-L41"', true, 'huawei=huawei yal-l41'],
            ['"JAT-L41"', true, 'huawei=huawei jat-l41'],
            ['"JNY-LX1"', true, 'huawei=huawei jny-lx1'],
            ['"EVR-L29"', true, 'huawei=huawei evr-l29'],
            ['"BAH-L09"', true, 'huawei=huawei bah-l09'],
            ['"ART-L29"', true, 'huawei=huawei art-l29'],
            ['"BAH2-W19"', true, 'huawei=huawei bah2-w19'],
            ['"AGS2-L09"', true, 'huawei=huawei ags2-l09'],
            ['"YAL-L21"', true, 'huawei=huawei yal-l21'],
            ['"RNE-L21"', true, 'huawei=huawei rne-l21'],
            ['"POT-LX1"', true, 'huawei=huawei pot-lx1'],
            ['"SHT-AL09"', true, 'huawei=huawei sht-al09'],
            ['"BAH-W09"', true, 'huawei=huawei bah-w09'],
            ['"ELE-L29"', true, 'huawei=huawei ele-l29'],
            ['"FIG-LX1"', true, 'huawei=huawei fig-lx1'],
            ['"MAR-LX1A"', true, 'huawei=huawei mar-lx1a'],
            ['"BLA-L09"', true, 'huawei=huawei bla-l09'],
            ['"CMR-AL09"', true, 'huawei=huawei cmr-al09'],
            ['"EML-L29"', true, 'huawei=huawei eml-l29'],
            ['"MRD-LX1"', true, 'huawei=huawei mrd-lx1'],
            ['"CLT-L29"', true, 'huawei=huawei clt-l29'],
            ['"HUAWEI SCL-L21"', true, 'huawei=huawei scl-l21'],
            ['"LYA-L29"', true, 'huawei=huawei lya-l29'],
            ['"AMN-LX9"', true, 'huawei=huawei amn-lx9'],
            ['"PRA-LX1"', true, 'huawei=huawei pra-lx1'],
            ['"ATU-L21"', true, 'huawei=huawei atu-l21'],
            ['"WAS-LX1A"', true, 'huawei=huawei was-lx1a'],
            ['"AGS-W09"', true, 'huawei=huawei ags-w09'],
            ['"BND-L21"', true, 'huawei=huawei bnd-l21'],
            ['"HUAWEI CAN-L11"', true, 'huawei=huawei can-l11'],
            ['"COR-L29"', true, 'huawei=huawei cor-l29'],
            ['"VTR-L09"', true, 'huawei=huawei vtr-l09'],
            ['"BKL-L09"', true, 'huawei=huawei bkl-l09'],
            ['"AUM-L29"', true, 'huawei=huawei aum-l29'],
            ['"POT-LX1T"', true, 'huawei=huawei pot-lx1t'],
            ['"POT-LX1A"', true, 'huawei=huawei pot-lx1a'],
            ['"EML-L09"', true, 'huawei=huawei eml-l09'],
            ['"CMR-W09"', true, 'huawei=huawei cmr-w09'],
            ['"BLA-L29"', true, 'huawei=huawei bla-l29'],
            ['"EVR-N29"', true, 'huawei=huawei evr-n29'],
            ['"STF-L09"', true, 'huawei=huawei stf-l09'],
            ['"HMA-L29"', true, 'huawei=huawei hma-l29'],
            ['"DUB-LX1"', true, 'huawei=huawei dub-lx1'],
            ['"HUAWEI M2-A01W"', true, 'huawei=huawei m2-a01w'],
            ['"DIG-L21HN"', true, 'huawei=huawei dig-l21hn'],
            ['"HUAWEI VNS-L31"', true, 'huawei=huawei vns-l31'],
            ['"INE-LX2r"', true, 'huawei=huawei ine-lx2r'],
            ['"ALI-NX1"', true, 'huawei=huawei ali-nx1'],
            // Lenovo
            ['"Lenovo TB-X304F"', true, 'lenovo=lenovo tb-x304f'],
            ['"X1030X"', true, 'lenovo=lenovo x1030x'],
            ['"Lenovo YT-J706F"', true, 'lenovo=lenovo yt-j706f'],
            ['"Lenovo TB-X306X"', true, 'lenovo=lenovo tb-x306x'],
            ['"Lenovo TB-X306XA"', true, 'lenovo=lenovo tb-x306xa'],
            ['"Lenovo TB-J616F"', true, 'lenovo=lenovo tb-j616f'],
            ['"Lenovo TB-J616X"', true, 'lenovo=lenovo tb-j616x'],
            ['"Lenovo TB-X606F"', true, 'lenovo=lenovo tb-x606f'],
            ['"Lenovo TB-8705F"', true, 'lenovo=lenovo tb-8705f'],
            ['"Lenovo TB-8505X"', true, 'lenovo=lenovo tb-8505x'],
            ['"Lenovo TB-X605F"', true, 'lenovo=lenovo tb-x605f'],
            ['"Lenovo TB-8504X"', true, 'lenovo=lenovo tb-8504x'],
            ['"Lenovo YT3-X50F"', true, 'lenovo=lenovo yt3-x50f'],
            ['"Lenovo TB-X705F"', true, 'lenovo=lenovo tb-x705f'],
            ['"Lenovo TB-8505FS"', true, 'lenovo=lenovo tb-8505fs'],
            ['"Lenovo YT-X705F"', true, 'lenovo=lenovo yt-x705f'],
            ['"TB350XU"', true, 'lenovo=lenovo tb350xu'],
            ['"B5032"', true, 'lenovo=lenovo b5032'],
            ['"TB330FU"', true, 'lenovo=lenovo tb330fu'],
            ['"TB350FU"', true, 'lenovo=lenovo tb350fu'],
            // Nokia
            ['"Nokia G50"', true, 'nokia=nokia g50'],
            ['"Nokia G20"', true, 'nokia=nokia g20'],
            ['"Nokia X10"', true, 'nokia=nokia x10'],
            ['"Nokia X20"', true, 'nokia=nokia x20'],
            ['"Nokia G22"', true, 'nokia=nokia g22'],
            ['"Nokia C12"', true, 'nokia=nokia c12'],
            ['"Nokia 2.3"', true, 'nokia=nokia 2.3'],
            ['"Nokia 5.4"', true, 'nokia=nokia 5.4'],
            ['"Nokia 8.3 5G"', true, 'nokia=nokia 8.3 5g'],
            ['"Nokia G11"', true, 'nokia=nokia g11'],
            ['"Nokia 8.1"', true, 'nokia=nokia 8.1'],
            ['"Nokia 5.1"', true, 'nokia=nokia 5.1'],
            ['"Nokia 7.1"', true, 'nokia=nokia 7.1'],
            ['"Nokia 7.2"', true, 'nokia=nokia 7.2'],
            ['"Nokia 4.2"', true, 'nokia=nokia 4.2'],
            ['"Nokia 6.1"', true, 'nokia=nokia 6.1'],
            ['"Nokia 6.2"', true, 'nokia=nokia 6.2'],
            // Microsoft
            ['"Surface Duo"', true, 'microsoft=microsoft surface duo'],
            ['"Xbox"', true, 'microsoft=microsoft xbox one'],
            // realme
            ['"RMX3085"', true, 'realme=realme rmx3085'],
            ['"RMX3231"', true, 'realme=realme rmx3231'],
            ['"RMX3393"', true, 'realme=realme rmx3393'],
            ['"RMX3370"', true, 'realme=realme rmx3370'],
            ['"RMX3241"', true, 'realme=realme rmx3241'],
            ['"RMX3501"', true, 'realme=realme rmx3501'],
            ['"RMX3151"', true, 'realme=realme rmx3151'],
            ['"RMX3263"', true, 'realme=realme rmx3263'],
            ['"RMX3201"', true, 'realme=realme rmx3201'],
            ['"RMX2202"', true, 'realme=realme rmx2202'],
            ['"RMX2155"', true, 'realme=realme rmx2155'],
            ['"RMX3081"', true, 'realme=realme rmx3081'],
            ['"RMX2193"', true, 'realme=realme rmx2193'],
            ['"RMX3311"', true, 'realme=realme rmx3311'],
            ['"RMX3521"', true, 'realme=realme rmx3521'],
            ['"RMX3269"', true, 'realme=realme rmx3269'],
            ['"RMX3363"', true, 'realme=realme rmx3363'],
            ['"RMX3511"', true, 'realme=realme rmx3511'],
            ['"RMX3301"', true, 'realme=realme rmx3301'],
            ['"RMX3242"', true, 'realme=realme rmx3242'],
            ['"RMX3563"', true, 'realme=realme rmx3563'],
            ['"RMX3623"', true, 'realme=realme rmx3623'],
            ['"RMX1931"', true, 'realme=realme rmx1931'],
            // Motorola
            ['"moto g200 5G"', true, 'motorola=motorola moto g200 5g'],
            ['"motorola razr 5G"', true, 'motorola=motorola razr 5g'],
            ['"moto g42"', true, 'motorola=motorola moto g42'],
            ['"moto g(60)"', true, 'motorola=motorola moto g60'],
            ['"moto g(50)"', true, 'motorola=motorola moto g50'],
            ['"moto g(30)"', true, 'motorola=motorola moto g30'],
            ['"moto g pro"', true, 'motorola=motorola moto g pro'],
            ['"moto e32(s)"', true, 'motorola=motorola moto e32s'],
            ['"moto e30"', true, 'motorola=motorola moto e30'],
            ['"moto e20"', true, 'motorola=motorola moto e20'],
            ['"moto e40"', true, 'motorola=motorola moto e40'],
            ['"moto g(8) plus"', true, 'motorola=motorola moto g8 plus'],
            ['"motorola one macro"', true, 'motorola=motorola one macro'],
            ['"Motorola Defy"', true, 'motorola=motorola defy 2021'],
            ['"moto g 5G"', true, 'motorola=motorola moto g 5g'],
            ['"motorola edge 20"', true, 'motorola=motorola edge 20 2021'],
            ['"motorola edge 20 lite"', true, 'motorola=motorola edge 20 lite'],
            ['"motorola edge 20 pro"', true, 'motorola=motorola edge 20 pro'],
            ['"motorola edge 30 neo"', true, 'motorola=motorola edge 30 neo'],
            ['"motorola edge 30"', true, 'motorola=motorola edge 30'],
            ['"motorola edge 30 ultra"', true, 'motorola=motorola edge 30 ultra'],
            ['moto g(20)', true, 'motorola=motorola moto g20'],
            ['motorola one', true, 'motorola=motorola one'],
            ['motorola one vision', true, 'motorola=motorola one vision'],
            ['moto g(8) power', true, 'motorola=motorola moto g8 power'],
            ['Moto G (4)', true, 'motorola=motorola moto g4'],
            ['moto g(6)', true, 'motorola=motorola moto g6'],
            ['moto g(6) play', true, 'motorola=motorola moto g6 play'],
            ['moto g(9) plus', true, 'motorola=motorola moto g9 plus'],
            ['moto g(7) play', true, 'motorola=motorola moto g7 play'],
            ['moto g(9) play', true, 'motorola=motorola moto g9 play'],
            ['Moto G (5S)', true, 'motorola=motorola xt1793'],
            ['Moto G (5)', true, 'motorola=motorola moto g5'],
            ['moto g04s', true, 'motorola=motorola moto g04s'],
            ['motorola edge 40', true, 'motorola=motorola edge 40'],
            ['motorola edge 40 neo', true, 'motorola=motorola edge 40 neo'],
            ['moto g24', true, 'motorola=motorola moto g24'],
            // Sony
            ['"XQ-CC54"', true, 'sony=sony xq-cc54'],
            ['"XQ-BQ52"', true, 'sony=sony xq-bq52'],
            ['"XQ-BE52"', true, 'sony=sony xq-be52'],
            ['"H8266"', true, 'sony=sony h8266'],
            ['"XQ-BC52"', true, 'sony=sony xq-bc52'],
            ['"XQ-AU52"', true, 'sony=sony xq-au52'],
            ['"I4312"', true, 'sony=sony i4312'],
            ['"F5321"', true, 'sony=sony f5321'],
            ['"J9210"', true, 'sony=sony j9210'],
            ['"H3113"', true, 'sony=sony h3113'],
            ['"F3311"', true, 'sony=sony f3311'],
            ['"G8341"', true, 'sony=sony g8341'],
            ['"XQ-AT51"', true, 'sony=sony xq-at51'],
            ['"XQ-AS52"', true, 'sony=sony xq-as52'],
            ['"F5121"', true, 'sony=sony f5121'],
            ['"E5823"', true, 'sony=sony e5823'],
            ['"XQ-ES54"', true, 'sony=sony xq-es54'],
            ['"XQ-DC54"', true, 'sony=sony xq-dc54'],
            // Vivo
            ['"V2109"', true, 'vivo=vivo v2109'],
            ['"vivo 1716"', true, 'vivo=vivo 1716'],
            ['"vivo 1920"', true, 'vivo=vivo 1920'],
            ['"V2053"', true, 'vivo=vivo v2053'],
            ['"V2206"', true, 'vivo=vivo v2206'],
            // Fairphone
            ['"FP4"', true, 'fairphone=fairphone fp4'],
            ['"FP3"', true, 'fairphone=fairphone fp3'],
            // Oukitel
            ['"WP16"', true, 'oukitel=oukitel wp16'],
            ['"WP18"', true, 'oukitel=oukitel wp18'],
            ['"C17 Pro"', true, 'oukitel=oukitel c17 pro'],
            ['"C21 Pro"', true, 'oukitel=oukitel c21 pro'],
            // Ulefone
            ['"Note 6P"', true, 'ulefone=ulefone note 6p'],
            ['"Armor 11T 5G"', true, 'ulefone=ulefone armor 11t 5g'],
            ['"Armor X5"', true, 'ulefone=ulefone armor x5'],
            ['"Armor_6E"', true, 'ulefone=ulefone armor 6e'],
            ['"Note 16 Pro"', true, 'ulefone=ulefone note 16 pro'],
            // Doogee
            ['"N40Pro"', true, 'doogee=doogee n40 pro'],
            ['"S88Pro"', true, 'doogee=doogee s88 pro'],
            ['"S59Pro"', true, 'doogee=doogee s59 pro'],
            ['"S97Pro"', true, 'doogee=doogee s97 pro'],
            ['"X30"', true, 'doogee=doogee x30'],
            ['"S96Pro"', true, 'doogee=doogee s96 pro'],
            ['"X93"', true, 'doogee=doogee x93'],
            // shiftphones
            ['"SHIFT6mq"', true, 'shift-phones=shift-phones shift6mq'],
            // Cubot/Hafury
            ['"GT20"', true, 'cubot=cubot gt20'],
            ['"CUBOT KING KONG"', true, 'cubot=cubot king kong'],
            ['"KINGKONG 9"', true, 'cubot=cubot kingkong 9'],
            ['"KINGKONG 7"', true, 'cubot=cubot kingkong 7'],
            // Aoyodkg
            ['"AOYODKG_A38"', true, 'aoyodkg=aoyodkg a38'],
            // gigaset
            ['"E940-2795-00"', true, 'gigaset=gigaset e940-2795-00'],
            ['"E940-2796-00"', true, 'gigaset=gigaset e940-2796-00'],
            ['"GS185"', true, 'gigaset=gigaset gs185'],
            ['"GX290"', true, 'gigaset=gigaset gx290'],
            // wiko
            ['"W-V750BN-EEA"', true, 'wiko=wiko w-v750bn-eea'],
            ['"W-V680-EEA"', true, 'wiko=wiko w-v680-eea'],
            ['"W-V730-EEA"', true, 'wiko=wiko w-v730-eea'],
            ['"W-V720-EEA"', true, 'wiko=wiko w-v720-eea'],
            ['"W-V755-OPE"', true, 'wiko=wiko w-v755-ope'],
            // razer
            ['"Phone 2"', true, 'razer=razer phone 2'],
            // Alcatel
            ['"5024D_EEA"', true, 'alcatel=alcatel 5024d_eea'],
            ['"6025D_EEA"', true, 'alcatel=alcatel 6025d_eea'],
            // HTC
            ['"HTC Desire 19+"', true, 'htc=htc desire 19 plus'],
            ['"HTC U11"', true, 'htc=htc u11'],
            ['"HTC 10"', true, 'htc=htc 10'],
            ['"HTC 2PZF1"', true, 'htc=htc 2pzf1'],
            // teclast
            ['"P30S_EEA"', true, 'teclast=teclast p30s_eea'],
            ['"P25T_EEA"', true, 'teclast=teclast p25t_eea'],
            // alldocube
            ['"iPlay_40"', true, 'alldocube=alldocube iplay 40'],
            // dgtec
            ['"DG101HSTB"', true, 'dgtec=dgtec dg101hstb'],
            // coopers
            ['"CP20_Gold"', true, 'coopers=coopers cocp20gold'],
            // blackview
            ['"BV6800Pro"', true, 'blackview=blackview bv6800 pro'],
            ['"BV4900Pro"', true, 'blackview=blackview bv4900 pro'],
            ['"Tab 7 WiFi"', true, 'blackview=blackview tab 7 wifi'],
            // medion
            ['"B5532"', true, 'medion=medion b5532'],
            // caterpillar
            ['"S60"', true, 'caterpillar=caterpillar s60'],
            // blackberry
            ['"STV100-4"', true, 'rim=blackberry stv100-4'],
            // leeco
            ['"Le X820"', true, 'leeco=leeco le x820'],
            // wortmann
            ['"TERRA_PAD_1006"', true, 'wortmann=wortmann terra pad 1006'],
            // infinix
            ['"S5 Pro"', true, 'infinix=infinix s5 pro'],
            // cyrus
            ['"CS24"', true, 'cyrus=cyrus cs24'],
            // facetel
            ['"Q3-EEA"', true, 'facetel=facetel q3-eea'],
            // lectrus
            ['"LECT-TAB1011H"', true, 'lectrus=lectrus lect-tab1011h'],
            // sunmax
            ['"Model_6_pro_4G"', true, 'sunmax=sunmax model 6 pro max 4g'],
            ['"Model 6"', true, 'sunmax=sunmax model 6'],
            ['"Model A"', true, 'sunmax=sunmax model a'],
            ['"Model D"', true, 'sunmax=sunmax model d'],
            ['"Model S"', true, 'sunmax=sunmax model s'],
            ['"Model S 4G"', true, 'sunmax=sunmax model s 4g'],
            // captiva
            ['"Captiva Pad 10 3G Plus"', true, 'captiva=captiva pad 10 3g plus'],
            // toscido
            ['"M863-EEA"', true, 'toscido=toscido m863-eea'],
            // beafon
            ['"TW10"', true, 'beafon=beafon tw10'],
            // micromax
            ['"A065"', true, 'micromax=micromax a065'],
            // itel
            ['"itel L6006"', true, 'itel=itel l6006'],
            // vontar
            ['"HK1RBOX-X4"', true, 'vontar=vontar hk1 rbox x4'],
            // hisense
            ['"HLTE239E"', true, 'hisense=hisense hlte239e'],
            // insys
            ['"HN2-M16Q"', true, 'insys=insys hn2-m16q'],
            // aiwa
            ['"AWTX6"', true, 'aiwa=aiwa awtx6'],
            // walton
            ['"XANON X90"', true, 'walton=walton xanon x90'],
            // other
            ['"Model"', false, null],
            ['": "', false, null],
            ['""', false, null],
            ['"Some Unknown Model"', false, null],
        ];
    }
}
