VALIDATE_ALL_CODEBASE: true
LOG_LEVEL: INFO
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (vendor/)
ENABLE:
  - EDITORCONFIG
  - MARKDOWN
  - YAML
DISABLE:
  - SPELL
  #- COPYPASTE
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - YAML_V8R
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "(\\.idea|\\.editorconfig|\\.github|\\.phpunit\\.result\\.cache|LICENSE)"
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(composer\\.json)"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: "(\\.github)"
PHP_PHPCS_CONFIG_FILE: "phpcs.xml"
PHP_PHPCS_ARGUMENTS: "-n"
PHP_PHPSTAN_CONFIG_FILE: "phpstan.neon"
PHP_PHPSTAN_FILTER_REGEX_INCLUDE: "(src)"
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.github)"
