codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: pass
    project:
      default:   # default is the status check's name, not default settings
        target: 100%
        threshold: 1%
        if_ci_failed: success #success, failure, error, ignore
        informational: true
        only_pulls: false
    patch:
      default:
        informational: true

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [true :: must have a base report to post]
  require_head: false     # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]
