<?php

return [
    'test-00107-00000' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; en-za; SAMSUNG SM-G800H Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.6 Chrome/28.0.1500.94 Mobile Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Android WebView',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.6',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.4.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00107-00001' => [
        'ua'         => 'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaX6-00/40.0.002; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.33 Mobile Safari/533.4 3gpp-gba',
        'properties' => [
            'Browser_Name'            => 'Default Browser',
            'Browser_Type'            => 'unknown',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'Symbian OS',
            'Platform_Marketingname'  => 'Symbian OS',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Symbian Foundation',
            'Platform_Brand_Name'     => 'Symbian Foundation',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'test-00107-00002' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; SonyLT26i Build/6.2.B.1.96) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'Android',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.1.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'test-00107-00003' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Android 2.3.4; ro-ro; SonyEricssonLT18i Build/4.0.2.A.0.62) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
        'properties' => [
            'Browser_Name'            => 'Android',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '2.3.4',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'test-00107-00004' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.2.2; fa-ir; HUAWEI G750-U10 Build/HuaweiG750-U10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'Android',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.2.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'test-00107-00005' => [
        'ua'         => 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US) AppleWebKit/125.4 (KHTML, like Gecko, Safari) OmniWeb/v563.15',
        'properties' => [
            'Browser_Name'            => 'Omniweb',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'Mac OS X',
            'Platform_Marketingname'  => 'Mac OS X',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'Macintosh',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Macintosh',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
