<?php
/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2018, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);
namespace BrowserDetector\Factory\Browser;

use BrowserDetector\Factory\FactoryInterface;
use BrowserDetector\Loader\ExtendedLoaderInterface;
use Stringy\Stringy;
use UaResult\Os\OsInterface;

/**
 * Browser detection class
 */
class GenericBrowserFactory implements FactoryInterface
{
    /**
     * @var \BrowserDetector\Loader\ExtendedLoaderInterface
     */
    private $loader;

    /**
     * @param \BrowserDetector\Loader\ExtendedLoaderInterface $loader
     */
    public function __construct(ExtendedLoaderInterface $loader)
    {
        $this->loader = $loader;
    }

    /**
     * Gets the information about the browser by User Agent
     *
     * @param string                        $useragent
     * @param Stringy                       $s
     * @param \UaResult\Os\OsInterface|null $platform
     *
     * @return array
     */
    public function detect(string $useragent, Stringy $s, ?OsInterface $platform = null): array
    {
        $firstCheck = [
            'revip.info site analyzer' => 'reverse ip lookup',
            'reddit pic scraper'       => 'reddit pic scraper',
            'mozilla crawl'            => 'mozilla crawler',
        ];

        foreach ($firstCheck as $search => $key) {
            if ($s->contains($search, false)) {
                return $this->loader->load($key, $useragent);
            }
        }

        if ($s->startsWith('[fban', false)) {
            return $this->loader->load('facebook app', $useragent);
        }

        $checkBeforeMosbookmarks = [
            'ucbrowser'                           => 'ucbrowser',
            'uc browser'                          => 'ucbrowser',
            'ucweb'                               => 'ucbrowser',
            'ic opengraph crawler'                => 'ibm connections',
            'icab'                                => 'icab',
            'hggh phantomjs screenshoter'         => 'hggh screenshot system with phantomjs',
            'bl.uk_lddc_bot'                      => 'bl.uk_lddc_bot',
            'phantomas'                           => 'phantomas',
            'seznam screenshot-generator'         => 'seznam screenshot generator',
            'stagefright'                         => 'stagefright',
            'seznambot'                           => 'seznambot',
            'maxthon'                             => 'maxthon',
            'qqbrowser/mini'                      => 'qqbrowser mini',
            'qqbrowser'                           => 'qqbrowser',
            'pinterestbot'                        => 'pinterest bot',
            'pinterest'                           => 'pinterest app',
            't-online browser'                    => 't-online browser',
            'to-browser'                          => 't-online browser',
            'tob'                                 => 't-online browser',
            'epiphany'                            => 'epiphany',
            'omniweb'                             => 'omniweb',
            'windows-rss-platform'                => 'windows-rss-platform',
            'lssrocketcrawler'                    => 'lightspeed systems rocketcrawler',
            'outlook social connector'            => 'outlook social connector',
            'outlook'                             => 'outlook',
            'microsoft office protocol discovery' => 'ms opd',
            'excel '                              => 'excel',
            'excel/'                              => 'excel',
            'powerpoint'                          => 'powerpoint',
            'wordpress'                           => 'wordpress',
            'office word'                         => 'word',
            'microsoft word'                      => 'word',
            'word/'                               => 'word',
            'office onenote'                      => 'onenote',
            'microsoft onenote'                   => 'onenote',
            'office visio'                        => 'visio',
            'microsoft visio'                     => 'visio',
            'office access'                       => 'access',
            'microsoft access'                    => 'access',
            'lync'                                => 'lync',
            'office syncproc'                     => 'office syncproc',
            'office upload center'                => 'office upload center',
            'frontpage'                           => 'frontpage',
            'microsoft office mobile'             => 'office',
            'microsoft office'                    => 'office',
            'orangebot'                           => 'orangebot',
            'appengine-google'                    => 'google app engine',
            'locubot'                             => 'locubot',
            'acapbot'                             => 'acapbot',
            'deepcrawl'                           => 'deepcrawl',
            'googlebot-mobile'                    => 'googlebot-mobile',
            'google-http-java-client'             => 'google http client library for java',
            'googlebot-image'                     => 'google image search',
            'googlebot'                           => 'googlebot',
            'merchantcentricbot'                  => 'merchantcentricbot',
            'commerce browser center'             => 'commerce browser center',
            'iccrawler'                           => 'iccrawler',
            'centil-schweiz webbot'               => 'centil-schweiz webbot',
            'socialradarbot'                      => 'socialradar bot',
            'infegyatlas'                         => 'infegyatlas',
            'hubspot marketing grader'            => 'hubspot marketing grader',
            'diffbot'                             => 'diffbot',
            'netnewswire'                         => 'netnewswire',
            'whatsapp'                            => 'whatsapp',
            'dolphin http client'                 => 'dolphin smalltalk http client',
            'dolfin'                              => 'dolfin',
            'dolphin'                             => 'dolfin',
            'baiduspider-image'                   => 'baidu image search',
            'baiduspider'                         => 'baiduspider',
            'ibrowser/mini'                       => 'ibrowser mini',
            'ibrowser'                            => 'ibrowser',
            'onebrowser'                          => 'onebrowser',
            'windows phone search'                => 'windows phone search',
            'windows-update-agent'                => 'windows-update-agent',
            'classilla'                           => 'classilla',
            'nokia'                               => 'nokiabrowser',
            'twitterbot'                          => 'twitterbot',
            'quicktime'                           => 'quicktime',
            'mailchimp'                           => 'mailchimp.com',
            'mailbar'                             => 'mailbar',
            'adidxbot'                            => 'adidxbot',
            'msnbot'                              => 'bingbot',
            'blackberry'                          => 'blackberry',
            'wp-android'                          => 'wordpress app',
            'quora link preview'                  => 'quora link preview bot',
            'adbeat_bot'                          => 'adbeat bot',
            'adbeat.com'                          => 'adbeat bot',
            'nagios-plugins'                      => 'nagios',
            'check_http'                          => 'nagios',
            'bingbot'                             => 'bingbot',
            'smtbot'                              => 'smtbot',
            'slurp'                               => 'slurp',
            'soundcloud'                          => 'soundcloud app',
            'evernote clip resolver'              => 'evernote clip resolver',
            'konqueror'                           => 'konqueror',
            'windows phone ad client'             => 'windows phone ad client',
            'ddg-android-'                        => 'duckduck app',
            'ddg-ios-'                            => 'duckduck app',
            'xing-contenttabreceiver'             => 'xing contenttabreceiver',
            'easouspider'                         => 'easouspider',
            'unister-test'                        => 'unistertesting',
            'unistertesting'                      => 'unistertesting',
            'unister-https-test'                  => 'unistertesting',
            'tweetmemebot'                        => 'tweetmeme bot',
            'curb'                                => 'curb',
            'link_thumbnailer'                    => 'link_thumbnailer',
            'mechanize'                           => 'mechanize',
            'ruby'                                => 'generic ruby crawler',
            'gvfs'                                => 'gvfs',
            'playstation 3'                       => 'netfront',
            'sistrix'                             => 'sistrix crawler',
            'ezooms'                              => 'ezooms',
            'grapefx'                             => 'grapefx',
            'grapeshotcrawler'                    => 'grapeshotcrawler',
            'mail.ru'                             => 'mail.ru',
            'proximic'                            => 'proximic',
            'polaris'                             => 'polaris',
            'another web mining tool'             => 'another web mining tool',
            'awmt'                                => 'another web mining tool',
            'wbsearchbot'                         => 'wbsearchbot',
            'wbsrch'                              => 'wbsearchbot',
            'typo3-linkvalidator'                 => 'typo3 linkvalidator',
            'typo3'                               => 'typo3',
            'paperlibot'                          => 'paper.li bot',
            'spbot'                               => 'seoprofiler',
            'dotbot'                              => 'dotbot',
            'google-structureddatatestingtool'    => 'google structured-data testingtool',
            'google-structured-data-testing-tool' => 'google structured-data testingtool',
            'webmastercoffee'                     => 'webmastercoffee',
            'ahrefs'                              => 'ahrefsbot',
            'apercite'                            => 'apercite',
            'woobot'                              => 'woobot',
            'scoutjet'                            => 'scoutjet',
            'blekkobot'                           => 'blekkobot',
            'pagesinventory'                      => 'pagesinventory bot',
            'slackbot-linkexpanding'              => 'slackbot-link-expanding',
            'slackbot'                            => 'slackbot',
            'seokicks-robot'                      => 'seokicks robot',
            'alexabot'                            => 'alexabot',
            'exabot'                              => 'exabot',
            'domainscan'                          => 'domainscan server monitoring',
            'jobroboter'                          => 'jobroboter',
            'acoonbot'                            => 'acoonbot',
            'woriobot'                            => 'woriobot',
            'monobot'                             => 'monobot',
            'domainsigmacrawler'                  => 'domainsigmacrawler',
            'bnf.fr_bot'                          => 'bnf.fr bot',
            'crawlrobot'                          => 'crawlrobot',
            'addthis.com robot'                   => 'addthis.com robot',
            'yeti'                                => 'naverbot',
            'naver.com/robots'                    => 'naverbot',
            'robots'                              => 'testcrawler',
            'deusu'                               => 'werbefreie deutsche suchmaschine',
            'yodaobot'                            => 'yodaobot',
            'obot'                                => 'obot',
            'zumbot'                              => 'zumbot',
            'umbot'                               => 'umbot',
            'picmole'                             => 'picmole bot',
            'zollard'                             => 'zollard worm',
            'fhscan core'                         => 'fhscan core',
            'com.linkedin'                        => 'linkedinbot',
            'linkedinbot'                         => 'linkedinbot',
            'nbot'                                => 'nbot',
            'loadtimebot'                         => 'loadtimebot',
            'scrubby'                             => 'scrubby',
            'squzer'                              => 'squzer',
            'piplbot'                             => 'piplbot',
            'everyonesocialbot'                   => 'everyonesocialbot',
            'aolbot'                              => 'aolbot',
            'glbot'                               => 'glbot',
            'sslbot'                              => 'sslbot',
            'lbot'                                => 'lbot',
            'blexbot'                             => 'blexbot',
            'synapse'                             => 'apache synapse',
            'linkdexbot'                          => 'linkdex bot',
            'coccoc'                              => 'coccoc bot',
            'siteexplorer'                        => 'siteexplorer',
            'semrushbot'                          => 'semrushbot',
            'istellabot'                          => 'istellabot',
            'meanpathbot'                         => 'meanpathbot',
            'urlappendbot'                        => 'urlappendbot',
            'netseer crawler'                     => 'netseer crawler',
            'add catalog'                         => 'add catalog',
            'moreover'                            => 'moreover',
            'linkpadbot'                          => 'linkpadbot',
            'lipperhey seo service'               => 'lipperhey seo service',
            'blog search'                         => 'blog search',
            'qualidator.com bot'                  => 'qualidator.com bot',
            'fr-crawler'                          => 'fr-crawler',
            'ca-crawler'                          => 'ca-crawler',
            'website thumbnail generator'         => 'website thumbnail generator',
            'komodiabot'                          => 'komodiabot',
            'grouphigh'                           => 'grouphigh bot',
            'theoldreader'                        => 'the old reader',
            'google-site-verification'            => 'google-site-verification',
            'prlog'                               => 'prlog',
            'cms crawler'                         => 'cms crawler',
            'pmoz.info odp link checker'          => 'pmoz.info odp link checker',
            'twingly recon'                       => 'twingly recon',
            'embedly'                             => 'embedly',
            'alexa site audit'                    => 'alexa site audit',
            'mj12bot'                             => 'mj12bot',
            'httrack'                             => 'httrack',
            'unisterbot'                          => 'unisterbot',
            'careerbot'                           => 'careerbot',
            'wada.vn'                             => 'wada.vn search bot',
            'lynx'                                => 'lynx',
            'nintendo 3ds'                        => 'netfront nx',
            'netfront'                            => 'netfront',
            'playstation 4'                       => 'netfront',
            'xovibot'                             => 'xovibot',
            '007ac9 crawler'                      => '007ac9 crawler',
            '200pleasebot'                        => '200pleasebot',
            'abonti'                              => 'abonti websearch',
            'publiclibraryarchive'                => 'publiclibraryarchive bot',
            'pad-bot'                             => 'pad-bot',
            'softlistbot'                         => 'softlistbot',
            'sreleasebot'                         => 'sreleasebot',
            'vagabondo'                           => 'vagabondo',
            'special_archiver'                    => 'internet archive special archiver',
            'optimizer'                           => 'optimizer bot',
            'sophora linkchecker'                 => 'sophora linkchecker',
            'seodiver'                            => 'seodiver bot',
            'itsscan'                             => 'itsscan',
            'google desktop'                      => 'google desktop',
            'lotus-notes'                         => 'lotus notes',
            'askpeterbot'                         => 'askpeterbot',
            'discoverybot'                        => 'discovery bot',
            'yandexbot'                           => 'yandexbot',
            'yandeximages'                        => 'yandeximages',
        ];

        foreach ($checkBeforeMosbookmarks as $search => $key) {
            if ($s->contains($search, false)) {
                return $this->loader->load($key, $useragent);
            }
        }

        if ($s->containsAll(['mosbookmarks', 'link checker'], false)) {
            return $this->loader->load('mosbookmarks link checker', $useragent);
        }

        $checkBeforeOpenwaveBrowser = [
            'mosbookmarks'                 => 'mosbookmarks',
            'webmasteraid'                 => 'webmasteraid',
            'aboutusbot johnny5'           => 'aboutus bot johnny5',
            'aboutusbot'                   => 'aboutus bot',
            'semantic-visions.com crawler' => 'semantic-visions.com crawler',
            'waybackarchive.org'           => 'wayback archive bot',
            'wayback save page'            => 'wayback archive bot',
            'openvas'                      => 'open vulnerability assessment system',
            'mixrankbot'                   => 'mixrankbot',
            'mojeekbot'                    => 'mojeekbot',
            'memorybot'                    => 'memorybot',
            'domainappender'               => 'domainappender bot',
            'gidbot'                       => 'gidbot',
            'wap browser/maui'             => 'maui wap browser',
            'discovered'                   => 'discovered',
            'gosquared-thumbnailer'        => 'gosquared-thumbnailer',
            'pycurl'                       => 'pycurl',
            'libcurl-agent'                => 'libcurl',
            'taproot'                      => 'taproot bot',
            'guzzlehttp'                   => 'guzzle http client',
            'php-curl-class'               => 'php-curl-class',
            'curl'                         => 'curl',
            'red'                          => 'redbot',
            'dbot'                         => 'dbot',
            'pwbot'                        => 'pwbot',
            '+5bot'                        => 'plus5bot',
            'wasalive-bot'                 => 'wasalive bot',
            'openhosebot'                  => 'openhosebot',
            'urlfilterdb-crawler'          => 'urlfilterdb crawler',
            'metager2-verification-bot'    => 'metager2-verification-bot',
            'powermarks'                   => 'powermarks',
            'phantom.js bot'               => 'phantom.js bot',
            'netestate ne crawler'         => 'netestate ne crawler',
            'garlikcrawler'                => 'garlikcrawler',
            'metageneratorcrawler'         => 'metageneratorcrawler',
            'screenerbot'                  => 'screenerbot',
            'webtarantula.com crawler'     => 'webtarantula',
            'backlinkcrawler'              => 'backlinkcrawler',
            'linkscrawler'                 => 'linkscrawler',
            'ssearch_bot'                  => 'ssearch crawler',
            'ssearch crawler'              => 'ssearch crawler',
            'icc-crawler'                  => 'icc-crawler',
            'arachnida web crawler'        => 'arachnida web crawler',
            'finderlein research crawler'  => 'finderlein research crawler',
            'testcrawler'                  => 'testcrawler',
            'scopia crawler'               => 'scopia crawler',
            'metajobbot'                   => 'metajobbot',
            'lucidworks'                   => 'lucidworks bot',
            'pub-crawler'                  => 'pub-crawler',
            'archive.org.ua crawler'       => 'internet archive',
            'digincore bot'                => 'digincore bot',
            'steeler'                      => 'steeler',
            'electricmonk'                 => 'duedil crawler',
            'virtuoso'                     => 'virtuoso',
            'aboundex'                     => 'aboundexbot',
            'r6_commentreader'             => 'r6 commentreader',
            'r6_feedfetcher'               => 'r6 feedfetcher',
            'crazywebcrawler'              => 'crazywebcrawler',
            'fast-webcrawler'              => 'fast webcrawler',
            'crawler4j'                    => 'crawler4j',
            'ichiro/mobile'                => 'ichiro mobile bot',
            'ichiro'                       => 'ichiro bot',
            'tineye-bot'                   => 'tineye bot',
            'livelapbot'                   => 'livelap crawler',
            'safesearch microdata crawler' => 'safesearch microdata crawler',
            'fastbot crawler'              => 'fastbot crawler',
            'camcrawler'                   => 'camcrawler',
            'domaincrawler'                => 'domaincrawler',
            'pagefreezer'                  => 'pagefreezer',
            'showyoubot'                   => 'showyoubot',
            'y!j-asr'                      => 'yahoo! japan',
            'y!j-bsc'                      => 'yahoo! japan',
            'rogerbot'                     => 'rogerbot',
            'commoncrawler node'           => 'commoncrawler node',
            'adcrawler'                    => 'adcrawler',
            'contacts crawler'             => 'contacts crawler',
            'vorboss web crawler'          => 'vorboss web crawler',
            'crawler'                      => 'crawler',
            'jig browser web'              => 'jig browser web',
            't-h-u-n-d-e-r-s-t-o-n-e'      => 'texis webscript',
            'focuseekbot'                  => 'focuseekbot',
            'vbseo'                        => 'vbulletin seo bot',
            'kgbody'                       => 'kgbody',
            'jobdiggerspider'              => 'jobdiggerspider',
            'imrbot'                       => 'mignify bot',
            'kulturarw3'                   => 'kulturarw3',
            'nett.io bot'                  => 'nett.io bot',
            'semanticbot'                  => 'semanticbot',
            'tweetedtimes'                 => 'tweetedtimes bot',
            'vkshare'                      => 'vkshare',
            'yahoo ad monitoring'          => 'yahoo ad monitoring',
            'yioopbot'                     => 'yioopbot',
            'zitebot'                      => 'zitebot',
            'esribot'                      => 'esribot',
            'dillo'                        => 'dillo',
            'digg'                         => 'digg bot',
            'ajaxsnapbot'                  => 'ajaxsnapbot',
            'owler'                        => 'owler bot',
            'yahoo link preview'           => 'yahoo link preview',
            'linkfluence'                  => 'kraken',
            'qwantify'                     => 'qwantify',
            'setlinks bot'                 => 'setlinks.ru crawler',
            'megaindex.ru'                 => 'megaindex bot',
            'cliqzbot'                     => 'cliqzbot',
            'dawinci antiplag spider'      => 'dawinci antiplag spider',
            'advbot'                       => 'advbot',
            'duckduckgo-favicons-bot'      => 'duckduck favicons bot',
            'duckduckbot'                  => 'duckduck bot',
            'zyborg'                       => 'wisenut search engine crawler',
            'hypercrawl'                   => 'hypercrawl',
            'worldwebheritage'             => 'worldwebheritage.org bot',
            'begunadvertising'             => 'begun advertising bot',
            'trendwinhttp'                 => 'trendwinhttp',
            'winhttp'                      => 'winhttp',
            'skypeuripreview'              => 'skypeuripreview',
            'lipperhey-kaus-australis'     => 'lipperhey kaus australis',
            'jasmine'                      => 'jasmine',
            'yoozbot'                      => 'yoozbot',
            'online-webceo-bot'            => 'webceo bot',
            'niki-bot'                     => 'niki-bot',
            'contextad bot'                => 'contextad bot',
            'integrity'                    => 'integrity',
            'masscan'                      => 'masscan',
            'zmeu'                         => 'zmeu',
            'sogou web spider'             => 'sogou web spider',
            'openwave'                     => 'openwave mobile browser',
            'up.browser'                   => 'openwave mobile browser',
        ];

        foreach ($checkBeforeOpenwaveBrowser as $search => $key) {
            if ($s->contains($search, false)) {
                return $this->loader->load($key, $useragent);
            }
        }

        if ($s->contains('UP/', true)) {
            return $this->loader->load('openwave mobile browser', $useragent);
        }

        if (preg_match('/(obigointernetbrowser|obigo\-browser|obigo|telecabrowser|teleca)(\/|-)q(\d+)/i', $useragent)) {
            return $this->loader->load('obigo q', $useragent);
        }

        $checkBeforeGoHttpClient = [
            'teleca'                             => 'teleca-obigo',
            'obigo'                              => 'teleca-obigo',
            'au-mic'                             => 'teleca-obigo',
            'mic/'                               => 'teleca-obigo',
            'davclnt'                            => 'microsoft-webdav',
            'slingstone'                         => 'yahoo slingstone',
            'bot for jce'                        => 'bot for jce',
            'validator.nu/lv'                    => 'validator.nu/lv',
            'securepoint cf'                     => 'securepoint content filter',
            'rankflex'                           => 'rankflex',
            'kiodia spider'                      => 'kiodia-spider',
            'domnutch'                           => 'domnutch bot',
            'nutch'                              => 'nutch',
            'boardreader favicon fetcher'        => 'boardreader favicon fetcher',
            'checksite verification agent'       => 'checksite verification agent',
            'experibot'                          => 'experibot',
            'feedblitz'                          => 'feedblitz',
            'rss2html'                           => 'rss2html',
            'feedlyapp'                          => 'feedly app',
            'genderanalyzer'                     => 'genderanalyzer',
            'gooblog'                            => 'gooblog',
            'tumblr'                             => 'tumblr app',
            'w3c_i18n-checker'                   => 'w3c i18n checker',
            'w3c_unicorn'                        => 'w3c unicorn',
            'alltop'                             => 'alltop app',
            'internetseer'                       => 'internetseer.com',
            'admantx platform semantic analyzer' => 'admantx platform semantic analyzer',
            'universalfeedparser'                => 'universalfeedparser',
            'binlar'                             => 'larbin',
            'larbin'                             => 'larbin',
            'unityplayer'                        => 'unity web player',
            'wesee:search'                       => 'wesee:search',
            'wesee:ads'                          => 'wesee:ads',
            'a6-indexer'                         => 'a6-indexer',
            'nerdybot'                           => 'nerdybot',
            'peeplo screenshot bot'              => 'peeplo screenshot bot',
            'ccbot'                              => 'ccbot',
            'visionutils'                        => 'visionutils',
            'feedly'                             => 'feedly feed fetcher',
            'photon'                             => 'photon',
            'wdg_validator'                      => 'html validator',
            'yisouspider'                        => 'yisouspider',
            'hivabot'                            => 'hivabot',
            'comodo spider'                      => 'comodo spider',
            'openwebspider'                      => 'openwebspider',
            'psbot-image'                        => 'picsearch bot',
            'psbot-page'                         => 'picsearch bot',
            'bloglovin'                          => 'bloglovin bot',
            'viralvideochart'                    => 'viralvideochart bot',
            'metaheadersbot'                     => 'metaheadersbot',
            'zendhttpclient'                     => 'zend_http_client',
            'zend_http_client'                   => 'zend_http_client',
            'zend\http\client'                   => 'zend_http_client',
            'wget'                               => 'wget',
            'scrapy'                             => 'scrapy',
            'moozilla'                           => 'moozilla',
            'antbot'                             => 'antbot',
            'browsershots'                       => 'browsershots',
            'revolt'                             => 'bot revolt',
            'pdrlabs'                            => 'pdrlabs bot',
            'elinks'                             => 'elinks',
            'linkstats bot'                      => 'linkstats bot',
            'bcklinks'                           => 'bcklinks',
            'links'                              => 'links',
            'airmail'                            => 'airmail',
            'web.de mailcheck'                   => 'web.de mailcheck',
            'screaming frog seo spider'          => 'screaming frog seo spider',
            'androiddownloadmanager'             => 'android download manager',
        ];

        foreach ($checkBeforeGoHttpClient as $search => $key) {
            if ($s->contains($search, false)) {
                return $this->loader->load($key, $useragent);
            }
        }

        if (preg_match('/go ([\d\.]+) package http/i', $useragent)) {
            return $this->loader->load('go httpclient', $useragent);
        }

        if (preg_match('/NF[34]/i', $useragent)) {
            return $this->loader->load('netfront', $useragent);
        }

        $lastBrowsers = [
            'go-http-client'                                         => 'go httpclient',
            'proxy gear pro'                                         => 'proxy gear pro',
            'tiny tiny rss'                                          => 'tiny tiny rss',
            'readability'                                            => 'readability',
            'nsplayer'                                               => 'windows media player',
            'pingdom'                                                => 'pingdom',
            'gg peekbot'                                             => 'gg peekbot',
            'libreoffice'                                            => 'libreoffice',
            'openoffice'                                             => 'openoffice',
            'thumbnailagent'                                         => 'thumbnailagent',
            'ez publish link validator'                              => 'ez publish link validator',
            'thumbsniper'                                            => 'thumbsniper',
            'stq_bot'                                                => 'searchteq bot',
            'snk screenshot bot'                                     => 'save n keep screenshot bot',
            'okhttp'                                                 => 'okhttp',
            'synhttpclient'                                          => 'synhttpclient',
            'eventmachine httpclient'                                => 'eventmachine httpclient',
            'livedoor'                                               => 'livedoor',
            'jakarta commons-httpclient'                             => 'jakarta commons-httpclient',
            'httpclient'                                             => 'httpclient',
            'implisensebot'                                          => 'implisensebot',
            'buibui-bot'                                             => 'buibui-bot',
            'thumbshots-de-bot'                                      => 'thumbshots-de-bot',
            'python-requests'                                        => 'python-requests',
            'python-urllib'                                          => 'python-urllib',
            'bot.araturka.com'                                       => 'bot.araturka.com',
            'http_requester'                                         => 'http_requester',
            'whatweb'                                                => 'whatweb web scanner',
            'isc header collector handlers'                          => 'isc header collector handlers',
            'thumbor'                                                => 'thumbor',
            'forum poster'                                           => 'forum poster',
            'facebot'                                                => 'facebot',
            'netzcheckbot'                                           => 'netzcheckbot',
            'mib'                                                    => 'motorola internet browser',
            'facebookscraper'                                        => 'facebookscraper',
            'zookabot'                                               => 'zookabot',
            'metauri'                                                => 'metauri bot',
            'freewebmonitoring sitechecker'                          => 'freewebmonitoring sitechecker',
            'ipv4scan'                                               => 'ipv4scan',
            'domainsbot'                                             => 'domainsbot',
            'bubing'                                                 => 'bubing bot',
            'ramblermail'                                            => 'ramblermail bot',
            'iisbot'                                                 => 'iis site analysis web crawler',
            'jooblebot'                                              => 'jooblebot',
            'superfeedr bot'                                         => 'superfeedr bot',
            'feedburner'                                             => 'feedburner',
            'icarus6j'                                               => 'icarus6j',
            'wsr-agent'                                              => 'wsr-agent',
            'blogshares spiders'                                     => 'blogshares spiders',
            'quickiwiki'                                             => 'quickiwiki bot',
            'facebookexternalhit'                                    => 'facebookexternalhit',
            'ror sitemap generator'                                  => 'ror sitemap generator',
            'sitemap generator'                                      => 'sitemap generator',
            'embed php library'                                      => 'embed php library',
            'toquo.es'                                               => 'toquo.es-bot',
            'php'                                                    => 'php',
            'apple-pubsub'                                           => 'apple pubsub',
            'bigbozz'                                                => 'bigbozz - financial search',
            'eccp'                                                   => 'eccp',
            'gigablastopensource'                                    => 'gigablast search engine',
            'webindex'                                               => 'webindex',
            'prince'                                                 => 'prince',
            'adsense-snapshot-google'                                => 'adsense snapshot bot',
            'amazon cloudfront'                                      => 'amazon cloudfront',
            'bandscraper'                                            => 'bandscraper',
            'simplescraper'                                          => 'simplescraper',
            'bitlybot'                                               => 'bitlybot',
            'cars-app-browser'                                       => 'cars-app-browser',
            'coursera-mobile'                                        => 'coursera mobile app',
            'crowsnest'                                              => 'crowsnest mobile app',
            'dorado wap-browser'                                     => 'dorado wap browser',
            'goldfire server'                                        => 'goldfire server',
            'iball'                                                  => 'iball',
            'inagist url resolver'                                   => 'inagist url resolver',
            'jeode'                                                  => 'jeode',
            'kraken'                                                 => 'krakenjs',
            'mixbot'                                                 => 'mixbot',
            'busecurityproject'                                      => 'busecurityproject',
            'restify'                                                => 'restify',
            'vlc'                                                    => 'vlc media player',
            'webringchecker'                                         => 'webringchecker',
            'bot-pge.chlooe.com'                                     => 'chlooe bot',
            'seebot'                                                 => 'seebot',
            'ltx71'                                                  => 'ltx71 bot',
            'cookiereports'                                          => 'cookie reports bot',
            'elmer'                                                  => 'elmer',
            'iframely'                                               => 'iframely bot',
            'metainspector'                                          => 'metainspector',
            'microsoft-cryptoapi'                                    => 'microsoft cryptoapi',
            'microsoft url control'                                  => 'microsoft url control',
            'microsoft data access internet publishing provider dav' => 'microsoft data access internet publishing provider dav',
            'owasp_secret_browser'                                   => 'owasp_secret_browser',
            'smrf url expander'                                      => 'smrf url expander',
            'speedyspider'                                           => 'speedy spider',
            'speedy spider'                                          => 'speedy spider',
            'speedy_spider'                                          => 'speedy spider',
            'superarama.com - bot'                                   => 'superarama.com - bot',
            'wnmbot'                                                 => 'wnmbot',
            'website explorer'                                       => 'website explorer',
            'city-map screenshot service'                            => 'city-map screenshot service',
            'optivo(r) nethelper'                                    => 'optivo nethelper',
            'pr-cy.ru screenshot bot'                                => 'screenshot bot',
            'cyberduck'                                              => 'cyberduck',
            'accserver'                                              => 'accserver',
            'izsearch'                                               => 'izsearch bot',
            'netlyzer fastprobe'                                     => 'netlyzer fastprobe',
            'mnogosearch'                                            => 'mnogosearch',
            'uipbot'                                                 => 'uipbot',
            'mbot'                                                   => 'mbot',
            'ms web services client protocol'                        => '.net framework clr',
            'feedfetcher-google'                                     => 'google feedfetcher',
            'test certificate info'                                  => 'test certificate info',
            'riddler'                                                => 'riddler',
            'sophosupdatemanager'                                    => 'sophosupdatemanager',
            'debian apt-http'                                        => 'apt http transport',
            'ubuntu apt-http'                                        => 'apt http transport',
            'urlgrabber'                                             => 'url grabber',
            'w3c-checklink'                                          => 'w3c-checklink',
            'libwww-perl'                                            => 'libwww',
            'openbsd ftp'                                            => 'openbsd ftp',
            'sophosagent'                                            => 'sophosagent',
            'jupdate'                                                => 'jupdate',
            'roku/dvp'                                               => 'roku dvp',
            'safeassign'                                             => 'safeassign',
            'exaleadcloudview'                                       => 'exalead cloudview',
            'typhoeus'                                               => 'typhoeus',
            'camo asset proxy'                                       => 'camo asset proxy',
            'yahoocachesystem'                                       => 'yahoocachesystem',
            'wmtips.com'                                             => 'webmaster tips bot',
            'brokenlinkcheck.com'                                    => 'brokenlinkcheck',
            'linkcheck'                                              => 'linkcheck',
            'gwpimages'                                              => 'gwpimages',
            'notetextview'                                           => 'notetextview',
            'yourls'                                                 => 'yourls',
            'thunderbird'                                            => 'thunderbird',
            'ning'                                                   => 'ning',
            'sprinklr'                                               => 'sprinklr',
            'urlchecker'                                             => 'urlchecker',
            'newsme'                                                 => 'newsme',
            'traackr'                                                => 'traackr',
            'nineconnections'                                        => 'nineconnections',
            'xenu link sleuth'                                       => 'xenus link sleuth',
            'superagent'                                             => 'superagent',
            'goose'                                                  => 'goose-extractor',
            'ahc'                                                    => 'asynchronous http client',
            'newspaper'                                              => 'newspaper',
            'hatena::bookmark'                                       => 'hatena::bookmark',
            'easybib autocite'                                       => 'easybib autocite',
            'shortlinktranslate'                                     => 'shortlinktranslate',
            'marketing grader'                                       => 'marketing grader',
            'grammarly'                                              => 'grammarly',
            'dispatch'                                               => 'dispatch',
            'raven link checker'                                     => 'raven link checker',
            'http-kit'                                               => 'http kit',
            'sffeedreader'                                           => 'symfony rss reader',
            'twikle'                                                 => 'twikle bot',
            'node-fetch'                                             => 'node-fetch',
            'faraday'                                                => 'faraday',
            'gettor'                                                 => 'gettor',
            'seostats'                                               => 'seostats',
            'znajdzfoto/image'                                       => 'znajdzfoto/imagebot',
            'infox-wisg'                                             => 'infox-wisg',
            'wscheck.com'                                            => 'wscheck bot',
            'tweetminster'                                           => 'tweetminster bot',
            'astute srm'                                             => 'astute social',
            'longurl api'                                            => 'longurl bot',
            'trove'                                                  => 'trove bot',
            'melvil favicon'                                         => 'melvil favicon bot',
            'melvil'                                                 => 'melvil bot',
            'pearltrees'                                             => 'pearltrees bot',
            'svven-summarizer'                                       => 'svven summarizer bot',
            'athena site analyzer'                                   => 'athena site analyzer',
            'exploratodo'                                            => 'exploratodo bot',
            'webcorp'                                                => 'webcorp',
            'auditmypc webmaster tool'                               => 'auditmypc webmaster tool',
            'xmlsitemapgenerator'                                    => 'xmlsitemapgenerator',
            'stratagems kumo'                                        => 'stratagems kumo',
            'spip'                                                   => 'spip',
            'friendica'                                              => 'friendica',
            'magpierss'                                              => 'magpierss',
            'short url checker'                                      => 'short url checker',
            'webnumbrfetcher'                                        => 'webnumbr fetcher',
            'wap browser'                                            => 'wap browser',
            'spice qt-75'                                            => 'wap browser',
            'kkt20/midp'                                             => 'wap browser',
            'yacybot'                                                => 'yacybot',
            'java'                                                   => 'java',
            'blitzbot'                                               => 'blitzbot',
            'heritrix'                                               => 'heritrix',
            'archive-de.com'                                         => 'archive-de.com',
            'socialcast'                                             => 'socialcast bot',
            'cloudinary'                                             => 'cloudinary',
            'evc-batch'                                              => 'evc-batch',
            'researchbot'                                            => 'research-bot',
            'intelligentsearchassistant'                             => 'intelligent-search-assistant',
            'doccheckbot'                                            => 'doccheckbot',
            'rankactivelinkbot'                                      => 'rankactivelinkbot',
            'lippershey'                                             => 'lippershey',
            'sundance'                                               => 'sundance',
            'ucrawlr'                                                => 'ucrawlr',
            'goog'                                                   => 'googlebot',
            'fetchstream'                                            => 'fetch-stream',
            'autoit'                                                 => 'autoit',
            'atvoice'                                                => 'atvoice',
            'rankingbot2'                                            => 'rankingbot2',
            'pcore-http'                                             => 'pcore-http',
            'gloomarbot'                                             => 'gloomarbot',
            'booglebot'                                              => 'booglebot',
            'orbiter'                                                => 'orbiter',
            'generic site loader'                                    => 'generic site loader',
            'web downloader'                                         => 'web downloader',
            'wpscan'                                                 => 'wpscan',
            'wsp'                                                    => 'wsp',
            'origin'                                                 => 'origin',
            'itunes'                                                 => 'itunes',
            'mozilla'                                                => 'mozilla',
        ];

        foreach ($lastBrowsers as $search => $key) {
            if ($s->contains($search, false)) {
                return $this->loader->load($key, $useragent);
            }
        }

        return $this->loader->load('unknown', $useragent);
    }
}
