<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: add.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<h2>Neues Event</h2>
<div class="list">
    <div class="head">
        <span>neues Event</span>
    </div>
    <div class="content">
    <?php echo $this->form; ?>
    </div>
    <div class="bottom"><span></span></div>
</div>