<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: index.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<h2>
    Events
</h2>
<div class="list">
    <div class="content">
        <div class="filter">
            <div class="buttons">
                <a href="<?php echo $this->url(array(
                    'module' => 'kredit-admin',
                    'controller' => 'event',
                    'action'    => 'add'
                )); ?>">Neues Event eintragen</a>
            </div>
        </div>
        <div class="table">
        <table id="sortableTable" class="Data sortableTable" summary="Übersicht Ereignisse">
            <thead>
            <tr>
                <th class="first" scope="col"></th>
                <th scope="col">Zeit</th>
                <th scope="col">Typ</th>
                <th scope="col">Beschreibung</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($this->events as $row) : ?>

            <tr class="<?php echo $this->cycle(array('cycle1', 'cycle2'))->next(); ?>">
                <td class="first">

                </td>
                <td><?php echo $row['InsertAt']; ?></td>
                <td>
                    <img src="<?php echo $this->basedUrl('/images/kredit-admin/'.$row['Icon']); ?>" alt="" />
                    <span class="textSmall"><?php echo $row['Name']; ?></span>
                </td>
                <td class="literal"><?php echo nl2br($row['Desc']); ?></td>
            </tr>

            <?php endforeach; ?>
            </tbody>
        </table>
        </div>

    </div>
    <div class="bottom"><span>&nbsp;</span></div>

</div>
<script type="text/javascript">
/* <![CDATA[ */
   addTableSorter('sortableTable');
/* ]]> */
</script>