<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<xml dataset="<?php echo $this->reportNr; ?>">
    <anrede><?php echo $this->rData['anrede']; ?></anrede>
    <titel><?php echo $this->rData['titel']; ?></titel>
    <vorname><?php echo $this->rData['vorname']; ?></vorname>
    <nachname><?php echo $this->rData['nachname']; ?></nachname>
    <land><?php echo $this->rData['land']; ?></land>
    <strasse><?php echo $this->rData['strasse']; ?></strasse>
    <hausnr><?php echo $this->rData['hausnr']; ?></hausnr>
    <plz><?php echo $this->rData['plz']; ?></plz>
    <ort><?php echo $this->rData['ort']; ?></ort>
    <email><?php echo $this->rData['email']; ?></email>
    <vorwahl><?php echo $this->rData['vorwahl']; ?></vorwahl>
    <telefon><?php echo $this->rData['telefon']; ?></telefon>
    <vorwahlmobil><?php echo $this->rData['vorwahlmobil']; ?></vorwahlmobil>
    <mobilfunk><?php echo $this->rData['mobilfunk']; ?></mobilfunk>
    <gebdatumtag><?php echo $this->rData['gebdatumtag']; ?></gebdatumtag>
    <gebdatummonat><?php echo $this->rData['gebdatummonat']; ?></gebdatummonat>
    <gebdatumjahr><?php echo $this->rData['gebdatumjahr']; ?></gebdatumjahr>
    <berufsgruppe><?php echo $this->rData['berufsgruppe']; ?></berufsgruppe>
    <probezeit><?php echo $this->rData['probezeit']; ?></probezeit>
    <dreimonate><?php echo $this->rData['dreimonate']; ?></dreimonate>
    <schufaeinv><?php echo $this->rData['schufaeinv']; ?></schufaeinv>
    <dateneinv><?php echo $this->rData['dateneinv']; ?></dateneinv>
    <agbeinv><?php echo $this->rData['agbeinv']; ?></agbeinv>
    <paid><?php echo $this->rData['paid']; ?></paid>
    <kreditbetrag><?php echo $this->rData['kreditbetrag']; ?></kreditbetrag>
    <laufzeit><?php echo $this->rData['laufzeit']; ?></laufzeit>
    <vzweck><?php echo $this->rData['zweck']; ?></vzweck>
    <test><?php echo $this->rData['test']; ?></test>
    <kreditinstitut><?php echo $this->rData['kreditinstitut']; ?></kreditinstitut>
    <sparte><?php echo $this->rData['sparte']; ?></sparte>
    <uuid><?php echo $this->uuid; ?></uuid>
</xml>