<?php
/**
 * Layout für den Index-Controller
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: index.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<h2>
    Gesellschaften
</h2>
<div class="list">
    <div class="content">
        <div class="filter">
            <div class="buttons">
                <a href="<?php echo $this->basedUrl(
    array(
        'module' => 'kredit-admin',
        'controller' => 'institute',
        'action' => 'edit',
        'institut' => 0
    )
) ?>/">neues Institut anlegen</a>
            </div>
        </div>
        <div class="table">
            <table id="sortableTable" class="Data" summary="Übersicht über Institute">
                <colgroup>
                    <col style="width:20px;" />
                    <col span="7" />
                </colgroup>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>Codename</th>
                        <th>Name des Institutes</th>
                        <th>Sortierung</th>
                        <th>Farbe in Statistik</th>
                        <th>aktiv</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
<?php
if (isset($this->paginator) && is_object($this->paginator)) :
    foreach ($this->paginator->getItemsByPage($this->paginator->getCurrentPageNumber()) as $institut) :
?>
                    <tr class="<?php echo $this->cycle(array('cycle1', 'cycle2'))->next(); ?>" title="das Institut '<?php echo $institut->ki_name; ?>' ist <?php if (!$institut->ki_active) {
    echo 'nicht ';
} ?>aktiviert">
                        <td class="first edit" title="Institut bearbeiten">
                            <a href="<?php echo $this->basedUrl(
    array(
        'module' => 'kredit-admin',
        'controller' => 'institute',
        'action'   => 'edit',
        'institut' => $institut->ki_id
    )
); ?>">&nbsp;</a>
                        </td>
                        <td><?php echo $institut->ki_id; ?></td>
                        <td><?php echo $institut->ki_name; ?></td>
                        <td><?php echo $institut->ki_title; ?></td>
                        <td><?php echo $institut->ki_ordering; ?></td>
                        <td style="color:#<?php echo $institut->color; ?>;"><?php echo $institut->color; ?></td>
<?php
if (!$institut->ki_active) {
    $class = 'nok';
    $title = "das Institut '$institut->ki_name' aktivieren";
} else {
    $class = 'ok';
    $title = "das Institut '$institut->ki_name' deaktivieren";
}
?>
                        <td class="<?php echo $class; ?>" title="<?php echo $title; ?>">
                            <a href="<?php echo $this->basedUrl(
    array(
        'module' => 'kredit-admin',
        'controller' => 'institute',
        'action'   => 'activate',
        'institut' => $institut->ki_id,
        'aktiv'    => $institut->ki_active
    )
) ?>/">&nbsp;</a>
                        </td>
                        <td>
                            <div class="info" title="Produkte anzeigen">
                                <a href="<?php echo $this->basedUrl(
    array(
        'module' => 'kredit-admin',
        'controller' => 'products',
        'action'   => 'index',
        'institut' => $institut->ki_id
    )
) ?>/">Produkte anzeigen</a>
                            </div>
                            <div class="small">TODO: l&ouml;schen ??, Details anzeigen</div>
                        </td>
                    </tr>
<?php
    endforeach;
endif;
?>
                </tbody>
            </table>
        </div>
        <div class="filter">
            <?php if (null !== $this->queryPaginator) echo $this->paginationControl($this->queryPaginator, 'Sliding', 'pagination.phtml', array('module' => 'kredit-admin','controller' => 'institute','action'  => 'index')); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="bottom"><span>&nbsp;</span></div>
</div>