<?php

namespace BrowserDetectorTest\Detector\Device\Mobile\Samsung;

use BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:40:26.
 */
class SamsungSghT899mTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SamsungSghT899m
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SamsungSghT899m('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::detectOs
     * @todo   Implement testDetectOs().
     */
    public function testDetectOs()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getDeviceName
     * @todo   Implement testGetDeviceName().
     */
    public function testGetDeviceName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getDualOrientation
     * @todo   Implement testGetDualOrientation().
     */
    public function testGetDualOrientation()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getHasQwertyKeyboard
     * @todo   Implement testGetHasQwertyKeyboard().
     */
    public function testGetHasQwertyKeyboard()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getMarketingName
     * @todo   Implement testGetMarketingName().
     */
    public function testGetMarketingName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getNfcSupport
     * @todo   Implement testGetNfcSupport().
     */
    public function testGetNfcSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getPointingMethod
     * @todo   Implement testGetPointingMethod().
     */
    public function testGetPointingMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getResolutionHeight
     * @todo   Implement testGetResolutionHeight().
     */
    public function testGetResolutionHeight()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getResolutionWidth
     * @todo   Implement testGetResolutionWidth().
     */
    public function testGetResolutionWidth()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getSmsSupport
     * @todo   Implement testGetSmsSupport().
     */
    public function testGetSmsSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Samsung\SamsungSghT899m::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
