<?php
/**
 * Layout fuer den Vergleich
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Layout
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<td class="center"
    onclick="<?php echo $this->goto; ?>"
    onmousedown="logThisClick('<?php echo $this->sparte; ?>_<?php echo $this->kreditinstitut; ?>');"
    title="Jetzt ein <?php echo ucfirst($this->sparte); ?> Konto bei der <?php echo $this->kreditInstitutTitle; ?> er&ouml;ffnen!">
    <?php if (isset($this->kontofuehrung) && $this->kontofuehrung > 0) {echo $this->kontofuehrung; ?> &euro;<?php } else { ?>-<?php } ?>
</td>