<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Controller
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @license   http://www.unister.de  Unister License
 * @version   SVN: $Id$
 * @link      todo
 */
?>
<p>
    <span class="small"><span class="red">*</span> Bonit&auml;tsstufe 1(sehr gute Bonit&auml;t). Die Angaben sind teilweise bonit&auml;tsabh&auml;ngig und k&ouml;nnen aufgrund der bankinternen Bewertungs- und Berechnungsmethoden minimal von den hier errechneten Werten abweichen. Die Angaben sind ohne Gew&auml;hr.</span>
</p>
<p>
    <span class="smallStd"><strong class="darkgreen"><?php echo $this->domain; ?> Tipp: </strong>Sollten Sie f&uuml;r die Kredit-Anfrage von Ihrem ausgew&auml;hlten Anbieter keine Zusage erhalten,
                k&ouml;nnen Sie durchaus bei einem unserer anderen Anbieter mehr Erfolg haben.
                Probieren Sie es doch einfach unverbindlich aus!</span>
</p>
