<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Controller
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @license   http://www.unister.de  Unister License
 * @version   SVN: $Id$
 * @link      todo
 */

if ($this->mode != 'xml') {
?>
<div id="timeline">
    <ul>
<?php
$i = 0;
foreach($this->alleLaufzeiten as $lz => $lzName) {
    if ($this->mode == 'html') {
        $requestNav = '&amp;vzweck='.$this->zweck.'&amp;kreditbetrag='.$this->kreditbetrag.'&amp;ccstart=1';
?>
        <li<?php if ($this->loanPeriod == $lz) { ?> class="active"<?php } else { ?>><a rel="nofollow" href="<?php echo $this->url; ?>?loanPeriod=<?php echo $lz . $requestNav; ?>"<?php } ?>><span style="display:block;" class="separator"><?php echo $lzName; ?></span><?php if($this->loanPeriod != $lz): ?></a><?php endif; ?></li>
<?php
    } elseif ($this->mode == 'js') {
        $target  = 'var u=\''.$this->zweck.'\';var t=\''.$lz.'\';var a=\''.$this->kreditbetrag.'\';calc(u, t, a);reform(u, t, a);return false;';
?>
        <li<?php if ($this->loanPeriod == $lz) { ?> class="active"<?php } else { if ($i == 0) { ?> id="hover"<?php } ?>><a<?php if ($i == 0) { ?> class="first"<?php } ?> rel="nofollow" href="javascript:void(0);" onclick="<?php echo $target; ?>"<?php } ?>><span class="separator"><?php echo $lzName; ?></span><?php if($this->loanPeriod != $lz): ?></a><?php endif; ?></li>
<?php
    }
    $i++;
} ?>
    </ul>
</div>
<?php
}
