<?php

/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2025, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace BrowserDetectorTest;

use BrowserDetector\Collection\Headers;
use BrowserDetector\Detector;
use BrowserDetector\DetectorFactory;
use PHPUnit\Event\NoPreviousThrowableException;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Constraint\IsType;
use PHPUnit\Framework\Exception;
use PHPUnit\Framework\ExpectationFailedException;
use PHPUnit\Framework\NativeType;
use PHPUnit\Framework\TestCase;
use Psr\Log\LoggerInterface;
use Psr\SimpleCache\CacheInterface;
use Psr\SimpleCache\InvalidArgumentException;
use RuntimeException;
use UnexpectedValueException;

/** @phpcs:disable SlevomatCodingStandard.Classes.ClassLength.ClassTooLong */
#[CoversClass(Detector::class)]
#[CoversClass(Headers::class)]
final class DetectorIntegrationTest extends TestCase
{
    /**
     * @param array<non-empty-string, non-empty-string> $headers
     * @param array<string, mixed>                      $expected
     *
     * @throws Exception
     * @throws InvalidArgumentException
     * @throws UnexpectedValueException
     * @throws ExpectationFailedException
     * @throws RuntimeException
     * @throws \Laminas\Hydrator\Exception\InvalidArgumentException
     * @throws NoPreviousThrowableException
     * @throws \PHPUnit\Framework\MockObject\Exception
     */
    #[DataProvider('providerUa')]
    public function testData(array $headers, array $expected): void
    {
        $logger = $this->createMock(LoggerInterface::class);
        $logger
            ->expects(self::never())
            ->method('info');
        $logger
            ->expects(self::never())
            ->method('notice');
        $logger
            ->expects(self::never())
            ->method('warning');
        $logger
            ->expects(self::never())
            ->method('error');
        $logger
            ->expects(self::never())
            ->method('critical');
        $logger
            ->expects(self::never())
            ->method('alert');
        $logger
            ->expects(self::never())
            ->method('emergency');

        $cache = $this->createMock(CacheInterface::class);
        $cache
            ->expects(self::never())
            ->method('get');
        $cache
            ->expects(self::once())
            ->method('set');
        $cache
            ->expects(self::never())
            ->method('delete');
        $cache
            ->expects(self::never())
            ->method('clear');
        $cache
            ->expects(self::never())
            ->method('getMultiple');
        $cache
            ->expects(self::never())
            ->method('setMultiple');
        $cache
            ->expects(self::never())
            ->method('deleteMultiple');
        $cache
            ->expects(self::once())
            ->method('has')
            ->with(new IsType(NativeType::String))
            ->willReturn(false);

        $factory  = new DetectorFactory($cache, $logger);
        $detector = $factory();

        $result = $detector->getBrowser($headers);

        self::assertSame($expected, $result);
    }

    /**
     * @return array<int, array<int, mixed>>
     *
     * @throws void
     *
     * @phpcs:disable SlevomatCodingStandard.Functions.FunctionLength.FunctionLength
     */
    public static function providerUa(): array
    {
        return [
            [
                [
                    'sec-ch-ua' => '"Chromium";v="92", " Not A;Brand";v="99", "HuaweiBrowser";v="92"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-full-version' => '"92.0.4515.105"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"RVL-AL09"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"9; HarmonyOS"',
                    'sec-fetch-dest' => 'document',
                    'sec-fetch-mode' => 'navigate',
                    'sec-fetch-site' => 'cross-site',
                    'sec-fetch-user' => '?1',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 9; HarmonyOS; RVL-AL09; HMSCore 6.7.0.301; GMSCore 22.30.17) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.3.303 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"RVL-AL09"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"9; HarmonyOS"',
                        'sec-ch-ua' => '"Chromium";v="92", " Not A;Brand";v="99", "HuaweiBrowser";v="92"',
                        'sec-ch-ua-full-version' => '"92.0.4515.105"',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-mobile' => '?1',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 9; HarmonyOS; RVL-AL09; HMSCore 6.7.0.301; GMSCore 22.30.17) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.3.303 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'RVL-AL09',
                        'marketingName' => 'Honor Note 10',
                        'manufacturer' => 'Huawei',
                        'brand' => 'Huawei',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2220,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.95,
                        ],
                        'type' => 'phablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'HarmonyOS',
                        'marketingName' => 'HarmonyOS',
                        'version' => null,
                        'manufacturer' => 'Huawei',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Huawei Browser Mobile',
                        'modus' => null,
                        'version' => '92.0.0',
                        'manufacturer' => 'Huawei',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '92.0.4515.105',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; Android 12; DBY-W09 Build/HUAWEIDBY-W09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.41 BDOS/1.0 (HarmonyOS 3.0.0) SP-engine/2.79.0 baiduboxapp/13.41.5.10 (Baidu; P1 12) NABar/1.0'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; Android 12; DBY-W09 Build/HUAWEIDBY-W09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.41 BDOS/1.0 (HarmonyOS 3.0.0) SP-engine/2.79.0 baiduboxapp/13.41.5.10 (Baidu; P1 12) NABar/1.0'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'DBY-W09',
                        'marketingName' => 'MatePad 11 Wi-Fi (2021)',
                        'manufacturer' => 'Huawei',
                        'brand' => 'Huawei',
                        'dualOrientation' => true,
                        'simCount' => 0,
                        'display' => [
                            'width' => 2560,
                            'height' => 1600,
                            'touch' => true,
                            'size' => 10.95,
                        ],
                        'type' => 'tablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'HarmonyOS',
                        'marketingName' => 'HarmonyOS',
                        'version' => '3.0.0',
                        'manufacturer' => 'Huawei',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Baidu Box App',
                        'modus' => null,
                        'version' => '13.41.5.10',
                        'manufacturer' => 'Baidu',
                        'type' => 'mobile-application',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'T7',
                        'version' => '13.41.0',
                        'manufacturer' => 'Baidu',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; U; Android 6.0.1; xx; Le X820 Build/MOB31T) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 Quark/1.6.9.911 Mobile Safari/537.36'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; U; Android 6.0.1; xx; Le X820 Build/MOB31T) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 Quark/1.6.9.911 Mobile Safari/537.36'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Le X820',
                        'marketingName' => 'Le Max 2',
                        'manufacturer' => 'leeco',
                        'brand' => 'leeco',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2560,
                            'height' => 1440,
                            'touch' => true,
                            'size' => 5.7,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '6.0.1',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Quark',
                        'modus' => null,
                        'version' => '1.6.9.911',
                        'manufacturer' => 'Quark',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '40.0.2214.89',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"14.0.0"',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"14.0.0"',
                        'sec-ch-ua-mobile' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '11.0.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"10.0.0"',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"10.0.0"',
                        'sec-ch-ua-mobile' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '10.0.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"0.1"',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"0.1"',
                        'sec-ch-ua-mobile' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '7.0.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"0.2"',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"0.2"',
                        'sec-ch-ua-mobile' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '8.0.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"0.3"',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"0.3"',
                        'sec-ch-ua-mobile' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.3',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '8.1.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '97.0.4692.99',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'UCWEB/2.0 (iOS; U; iPd OS 7_0_4; zh-CN; iPd5,1) U2/1.0.0 UCBrowser/9.0.1.284 U2/1.0.0 Mobile'],
                [
                    'headers' => ['user-agent' => 'UCWEB/2.0 (iOS; U; iPd OS 7_0_4; zh-CN; iPd5,1) U2/1.0.0 UCBrowser/9.0.1.284 U2/1.0.0 Mobile'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'iPad 5,1',
                        'marketingName' => 'iPad Mini 4 Wi-Fi',
                        'manufacturer' => 'Apple',
                        'brand' => 'Apple',
                        'dualOrientation' => true,
                        'simCount' => 0,
                        'display' => [
                            'width' => 2048,
                            'height' => 1536,
                            'touch' => true,
                            'size' => 7.9,
                        ],
                        'type' => 'tablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'iOS',
                        'marketingName' => 'iOS',
                        'version' => '7.0.4',
                        'manufacturer' => 'Apple',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'UC Browser',
                        'modus' => null,
                        'version' => '9.0.1.284',
                        'manufacturer' => 'UCWeb',
                        'type' => 'transcoder',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Macintosh',
                        'marketingName' => 'Macintosh',
                        'manufacturer' => 'Apple',
                        'brand' => 'Apple',
                        'dualOrientation' => false,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Mac OS X',
                        'marketingName' => 'Mac OS X',
                        'version' => '10.9.3',
                        'manufacturer' => 'Apple',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Safari',
                        'modus' => null,
                        'version' => '7.0.3',
                        'manufacturer' => 'Apple',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => '537.75.14',
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['x-crawled-by' => 'RecordedFuture-ASI-Crawl'],
                [
                    'headers' => ['x-crawled-by' => 'RecordedFuture-ASI-Crawl'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => null,
                        'marketingName' => null,
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => null,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => null,
                            'size' => null,
                        ],
                        'type' => 'unknown',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => null,
                        'marketingName' => null,
                        'version' => null,
                        'manufacturer' => 'unknown',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => null,
                        'modus' => null,
                        'version' => null,
                        'manufacturer' => 'unknown',
                        'type' => 'unknown',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => null,
                        'version' => null,
                        'manufacturer' => 'unknown',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Dalvik/2.1.0 (Linux; U; Android 8.1.0; iLA_Silk Build/iLA_Silk)'],
                [
                    'headers' => ['user-agent' => 'Dalvik/2.1.0 (Linux; U; Android 8.1.0; iLA_Silk Build/iLA_Silk)'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Silk',
                        'marketingName' => 'Silk',
                        'manufacturer' => 'ila',
                        'brand' => 'ila',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => true,
                            'size' => 5.7,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '8.1.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Browser',
                        'modus' => null,
                        'version' => '2.1.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; U; Android 4.2.1; zh-cn; Infinix X801 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30;'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; U; Android 4.2.1; zh-cn; Infinix X801 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30;'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'X801',
                        'marketingName' => 'Joypad 8S',
                        'manufacturer' => 'Infinix',
                        'brand' => 'Infinix',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 1024,
                            'height' => 768,
                            'touch' => true,
                            'size' => 8.0,
                        ],
                        'type' => 'fone-pad',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '4.2.1',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Webkit',
                        'modus' => null,
                        'version' => '4.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => '534.30.0',
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X; zh-CN) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/19B81 UCBrowser/13.7.2.1636 Mobile AliApp(TUnionSDK/0.1.20.4) dv(iPh14,5);pr(UCBrowser/13.7.2.1636);ov(15_1_1);ss(390x844);bt(UC);pm(0);bv(0);nm(0);im(0);nt(1);'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X; zh-CN) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/19B81 UCBrowser/13.7.2.1636 Mobile AliApp(TUnionSDK/0.1.20.4) dv(iPh14,5);pr(UCBrowser/13.7.2.1636);ov(15_1_1);ss(390x844);bt(UC);pm(0);bv(0);nm(0);im(0);nt(1);'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'iPhone 14,5',
                        'marketingName' => 'iPhone 13',
                        'manufacturer' => 'Apple',
                        'brand' => 'Apple',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 2532,
                            'height' => 1170,
                            'touch' => true,
                            'size' => 6.1,
                        ],
                        'type' => 'phablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'iOS',
                        'marketingName' => 'iOS',
                        'version' => '15.1.1',
                        'manufacturer' => 'Apple',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'UC Browser',
                        'modus' => null,
                        'version' => '13.7.2.1636',
                        'manufacturer' => 'UCWeb',
                        'type' => 'transcoder',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => '605.1.15',
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; Android 10; arm_64; M2002J9G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 YaBrowser/20.7.5.84.00 SA/3 Mobile Safari/537.36'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; Android 10; arm_64; M2002J9G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 YaBrowser/20.7.5.84.00 SA/3 Mobile Safari/537.36'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'M2002J9G',
                        'marketingName' => 'Mi 10 Lite 5G',
                        'manufacturer' => 'Xiaomi',
                        'brand' => 'Xiaomi',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.6,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '10.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Yandex Browser',
                        'modus' => null,
                        'version' => '20.7.5.84.00',
                        'manufacturer' => 'Yandex',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '83.0.4103.116',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; Android 10; arm_64; M2002J9G Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 YaBrowser/20.7.5.84.00 SA/3 Mobile Safari/537.36'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; Android 10; arm_64; M2002J9G Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 YaBrowser/20.7.5.84.00 SA/3 Mobile Safari/537.36'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'M2002J9G',
                        'marketingName' => 'Mi 10 Lite 5G',
                        'manufacturer' => 'Xiaomi',
                        'brand' => 'Xiaomi',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.6,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '10.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Yandex Browser',
                        'modus' => null,
                        'version' => '20.7.5.84.00',
                        'manufacturer' => 'Yandex',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '83.0.4103.116',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Linux; arm_64; Android 14; Optima 8430E 4G DA1C8P01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.2144 YaApp_Android/25.20.1/apad YaSearchBrowser/25.20.1/apad BroPP/1.0 SA/3 Mobile Safari/537.36'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Linux; arm_64; Android 14; Optima 8430E 4G DA1C8P01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.6834.2144 YaApp_Android/25.20.1/apad YaSearchBrowser/25.20.1/apad BroPP/1.0 SA/3 Mobile Safari/537.36'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'DA1C8P01',
                        'marketingName' => 'Optima 8430E 4G',
                        'manufacturer' => 'Digma',
                        'brand' => 'Digma',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 1280,
                            'height' => 800,
                            'touch' => true,
                            'size' => 8.0,
                        ],
                        'type' => 'fone-pad',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '14.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Yandex Search Browser',
                        'modus' => null,
                        'version' => '25.20.1',
                        'manufacturer' => 'Yandex',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '132.0.6834.2144',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Android 17 - samsung meliuslte'],
                [
                    'headers' => ['user-agent' => 'Android 17 - samsung meliuslte'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'general Samsung device',
                        'marketingName' => 'general Samsung device',
                        'manufacturer' => 'Samsung',
                        'brand' => 'Samsung',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'mobile-device',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => null,
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Webkit',
                        'modus' => null,
                        'version' => null,
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) WorxWeb/18.11.5(build 18.11.5.4) Mobile/16B92 Safari/605.1<tabid-F3D1C4D0-C475-4EFA-AFC9-9E4FA70B94AD>'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) WorxWeb/18.11.5(build 18.11.5.4) Mobile/16B92 Safari/605.1<tabid-F3D1C4D0-C475-4EFA-AFC9-9E4FA70B94AD>'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'iPhone',
                        'marketingName' => 'iPhone',
                        'manufacturer' => 'Apple',
                        'brand' => 'Apple',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 480,
                            'height' => 320,
                            'touch' => true,
                            'size' => 3.5,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'iOS',
                        'marketingName' => 'iOS',
                        'version' => '12.1.0',
                        'manufacturer' => 'Apple',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Safari',
                        'modus' => null,
                        'version' => '5.0.0',
                        'manufacturer' => 'Apple',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => '605.1.15',
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                [
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 12; Redmi 7 Build/SQ3A.220705.004) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36',
                    'x-requested-with' => 'org.lineageos.jelly',
                ],
                [
                    'headers' => [
                        'x-requested-with' => 'org.lineageos.jelly',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 12; Redmi 7 Build/SQ3A.220705.004) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Redmi 7',
                        'marketingName' => 'Redmi 7',
                        'manufacturer' => 'Xiaomi',
                        'brand' => 'Xiaomi',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 1520,
                            'height' => 720,
                            'touch' => true,
                            'size' => 6.26,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Lineage OS',
                        'marketingName' => 'Lineage OS',
                        'version' => '19.0.0',
                        'manufacturer' => 'unknown',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Jelly Browser',
                        'modus' => null,
                        'version' => null,
                        'manufacturer' => 'unknown',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '107.0.5304.105',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'imoAndroid/2020.03.2011; 10; REL; SM-G973F; samsung; play; phone; arm64-v8a'],
                [
                    'headers' => ['user-agent' => 'imoAndroid/2020.03.2011; 10; REL; SM-G973F; samsung; play; phone; arm64-v8a'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'SM-G973F',
                        'marketingName' => 'Galaxy S10 (Global)',
                        'manufacturer' => 'Samsung',
                        'brand' => 'Samsung',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 3040,
                            'height' => 1440,
                            'touch' => true,
                            'size' => 6.1,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => null,
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Webkit',
                        'modus' => null,
                        'version' => null,
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'com.amazon.sics/3.0.200230.0 (KFSUWI; Android 22; Amazon)'],
                [
                    'headers' => ['user-agent' => 'com.amazon.sics/3.0.200230.0 (KFSUWI; Android 22; Amazon)'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'KFSUWI',
                        'marketingName' => 'Fire HD 10 (2017)',
                        'manufacturer' => 'Amazon',
                        'brand' => 'Amazon',
                        'dualOrientation' => true,
                        'simCount' => 0,
                        'display' => [
                            'width' => 1920,
                            'height' => 1200,
                            'touch' => true,
                            'size' => 9.4,
                        ],
                        'type' => 'tablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Fire OS',
                        'marketingName' => 'Fire OS',
                        'version' => '8.0.0',
                        'manufacturer' => 'Amazon',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Webkit',
                        'modus' => null,
                        'version' => null,
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Dalvik/1.6.0 (Linux; U; Android 12/Viber 18.8.3.0 ; SM-G981BSP1A.210812.016) Viber/22.6.1.0'],
                [
                    'headers' => ['user-agent' => 'Dalvik/1.6.0 (Linux; U; Android 12/Viber 18.8.3.0 ; SM-G981BSP1A.210812.016) Viber/22.6.1.0'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'SM-G981B',
                        'marketingName' => 'Galaxy S20 5G (International)',
                        'manufacturer' => 'Samsung',
                        'brand' => 'Samsung',
                        'dualOrientation' => true,
                        'simCount' => 1,
                        'display' => [
                            'width' => 3200,
                            'height' => 1440,
                            'touch' => true,
                            'size' => 6.2,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '12.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Android Browser',
                        'modus' => null,
                        'version' => '1.6.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => null,
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (Mobile; Jio/F491H/Jio-F491H-001-06-24-271223;Android; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.5.3.2'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (Mobile; Jio/F491H/Jio-F491H-001-06-24-271223;Android; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.5.3.2'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'general Mobile device',
                        'marketingName' => 'general Mobile device',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'mobile-device',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'KaiOS',
                        'marketingName' => 'KaiOS',
                        'version' => '2.5.3.2',
                        'manufacturer' => 'KaiOS',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Firefox',
                        'modus' => null,
                        'version' => '48.0.0',
                        'manufacturer' => 'Mozilla',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Gecko',
                        'version' => '48.0.0',
                        'manufacturer' => 'Mozilla',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'light',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Microsoft Edge";v="138"',
                    'sec-ch-ua-arch' => '"x86"',
                    'sec-ch-ua-bitness' => '"64"',
                    'sec-ch-ua-form-factors' => '"Desktop"',
                    'sec-ch-ua-full-version' => '"138.0.3351.95"',
                    'sec-ch-ua-mobile' => '?0',
                    'sec-ch-ua-model' => '""',
                    'sec-ch-ua-platform' => '"Windows"',
                    'sec-ch-ua-platform-version' => '"19.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '""',
                        'sec-ch-ua-platform' => '"Windows"',
                        'sec-ch-ua-platform-version' => '"19.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Microsoft Edge";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.3351.95"',
                        'sec-ch-ua-bitness' => '"64"',
                        'sec-ch-ua-arch' => '"x86"',
                        'sec-ch-ua-form-factors' => '"Desktop"',
                        'sec-ch-ua-mobile' => '?0',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0',
                    ],
                    'device' => [
                        'architecture' => 'x86',
                        'deviceName' => 'Windows Desktop',
                        'marketingName' => 'Windows Desktop',
                        'manufacturer' => 'unknown',
                        'brand' => 'unknown',
                        'dualOrientation' => null,
                        'simCount' => 0,
                        'display' => [
                            'width' => null,
                            'height' => null,
                            'touch' => false,
                            'size' => null,
                        ],
                        'type' => 'desktop',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => 64,
                    ],
                    'os' => [
                        'name' => 'Windows',
                        'marketingName' => 'Windows',
                        'version' => '11.0.0',
                        'manufacturer' => 'Microsoft',
                        'bits' => 64,
                    ],
                    'client' => [
                        'name' => 'Edge',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Microsoft',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => 64,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"Mobile"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"Mobile"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"EInk", "Watch"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"EInk", "Watch"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'smart-watch',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"EInk"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"EInk"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'fone-pad',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"EInk", "Tablet"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"EInk", "Tablet"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'fone-pad',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"Tablet", "Automotive"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"Tablet", "Automotive"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'car-entertainment-system',
                        'ismobile' => false,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"EInk", "Xr"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"EInk", "Xr"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'wearable',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                [
                    'sec-ch-prefers-color-scheme' => 'dark',
                    'sec-ch-prefers-reduced-motion' => 'no-preference',
                    'sec-ch-prefers-reduced-transparency' => 'no-preference',
                    'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                    'sec-ch-ua-arch' => '""',
                    'sec-ch-ua-bitness' => '""',
                    'sec-ch-ua-form-factors' => '"Unknown Type"',
                    'sec-ch-ua-full-version' => '"138.0.7204.157"',
                    'sec-ch-ua-mobile' => '?1',
                    'sec-ch-ua-model' => '"moto g54 5G"',
                    'sec-ch-ua-platform' => '"Android"',
                    'sec-ch-ua-platform-version' => '"15.0.0"',
                    'sec-ch-ua-wow64' => '?0',
                    'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                ],
                [
                    'headers' => [
                        'sec-ch-ua-model' => '"moto g54 5G"',
                        'sec-ch-ua-platform' => '"Android"',
                        'sec-ch-ua-platform-version' => '"15.0.0"',
                        'sec-ch-ua' => '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"',
                        'sec-ch-ua-full-version' => '"138.0.7204.157"',
                        'sec-ch-ua-bitness' => '""',
                        'sec-ch-ua-arch' => '""',
                        'sec-ch-ua-form-factors' => '"Unknown Type"',
                        'sec-ch-ua-mobile' => '?1',
                        'sec-ch-ua-wow64' => '?0',
                        'user-agent' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36',
                    ],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'Moto G54 5G',
                        'marketingName' => 'Moto G54 5G',
                        'manufacturer' => 'Motorola',
                        'brand' => 'Motorola',
                        'dualOrientation' => true,
                        'simCount' => 2,
                        'display' => [
                            'width' => 2400,
                            'height' => 1080,
                            'touch' => true,
                            'size' => 6.5,
                        ],
                        'type' => 'smartphone',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'Android',
                        'marketingName' => 'Android',
                        'version' => '15.0.0',
                        'manufacturer' => 'Google',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Chrome',
                        'modus' => null,
                        'version' => '138.0.0',
                        'manufacturer' => 'Google',
                        'type' => 'browser',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'Blink',
                        'version' => '138.0.0.0',
                        'manufacturer' => 'Google',
                    ],
                ],
            ],
            [
                ['user-agent' => 'Mozilla/5.0 (iPad; CPU OS 26_1_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/397.0.836500703 Mobile/15E148 Safari/604.1'],
                [
                    'headers' => ['user-agent' => 'Mozilla/5.0 (iPad; CPU OS 26_1_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/397.0.836500703 Mobile/15E148 Safari/604.1'],
                    'device' => [
                        'architecture' => null,
                        'deviceName' => 'iPad',
                        'marketingName' => 'iPad',
                        'manufacturer' => 'Apple',
                        'brand' => 'Apple',
                        'dualOrientation' => true,
                        'simCount' => 0,
                        'display' => [
                            'width' => 1024,
                            'height' => 768,
                            'touch' => true,
                            'size' => 9.7,
                        ],
                        'type' => 'tablet',
                        'ismobile' => true,
                        'istv' => false,
                        'bits' => null,
                    ],
                    'os' => [
                        'name' => 'iPadOS',
                        'marketingName' => 'iPadOS',
                        'version' => '26.1.0',
                        'manufacturer' => 'Apple',
                        'bits' => null,
                    ],
                    'client' => [
                        'name' => 'Google Search App',
                        'modus' => null,
                        'version' => '397.0.836500703',
                        'manufacturer' => 'Google',
                        'type' => 'mobile-application',
                        'isbot' => false,
                        'bits' => null,
                    ],
                    'engine' => [
                        'name' => 'WebKit',
                        'version' => '605.1.15',
                        'manufacturer' => 'Apple',
                    ],
                ],
            ],
        ];
    }
}
