<?php

return [
    'test-00137-01102' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; LG-E975 Build/KOT49I.E97520a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '53',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.4.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00137-01103' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; GT-N8010 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '53',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.4.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'Galaxy Note 10.1 WiFi',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'GT-N8010',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00137-01134' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; SurfTab breeze 7.0 quad Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '53',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.4.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
