<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>
    Partner &amp; Kampagnen
</h2>

<div class="list">
    <div class="content">
        <div class="filter">
            <div class="buttons">
                <a href="<?php echo $this->basedUrl(array(
                    'module' => 'kredit-admin',
                    'controller' => 'mandant',
                    'action' => 'editportal',
                    'portal' => 0
                )) ?>/">Neuen Partner anlegen</a>
            </div>
        </div>
        <div class="table">
            <table id="sortableTable" class="Data sortableTable" summary="Partnerübersicht">
                <colgroup>
                    <col span="4" style="width:20px;" />
                    <col span="4" />
                </colgroup>
                <thead>
                    <tr>
                        <th colspan="4" scope="col">&nbsp;</th>
                        <th scope="col">Partner</th>
                        <th scope="col">Referenz Id</th>
                        <th scope="col">CSS-Datei</th>
                        <th scope="col">Kurzname in Statistik</th>
                        <th scope="col">Farbe in Statistik</th>
                        <th scope="col">Kontakt</th>
                    </tr>
                </thead>
<?php
$i = 0;
$classes=array('cycle1', 'cycle2');
foreach( (array)$this->partner as $key => $partner): $cycleClass = ($i % 2);
?>
                <tbody>
                    <tr class="<?php echo $classes[$cycleClass]; ?>">
                        <td class="first edit" title="Partner bearbeiten">
                            <a href="<?php echo $this->basedUrl(array(
                            'module' => 'kredit-admin',
                            'controller' => 'mandant',
                            'action' => 'editportal',
                            'portal' => $partner['p_id']
                        )); ?>/">&nbsp;</a>
                        </td>
                        <td class="first new" title="neue Kampagne erstellen">
                            <a href="<?php echo $this->basedUrl(array(
                            'module' => 'kredit-admin',
                            'controller' => 'mandant',
                            'action' => 'editcampaign',
                            'portal' => $partner['p_id'],
                            'campaign' => 0
                        )) ?>/">&nbsp;</a>
                        </td>
<?php
if (!$partner['active']) {
    $class = 'nok';
    $title = "das Portal '".$partner['name']."' aktivieren";
} else {
    $class = 'ok';
    $title = "das Portal '".$partner['name']."' deaktivieren";
}
?>
                        <td class="first <?php echo $class; ?>" title="<?php echo $title; ?>">
                            <a href="<?php echo $this->basedUrl(array(
                                'module' => 'kredit-admin',
                                'controller' => 'mandant',
                                'action' => 'activateportal',
                                'portal' => $partner['p_id'],
                                'aktiv'  => $partner['active']
                            )); ?>/">&nbsp;</a>
                        </td>
                        <td class="first">&nbsp;</td>
                        <td colspan="5"><strong><?php echo $partner['adresse']; ?>&nbsp;</strong></td>
                        <td>
                            <div class="email"><?php echo $partner['email']; ?>&nbsp;</div>
                            <div class="phone"><?php echo $partner['telefon']; ?>&nbsp;</div>
                        </td>
                    </tr>
<?php
$i++;
foreach( (array)$partner['childs'] as $ckey => $child):
$cycleClass = ($i % 2);
?>
                    <tr class="<?php echo $classes[$cycleClass]; ?>">
                        <td class="first edit" title="Kampagne bearbeiten">
                            <a href="<?php echo $this->basedUrl(array(
                            'module' => 'kredit-admin',
                            'controller' => 'mandant',
                            'action'   => 'editcampaign',
                            'campaign' => $child['idCampaigns'],
                            'portal'   => $partner['p_id']
                        )); ?>">&nbsp;</a>
                        </td>
                        <td class="first">&nbsp;</td>
<?php
if(!$child['css']) {
    $class = 'lock';
    $title = "die Kampagne '".$child['name']."' ist blockiert, CSS-Datei fehlt";
} elseif ($child['pic'] == 'lock') {
    $class = 'lock';
    $title = "die Kampagne '".$child['name']."' ist blockiert, ggf. erst Partner aktivieren";
} elseif ($child['active']) {
    $class = 'ok';
    $title = "die Kampagne '".$child['name']."' deaktivieren";
} else {
    $class = 'nok';
    $title = "die Kampagne '".$child['name']."' aktivieren";
}
?>
                        <td class="first <?php echo $class; ?>" title="<?php echo $title; ?>">
                            <?php if ($child['css'] && $child['pic'] != 'lock') { ?>
                            <a href="<?php echo $this->basedUrl(array(
                            'module' => 'kredit-admin',
                            'controller' => 'mandant',
                            'action'   => 'activatecampaign',
                            'campaign' => $child['idCampaigns'],
                            'aktiv'    => $child['active']
                        )); ?>">&nbsp;</a>
                            <?php } ?>
                        </td>
<?php
if(!$child['css']) {
    $class = 'nok';
    $title = "CSS-Datei ist nicht vorhanden";
} else {
    $class = 'ok';
    $title = "CSS-Datei ist vorhanden";
}
?>
                        <td class="first <?php echo $class; ?>" title="<?php echo $title; ?>">&nbsp;</td>
                        <td><strong><?php echo $partner['adresse']; ?></strong><i>::<?php echo $child['name'] ?></i></td>
                        <td><?php echo $child['name']; ?></td>
                        <td>
                            /css/<?php echo $child['idCampaigns']; ?>.css
                        </td>
                        <td><?php echo $child['name']; ?></td>
                        <td style="color:#<?php echo $child['color']; ?>;"><?php echo $child['color']; ?></td>
                        <td>&nbsp;</td>
                    </tr>
<?php
$i++;
endforeach;
?>
                </tbody>
<?php
endforeach;
?>
            </table>
        </div>

    </div>
    <div class="bottom"><span>&nbsp;</span></div>

</div>
<script type="text/javascript">
/* <![CDATA[ */
   addTableSorter('sortableTable');
/* ]]> */
</script>