<?php

return [
    'test-00053-03309' => [
        'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; nl; rv:1.9.2) Gecko/20100115 Firefox/3.6 (.NET CLR 3.5.30729)',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.6',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => 'XP.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'test-00053-03310' => [
        'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.3a3pre) Gecko/20100306 Firefox3.6 (.NET CLR 3.5.30729)',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '7.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'test-00053-03311' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; MDDRJS)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '8.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'test-00053-03312' => [
        'ua'         => 'Unibox/313 CFNetwork/754.1 Darwin/15.0.0 (x86_64)',
        'properties' => [
            'Browser_Name'            => 'Default Browser',
            'Browser_Type'            => 'unknown',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'Darwin',
            'Platform_Version'        => '15.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'test-00053-03313' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; MathPlayer 2.0)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '6.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => 'XP.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'test-00053-03314' => [
        'ua'         => 'Mozilla/5.0 (X11; U; Linux x86_64; it; rv:1.9.0.8) Gecko/2009032712 Ubuntu/8.10 (intrepid) Firefox/3.0.8',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.0',
            'Platform_Name'           => 'Ubuntu',
            'Platform_Version'        => '8.10.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Canonical Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'test-00053-03315' => [
        'ua'         => 'Dalvik/1.6.0 (Linux; U; Android ANDROID 5; Rainbow Build/KOT49H)',
        'properties' => [
            'Browser_Name'            => 'Default Browser',
            'Browser_Type'            => 'unknown',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'Android',
            'Platform_Version'        => '5.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'test-00053-03316' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.3; Rainbow Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Android WebView',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Name'           => 'Android',
            'Platform_Version'        => '4.3.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00053-03317' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; CMDTDF; .NET4.0C; AskTbNRO/5.12.5.17640; .NET4.0E)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '9.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '7.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'test-00053-03318' => [
        'ua'         => 'Mozilla/5.0 (Fedora; Linux x86_64) AppleWebKit/538.15 (KHTML, like Gecko) Version/8.0 Safari/538.15',
        'properties' => [
            'Browser_Name'            => 'Safari',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '8.0',
            'Platform_Name'           => 'Fedora Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Red Hat Inc',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
