<?php

/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2026, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace BrowserDetector\Parser\Helper\Device;

use BrowserDetector\Parser\Helper\DeviceInterface;
use Override;

/** @phpcs:disable SlevomatCodingStandard.Classes.ClassLength.ClassTooLong */
final class Huawei implements DeviceInterface
{
    /**
     * @return non-empty-string|null
     *
     * @throws void
     *
     * @phpcs:disable SlevomatCodingStandard.Functions.FunctionLength.FunctionLength
     */
    #[Override]
    public function getDeviceCode(string $code): string | null
    {
        $specialDevices = [];

        return match ($code) {
            'vog-l29' => 'huawei=huawei vog-l29',
            'nen-lx1' => 'huawei=huawei nen-lx1',
            'ppa-lx1' => 'huawei=huawei ppa-lx1',
            'jad-lx9' => 'huawei=huawei jad-lx9',
            'jad-al60' => 'huawei=huawei jad-al60',
            'jad-al80' => 'huawei=huawei jad-al80',
            'jad-al50' => 'huawei=huawei jad-al50',
            'jad-al00' => 'huawei=huawei jad-al00',
            'rea-nx9', 'honor rea-nx9', 'rea-nx9-n39' => 'huawei=huawei rea-nx9',
            'ntn-lx1', 'honor ntn-lx1' => 'huawei=huawei ntn-lx1',
            'lge-nx9' => 'huawei=huawei lge-nx9',
            'lge-an20' => 'huawei=huawei lge-an20',
            'lge-an10' => 'huawei=huawei lge-an10',
            'dby-w09' => 'huawei=huawei dby-w09',
            'nam-lx9' => 'huawei=huawei nam-lx9',
            'stk-lx1' => 'huawei=huawei stk-lx1',
            'ppa-lx2' => 'huawei=huawei ppa-lx2',
            'agr-w09' => 'huawei=huawei agr-w09',
            'ags3k-w09' => 'huawei=huawei ags3k-w09',
            'ags3k-w00' => 'huawei=huawei ags3k-w00',
            'ags3k-al20' => 'huawei=huawei ags3k-al20',
            'ags3k-l09' => 'huawei=huawei ags3k-l09',
            'nth-nx9' => 'huawei=huawei nth-nx9',
            'jsn-l21' => 'huawei=huawei jsn-l21',
            'jkm-lx2' => 'huawei=huawei jkm-lx2',
            'stk-l21' => 'huawei=huawei stk-l21',
            'sne-lx1' => 'huawei=huawei sne-lx1',
            'ine-lx1', 'ine-lx1-lx1' => 'huawei=huawei ine-lx1',
            'ine-lx1r' => 'huawei=huawei ine-lx1r',
            'fne-nx9' => 'huawei=huawei fne-nx9',
            'pgt-n19' => 'huawei=huawei pgt-n19',
            'pgt-an20' => 'huawei=huawei pgt-an20',
            'pgt-an10' => 'huawei=huawei pgt-an10',
            'pgt-an00' => 'huawei=huawei pgt-an00',
            'pgt-n09' => 'huawei=huawei pgt-n09',
            'yal-l41' => 'huawei=huawei yal-l41',
            'rvl-al09' => 'huawei=huawei rvl-al09',
            'ags2-w09' => 'huawei=huawei ags2-w09',
            'els-nx9', 'huawei els-nx9' => 'huawei=huawei els-nx9',
            'els-tn00', 'huawei els-tn00' => 'huawei=huawei els-tn00',
            'els-an10', 'huawei els-an10' => 'huawei=huawei els-an10',
            'els-an00', 'huawei els-an00' => 'huawei=huawei els-an00',
            'els-n39', 'huawei els-n39' => 'huawei=huawei els-n39',
            'els-n29', 'huawei els-n29' => 'huawei=huawei els-n29',
            'els-n04', 'huawei els-n04' => 'huawei=huawei els-n04',
            'ane-lx1', 'huawei ane-lx1' => 'huawei=huawei ane-lx1',
            'ane-lx2', 'huawei ane-lx2' => 'huawei=huawei ane-lx2',
            'ane-lx2j', 'huawei ane-lx2j' => 'huawei=huawei ane-lx2j',
            'ane-lx3', 'huawei ane-lx3' => 'huawei=huawei ane-lx3',
            'ane-l22', 'huawei ane-l22' => 'huawei=huawei ane-l22',
            'ane-al00', 'huawei ane-al00' => 'huawei=huawei ane-al00',
            'ane-tl00', 'huawei ane-tl00' => 'huawei=huawei ane-tl00',
            'jny-lx1' => 'huawei=huawei jny-lx1',
            'evr-l29' => 'huawei=huawei evr-l29',
            'evr-n29' => 'huawei=huawei evr-n29',
            'evr-tl00' => 'huawei=huawei evr-tl00',
            'evr-an00' => 'huawei=huawei evr-an00',
            'evr-al00' => 'huawei=huawei evr-al00',
            'bah-l09' => 'huawei=huawei bah-l09',
            'art-l29' => 'huawei=huawei art-l29',
            'bah2-w19' => 'huawei=huawei bah2-w19',
            'ags2-l09' => 'huawei=huawei ags2-l09',
            'yal-l21', 'huawei yal-l21', 'yal-l21-l71', 'yal-l21-l61' => 'huawei=huawei yal-l21',
            'rne-l21', 'huawei rne-l21' => 'huawei=huawei rne-l21',
            'rne-l22', 'huawei rne-l22' => 'huawei=huawei rne-l22',
            'rne-l03', 'huawei rne-l03' => 'huawei=huawei rne-l03',
            'rne-l02', 'huawei rne-l02' => 'huawei=huawei rne-l02',
            'rne-l01', 'huawei rne-l01' => 'huawei=huawei rne-l01',
            'rne-l23', 'huawei rne-l23' => 'huawei=huawei rne-l23',
            'rne-al10', 'huawei rne-al10' => 'huawei=huawei rne-al10',
            'rne-al00', 'huawei rne-al00' => 'huawei=huawei rne-al00',
            'pot-lx1' => 'huawei=huawei pot-lx1',
            'sht-al09' => 'huawei=huawei sht-al09',
            'bah-w09' => 'huawei=huawei bah-w09',
            'ele-l29' => 'huawei=huawei ele-l29',
            'cmr-al09' => 'huawei=huawei cmr-al09',
            'eml-l29' => 'huawei=huawei eml-l29',
            'mrd-lx1' => 'huawei=huawei mrd-lx1',
            'clt-l29' => 'huawei=huawei clt-l29',
            'huawei scl-l21' => 'huawei=huawei scl-l21',
            'amn-lx9' => 'huawei=huawei amn-lx9',
            'atu-l21' => 'huawei=huawei atu-l21',
            'was-lx1a' => 'huawei=huawei was-lx1a',
            'ags-w09' => 'huawei=huawei ags-w09',
            'bnd-l21' => 'huawei=huawei bnd-l21',
            'huawei can-l11' => 'huawei=huawei can-l11',
            'cor-l29' => 'huawei=huawei cor-l29',
            'vtr-l09' => 'huawei=huawei vtr-l09',
            'bkl-l09' => 'huawei=huawei bkl-l09',
            'pot-lx1t' => 'huawei=huawei pot-lx1t',
            'pot-lx1a' => 'huawei=huawei pot-lx1a',
            'eml-l09' => 'huawei=huawei eml-l09',
            'cmr-w09' => 'huawei=huawei cmr-w09',
            'stf-l09' => 'huawei=huawei stf-l09',
            'stf-al10' => 'huawei=huawei stf-al10',
            'stf-al00' => 'huawei=huawei stf-al00',
            'stf-tl10' => 'huawei=huawei stf-tl10',
            'stf-l09s' => 'huawei=huawei stf-l09s',
            'dub-lx1' => 'huawei=huawei dub-lx1',
            'huawei m2-a01w' => 'huawei=huawei m2-a01w',
            'dig-l21hn' => 'huawei=huawei dig-l21hn',
            'huawei vns-l31' => 'huawei=huawei vns-l31',
            'ine-lx2r' => 'huawei=huawei ine-lx2r',
            'ali-nx1' => 'huawei=huawei ali-nx1',
            'bvl-n49' => 'huawei=huawei bvl-n49',
            'eln-l03' => 'huawei=huawei eln-l03',
            'mha-l29' => 'huawei=huawei mha-l29',
            'bln-l21' => 'huawei=huawei bln-l21',
            'fdr-a01w' => 'huawei=huawei fdr-a01w',
            'duk-l09' => 'huawei=huawei duk-l09',
            'lyo-l21', 'huawei lyo-l21' => 'huawei=huawei lyo-l21',
            'sht-w09' => 'huawei=huawei sht-w09',
            'vky-l09' => 'huawei=huawei vky-l09',
            'ana-nx9' => 'huawei=huawei ana-nx9',
            'col-l29' => 'huawei=huawei col-l29',
            'nth-an00' => 'huawei=huawei nth-an00',
            'mna-lx9' => 'huawei=huawei mna-lx9',
            'rmo-nx1' => 'huawei=huawei rmo-nx1',
            'huawei m2-a01l' => 'huawei=huawei m2-a01l',
            'frd-l09' => 'huawei=huawei frd-l09',
            'huawei gra-l09' => 'huawei=huawei gra-l09',
            'cmr-al19' => 'huawei=huawei cmr-al19',
            'clt-l09' => 'huawei=huawei clt-l09',
            'vog-al00' => 'huawei=huawei vog-al00',
            'btv-dl09' => 'huawei=huawei btv-dl09',
            'eva-l09' => 'huawei=huawei eva-l09',
            'sla-l22' => 'huawei=huawei sla-l22',
            'lld-l31' => 'huawei=huawei lld-l31',
            'dra-lx9' => 'huawei=huawei dra-lx9',
            'bah2-l09' => 'huawei=huawei bah2-l09',
            'jmm-l22' => 'huawei=huawei jmm-l22',
            'pct-l29' => 'huawei=huawei pct-l29',
            'jsn-l22' => 'huawei=huawei jsn-l22',
            'mya-l41' => 'huawei=huawei mya-l41',
            'atu-l11' => 'huawei=huawei atu-l11',
            'was-lx1' => 'huawei=huawei was-lx1',
            'trt-lx1' => 'huawei=huawei trt-lx1',
            'ldn-l21' => 'huawei=huawei ldn-l21',
            'ags-l09' => 'huawei=huawei ags-l09',
            'huawei m2-801w' => 'huawei=huawei m2-801w',
            'lnd-l29' => 'huawei=huawei lnd-l29',
            'ale-l21' => 'huawei=huawei ale-l21',
            'fdr-a01l' => 'huawei=huawei fdr-a01l',
            'pic-lx9' => 'huawei=huawei pic-lx9',
            'bal-l49' => 'huawei=huawei bal-l49',
            'vtr-l29' => 'huawei=huawei vtr-l29',
            'alp-al00' => 'huawei=huawei alp-al00',
            'mrd-lx1f' => 'huawei=huawei mrd-lx1f',
            'plk-l01' => 'huawei=huawei plk-l01',
            'dco-lx9' => 'huawei=huawei dco-lx9',
            'dra-l21' => 'huawei=huawei dra-l21',
            'cdy-nx9a' => 'huawei=huawei cdy-nx9a',
            'huawei mla-l11' => 'huawei=huawei mla-l11',
            'vne-n41' => 'huawei=huawei vne-n41',
            'vne-an40' => 'huawei=huawei vne-an40',
            'vne-an00' => 'huawei=huawei vne-an00',
            'vne-lx3' => 'huawei=huawei vne-lx3',
            'vne-lx2' => 'huawei=huawei vne-lx2',
            'vne-lx1' => 'huawei=huawei vne-lx1',
            'alp-l09' => 'huawei=huawei alp-l09',
            'hey-w09', 'hey-w09-w09' => 'huawei=huawei hey-w09',
            'crt-nx1' => 'huawei=huawei crt-nx1',
            'mya-l13' => 'huawei=huawei mya-l13',
            'jdn2-w09' => 'huawei=huawei jdn2-w09',
            'crt-lx1' => 'huawei=huawei crt-lx1',
            'huawei cun-l21' => 'huawei=huawei cun-l21',
            'dli-l22' => 'huawei=huawei dli-l22',
            'gem-701l' => 'huawei=huawei gem-701l',
            'bll-l21' => 'huawei=huawei bll-l21',
            'huawei rio-l01' => 'huawei=huawei rio-l01',
            'atu-l31' => 'huawei=huawei atu-l31',
            'jdn2-l09' => 'huawei=huawei jdn2-l09',
            'nem-l51' => 'huawei=huawei nem-l51',
            'cma-lx1', 'honor cma-lx1' => 'huawei=huawei cma-lx1',
            'huawei tag-l21' => 'huawei=huawei tag-l21',
            'neo-l29' => 'huawei=huawei neo-l29',
            'che2-l11' => 'huawei=huawei che2-l11',
            'pot-lx1af' => 'huawei=huawei pot-lx1af',
            'was-lx2j' => 'huawei=huawei was-lx2j',
            'huawei can-l01' => 'huawei=huawei can-l01',
            'huawei lua-l21' => 'huawei=huawei lua-l21',
            'any-nx1' => 'huawei=huawei any-nx1',
            'was-tl10' => 'huawei=huawei was-tl10',
            'mha-l09' => 'huawei=huawei mha-l09',
            'nem-l21' => 'huawei=huawei nem-l21',
            'huawei vns-l21' => 'huawei=huawei vns-l21',
            'bln-l24' => 'huawei=huawei bln-l24',
            'stk-l22' => 'huawei=huawei stk-l22',
            'cam-l21' => 'huawei=huawei cam-l21',
            'lld-l21' => 'huawei=huawei lld-l21',
            'brp-nx1m' => 'huawei=huawei brp-nx1m',
            'fcp-n49' => 'huawei=huawei fcp-n49',
            'med-lx9n', 'huawei med-lx9n' => 'huawei=huawei med-lx9n',
            'mro-w09' => 'huawei=huawei mro-w09',
            'mro-w00' => 'huawei=huawei mro-w00',
            'mro-w10' => 'huawei=huawei mro-w10',
            'mro-al10' => 'huawei=huawei mro-al10',
            'bkk-al10' => 'huawei=huawei bkk-al10',
            'bkk-lx1' => 'huawei=huawei bkk-lx1',
            'bkk-lx2' => 'huawei=huawei bkk-lx2',
            'bkk-l21' => 'huawei=huawei bkk-l21',
            'bkk-al00' => 'huawei=huawei bkk-al00',
            'bkk-tl00' => 'huawei=huawei bkk-tl00',
            'ver-n49' => 'huawei=huawei ver-n49',
            'ver-n49dp' => 'huawei=huawei ver-n49dp',
            'ver-an10' => 'huawei=huawei ver-an10',
            'wgrr-w19' => 'huawei=huawei wgrr-w19',
            'wgrr-w09' => 'huawei=huawei wgrr-w09',
            'ptp-an10' => 'huawei=huawei ptp-an10',
            'ptp-an00' => 'huawei=huawei ptp-an00',
            'ptp-an70' => 'huawei=huawei ptp-an70',
            'ptp-n59' => 'huawei=huawei ptp-n59',
            'ptp-n49', 'ptp-n49-n49' => 'huawei=huawei ptp-n49',
            'ptp-n29' => 'huawei=huawei ptp-n29',
            'ptp-an60' => 'huawei=huawei ptp-an60',
            'ptp-an20' => 'huawei=huawei ptp-an20',
            'bon-al00' => 'huawei=huawei bon-al00',
            'icl-al20' => 'huawei=huawei icl-al20',
            'icl-al10' => 'huawei=huawei icl-al10',
            'icl-lx9' => 'huawei=huawei icl-lx9',
            'tgr-w09' => 'huawei=huawei tgr-w09',
            'tgr-w00' => 'huawei=huawei tgr-w00',
            'rod-w09' => 'huawei=huawei rod-w09',
            'mgi-an00' => 'huawei=huawei mgi-an00',
            'grl-al10' => 'huawei=huawei grl-al10',
            'krj2-an00' => 'huawei=huawei krj2-an00',
            'krj2-al00' => 'huawei=huawei krj2-al00',
            'krj2-w09' => 'huawei=huawei krj2-w09',
            'tet-an10' => 'huawei=huawei tet-an10',
            'tet-an00' => 'huawei=huawei tet-an00',
            'tet-an50' => 'huawei=huawei tet-an50',
            'tet-al00' => 'huawei=huawei tet-al00',
            'web-w00' => 'huawei=huawei web-w00',
            'wdy-lx2' => 'huawei=huawei wdy-lx2',
            'wdy-lx1' => 'huawei=huawei wdy-lx1',
            'hey2-w09', 'hey2-w09-w09' => 'huawei=huawei hey2-w09',
            'any-an00' => 'huawei=huawei any-an00',
            'any-lx3' => 'huawei=huawei any-lx3',
            'any-lx2' => 'huawei=huawei any-lx2',
            'any-lx1' => 'huawei=huawei any-lx1',
            'ada-al10u' => 'huawei=huawei ada-al10u',
            'ada-al00u' => 'huawei=huawei ada-al00u',
            'ada-al00' => 'huawei=huawei ada-al00',
            'elp-an00' => 'huawei=huawei elp-an00',
            'elp-nx9' => 'huawei=huawei elp-nx9',
            'eln-w09', 'honor eln-w09' => 'huawei=huawei eln-w09',
            'eln-l09' => 'huawei=huawei eln-l09',
            'cma-an40' => 'huawei=huawei cma-an40',
            'cma-an00' => 'huawei=huawei cma-an00',
            'cma-lx3' => 'huawei=huawei cma-lx3',
            'cma-lx2' => 'huawei=huawei cma-lx2',
            'bvl-an20' => 'huawei=huawei bvl-an20',
            'bvl-an16' => 'huawei=huawei bvl-an16',
            'bvl-n59' => 'huawei=huawei bvl-n59',
            'alt-an00' => 'huawei=huawei alt-an00',
            'alt-al10' => 'huawei=huawei alt-al10',
            'alt-al00' => 'huawei=huawei alt-al00',
            'alt-nx3' => 'huawei=huawei alt-nx3',
            'alt-nx1' => 'huawei=huawei alt-nx1',
            'alt-lx2', 'alt-lx2-l42' => 'huawei=huawei alt-lx2',
            'alt-lx1', 'honor alt-lx1' => 'huawei=huawei alt-lx1',
            'ctr-l81', 'huawei ctr-l81' => 'huawei=huawei ctr-l81',
            'aln-al80' => 'huawei=huawei aln-al80',
            'alp-an00' => 'huawei=huawei alp-an00',
            'wdy-an00' => 'huawei=huawei wdy-an00',
            'ali-an00' => 'huawei=huawei ali-an00',
            'vna-l29' => 'huawei=huawei vna-l29',
            'mrx-w29' => 'huawei=huawei mrx-w29',
            'krj-w09' => 'huawei=huawei krj-w09',
            'krj-an00' => 'huawei=huawei krj-an00',
            'web-w09' => 'huawei=huawei web-w09',
            'ple-701l' => 'huawei=huawei ple-701l',
            'maa-an10' => 'huawei=huawei maa-an10',
            'dvd-an00' => 'huawei=huawei dvd-an00',
            'dvd-an80' => 'huawei=huawei dvd-an80',
            'um840', 'huawei um840' => 'huawei=huawei um840',
            'rep-an00' => 'huawei=huawei rep-an00',
            'ver-an00' => 'huawei=huawei ver-an00',
            'eli-nx9' => 'huawei=huawei eli-nx9',
            'eli-an00' => 'huawei=huawei eli-an00',
            'fri-an10' => 'huawei=huawei fri-an10',
            'fri-nx9' => 'huawei=huawei fri-nx9',
            'fri-an00' => 'huawei=huawei fri-an00',
            'arc-al00' => 'huawei=huawei arc-al00',
            'maa-an00' => 'huawei=huawei maa-an00',
            'mag-an00' => 'huawei=huawei mag-an00',
            'clk-lx1' => 'huawei=huawei clk-lx1',
            'clk-lx2' => 'huawei=huawei clk-lx2',
            'clk-lx3' => 'huawei=huawei clk-lx3',
            'clk-an00' => 'huawei=huawei clk-an00',
            'gdi-w09' => 'huawei=huawei gdi-w09',
            'jdy-lx3' => 'huawei=huawei jdy-lx3',
            'jdy-lx2' => 'huawei=huawei jdy-lx2',
            'jdy-lx1', 'honor jdy-lx1' => 'huawei=huawei jdy-lx1',
            'jdy-an00' => 'huawei=huawei jdy-an00',
            'eln2-w29' => 'huawei=huawei eln2-w29',
            'eln2-l29' => 'huawei=huawei eln2-l29',
            'rol-w00' => 'huawei=huawei rol-w00',
            'amm-an00' => 'huawei=huawei amm-an00',
            'amp-an00' => 'huawei=huawei amp-an00',
            'tnnh-an00' => 'huawei=huawei tnnh-an00',
            'sdy-an00' => 'huawei=huawei sdy-an00',
            'alt-lx3' => 'huawei=huawei alt-lx3',
            'blk-al80' => 'huawei=huawei blk-al80',
            'nic-lx1a' => 'huawei=huawei nic-lx1a',
            'nic-lx1', 'honor nic-lx1' => 'huawei=huawei nic-lx1',
            'nic-lx2' => 'huawei=huawei nic-lx2',
            'nic-lx3' => 'huawei=huawei nic-lx3',
            'nic-an00' => 'huawei=huawei nic-an00',
            'rol-w60' => 'huawei=huawei rol-w60',
            'rod2-w69' => 'huawei=huawei rod2-w69',
            'ags5-al00' => 'huawei=huawei ags5-al00',
            'blk-lx9' => 'huawei=huawei blk-lx9',
            'gfy-al00' => 'huawei=huawei gfy-al00',
            'gfy-lx2p' => 'huawei=huawei gfy-lx2p',
            'gfy-lx2' => 'huawei=huawei gfy-lx2',
            'gfy-lx1', 'huawei gfy-lx1' => 'huawei=huawei gfy-lx1',
            'noh-al00' => 'huawei=huawei noh-al00',
            'noh-al10' => 'huawei=huawei noh-al10',
            'noh-an50' => 'huawei=huawei noh-an50',
            'noh-an80' => 'huawei=huawei noh-an80',
            'noh-an01' => 'huawei=huawei noh-an01',
            'noh-an00' => 'huawei=huawei noh-an00',
            'noh-nx9' => 'huawei=huawei noh-nx9',
            'pce-al30' => 'huawei=huawei pce-al30',
            'pce-w40' => 'huawei=huawei pce-w40',
            'pce-w30' => 'huawei=huawei pce-w30',
            'pce-w29' => 'huawei=huawei pce-w29',
            'jln-lx1' => 'huawei=huawei jln-lx1',
            'jln-lx3' => 'huawei=huawei jln-lx3',
            'jln-al00' => 'huawei=huawei jln-al00',
            'kob2-w09' => 'huawei=huawei kob2-w09',
            'kob2-w09hn' => 'huawei=huawei kob2-w09hn',
            'kob2-l09' => 'huawei=huawei kob2-l09',
            'kob2-l03' => 'huawei=huawei kob2-l03',
            'kob2-al00hn' => 'huawei=huawei kob2-al00hn',
            'bzc-w00' => 'huawei=huawei bzc-w00',
            'bzc-al00' => 'huawei=huawei bzc-al00',
            'ags3-w00e' => 'huawei=huawei ags3-w00e',
            'ags3-al00' => 'huawei=huawei ags3-al00',
            'ags3-al09hn' => 'huawei=huawei ags3-al09hn',
            'ags3-al09' => 'huawei=huawei ags3-al09',
            'ags3-w00d' => 'huawei=huawei ags3-w00d',
            'ags3-w09' => 'huawei=huawei ags3-w09',
            'ags3-l09' => 'huawei=huawei ags3-l09',
            'ags3-w9' => 'huawei=huawei ags3-w9',
            'mrx-w39' => 'huawei=huawei mrx-w39',
            'mrx-an19' => 'huawei=huawei mrx-an19',
            'mrx-al19' => 'huawei=huawei mrx-al19',
            'mrx-al09' => 'huawei=huawei mrx-al09',
            'mrx-w19' => 'huawei=huawei mrx-w19',
            'mrx-w09' => 'huawei=huawei mrx-w09',
            'bzt3-w09' => 'huawei=huawei bzt3-w09',
            'bzt3-al00' => 'huawei=huawei bzt3-al00',
            'bzd-w00' => 'huawei=huawei bzd-w00',
            'bzd-al00' => 'huawei=huawei bzd-al00',
            'agm3-w09hn' => 'huawei=huawei agm3-w09hn',
            'agm3-al09hn' => 'huawei=huawei agm3-al09hn',
            'brt-w09' => 'huawei=huawei brt-w09',
            'brt-an09' => 'huawei=huawei brt-an09',
            'tah-an00' => 'huawei=huawei tah-an00',
            'tah-an00m' => 'huawei=huawei tah-an00m',
            'tah-n29m' => 'huawei=huawei tah-n29m',
            'hjc-lx9' => 'huawei=huawei hjc-lx9',
            'hjc-an90' => 'huawei=huawei hjc-an90',
            'fio-bd00' => 'huawei=huawei fio-bd00',
            'ang-an00' => 'huawei=huawei ang-an00',
            'ang-lx1', 'huawei ang-lx1' => 'huawei=huawei ang-lx1',
            'ang-lx2' => 'huawei=huawei ang-lx2',
            'brq-al00' => 'huawei=huawei brq-al00',
            'brq-an00' => 'huawei=huawei brq-an00',
            'rna-an00' => 'huawei=huawei rna-an00',
            'rna-tn00' => 'huawei=huawei rna-tn00',
            'mld-al00' => 'huawei=huawei mld-al00',
            'mld-al10' => 'huawei=huawei mld-al10',
            'yok-an10' => 'huawei=huawei yok-an10',
            'tnn-an00' => 'huawei=huawei tnn-an00',
            'elz-an00' => 'huawei=huawei elz-an00',
            'elz-an10' => 'huawei=huawei elz-an10',
            'elz-an20' => 'huawei=huawei elz-an20',
            'hebe-bd00' => 'huawei=huawei hebe-bd00',
            'rte-al00' => 'huawei=huawei rte-al00',
            'jsc-al50' => 'huawei=huawei jsc-al50',
            'jsc-an00' => 'huawei=huawei jsc-an00',
            'chl-al60' => 'huawei=huawei chl-al60',
            'chl-al00' => 'huawei=huawei chl-al00',
            'chl-an00' => 'huawei=huawei chl-an00',
            'oce-an00' => 'huawei=huawei oce-an00',
            'oce-an50' => 'huawei=huawei oce-an50',
            'oce-al50' => 'huawei=huawei oce-al50',
            'oce-an10' => 'huawei=huawei oce-an10',
            'gia-an00' => 'huawei=huawei gia-an00',
            'gia-an80' => 'huawei=huawei gia-an80',
            'new-an90' => 'huawei=huawei new-an90',
            'lyn-an00' => 'huawei=huawei lyn-an00',
            'ndl-w09' => 'huawei=huawei ndl-w09',
            'ndl-l09' => 'huawei=huawei ndl-l09',
            'vca-an00' => 'huawei=huawei vca-an00',
            'juliaqn-l21b' => 'huawei=huawei juliaqn-l21b',
            'ali-nx3' => 'huawei=huawei ali-nx3',
            'clk-nx1', 'clk-nx1-n31' => 'huawei=huawei clk-nx1',
            'clk-nx2' => 'huawei=huawei clk-nx2',
            'clk-nx3' => 'huawei=huawei clk-nx3',
            'lge-n49b' => 'huawei=huawei lge-n49b',
            'lge-n19b' => 'huawei=huawei lge-n19b',
            'gbd-nx9' => 'huawei=huawei gbd-nx9',
            'juliaqn-l01b' => 'huawei=huawei juliaqn-l01b',
            'juliaqn-l23a' => 'huawei=huawei juliaqn-l23a',
            'rtg-nx9' => 'huawei=huawei rtg-nx9',
            'rea-an00' => 'huawei=huawei rea-an00',
            'hey2-n09' => 'huawei=huawei hey2-n09',
            'bve-w10' => 'huawei=huawei bve-w10',
            'tlr-al00' => 'huawei=huawei tlr-al00',
            'cls-al30' => 'huawei=huawei cls-al30',
            'cls-al00' => 'huawei=huawei cls-al00',
            'xyao-w00' => 'huawei=huawei xyao-w00',
            'pla-al10' => 'huawei=huawei pla-al10',
            'plr-l29' => 'huawei=huawei plr-l29',
            'plr-al50' => 'huawei=huawei plr-al50',
            'plr-al00' => 'huawei=huawei plr-al00',
            'hbp-lx9' => 'huawei=huawei hbp-lx9',
            'hbp-al00' => 'huawei=huawei hbp-al00',
            'mis-lx9', 'mis-lx9-lx9' => 'huawei=huawei mis-lx9',
            'mis-al00' => 'huawei=huawei mis-al00',
            'koz-al00cm' => 'huawei=huawei koz-al00cm',
            'koz-al00' => 'huawei=huawei koz-al00',
            'koz-al40' => 'huawei=huawei koz-al40',
            'nza-al00' => 'huawei=huawei nza-al00',
            'fin-al60a' => 'huawei=huawei fin-al60a',
            'fin-al60' => 'huawei=huawei fin-al60',
            'hbn-lx9' => 'huawei=huawei hbn-lx9',
            'hbn-al00' => 'huawei=huawei hbn-al00',
            'hbn-al10' => 'huawei=huawei hbn-al10',
            'hbn-al80' => 'huawei=huawei hbn-al80',
            'hpb-an00' => 'huawei=huawei hpb-an00',
            'dco-al00' => 'huawei=huawei dco-al00',
            'dnn-lx9' => 'huawei=huawei dnn-lx9',
            'dnn-an00' => 'huawei=huawei dnn-an00',
            'dnp-nx9', 'honor dnp-nx9', 'dnp-nx9-n39' => 'huawei=huawei dnp-nx9',
            'dnp-an00' => 'huawei=huawei dnp-an00',
            'dny-nx9', 'dny-nx9-n39' => 'huawei=huawei dny-nx9',
            'goa-lx9' => 'huawei=huawei goa-lx9',
            'goa-al80u' => 'huawei=huawei goa-al80u',
            'goa-al80' => 'huawei=huawei goa-al80',
            'jny-tl10' => 'huawei=huawei jny-tl10',
            'rbn-nx3' => 'huawei=huawei rbn-nx3',
            'mrr-w29' => 'huawei=huawei mrr-w29',
            'mrr-w39' => 'huawei=huawei mrr-w39',
            'amg-an00' => 'huawei=huawei amg-an00',
            'amn-lx1' => 'huawei=huawei amn-lx1',
            'amn-lx2' => 'huawei=huawei amn-lx2',
            'amn-lx3' => 'huawei=huawei amn-lx3',
            'amp-an10' => 'huawei=huawei amp-an10',
            'amz-l29' => 'huawei=huawei amz-l29',
            'nle-l29' => 'huawei=huawei nle-l29',
            'yal-l61' => 'huawei=huawei yal-l61',
            'yal-l61d' => 'huawei=huawei yal-l61d',
            'yal-l71' => 'huawei=huawei yal-l71',
            'yal-al00' => 'huawei=huawei yal-al00',
            'yal-al10' => 'huawei=huawei yal-al10',
            'stg-lx2' => 'huawei=huawei stg-lx2',
            'stg-lx1', 'huawei stg-lx1' => 'huawei=huawei stg-lx1',
            'rky-an10' => 'huawei=huawei rky-an10',
            'mao-al00' => 'huawei=huawei mao-al00',
            'rbn-nx1' => 'huawei=huawei rbn-nx1',
            'mao-lx9n' => 'huawei=huawei mao-lx9n',
            'mao-lx9' => 'huawei=huawei mao-lx9',
            'stg-al00' => 'huawei=huawei stg-al00',
            'anb-an00' => 'huawei=huawei anb-an00',
            'ann-an00' => 'huawei=huawei ann-an00',
            'anp-an00' => 'huawei=huawei anp-an00',
            'adt-an00' => 'huawei=huawei adt-an00',
            'tfy-an40' => 'huawei=huawei tfy-an40',
            'lge-an00' => 'huawei=huawei lge-an00',
            'dio-an00' => 'huawei=huawei dio-an00',
            'abr-al90' => 'huawei=huawei abr-al90',
            'abr-al80' => 'huawei=huawei abr-al80',
            'abr-al60' => 'huawei=huawei abr-al60',
            'abr-al00' => 'huawei=huawei abr-al00',
            'abr-n31c1' => 'huawei=huawei abr-n31c1',
            'abr-nx1', 'abr-nx1-n31' => 'huawei=huawei abr-nx1',
            'abr-lx9' => 'huawei=huawei abr-lx9',
            'abr-lx3' => 'huawei=huawei abr-lx3',
            'abr-lx2' => 'huawei=huawei abr-lx2',
            'abr-lx1', 'honor abr-lx1' => 'huawei=huawei abr-lx1',
            'hey3-n09' => 'huawei=huawei hey3-n09',
            'hey3-w00' => 'huawei=huawei hey3-w00',
            'rod-w19' => 'huawei=huawei rod-w19',
            'nla-lx2p', 'huawei nla-lx2p' => 'huawei=huawei nla-lx2p',
            'ela-lx3' => 'huawei=huawei ela-lx3',
            'ela-lx2' => 'huawei=huawei ela-lx2',
            'cle-an00' => 'huawei=huawei cle-an00',
            'lgn-lx1', 'honor lgn-lx1' => 'huawei=huawei lgn-lx1',
            'lmu-lx9' => 'huawei=huawei lmu-lx9',
            'plr-al30' => 'huawei=huawei plr-al30',
            'abr-an00' => 'huawei=huawei abr-an00',
            'mtn-an00' => 'huawei=huawei mtn-an00',
            'mtn-an80' => 'huawei=huawei mtn-an80',
            'mtn-nx1', 'honor mtn-nx1' => 'huawei=huawei mtn-nx1',
            'mtn-nx1m' => 'huawei=huawei mtn-nx1m',
            'grl-lx9' => 'huawei=huawei grl-lx9',
            'mbh-an10' => 'huawei=huawei mbh-an10',
            'mbh-n49' => 'huawei=huawei mbh-n49',
            'lly-nx1', 'lly-nx1-n31' => 'huawei=huawei lly-nx1',
            'lly-an00' => 'huawei=huawei lly-an00',
            'lly-lx3' => 'huawei=huawei lly-lx3',
            'lly-lx2' => 'huawei=huawei lly-lx2',
            'lly-lx1' => 'huawei=huawei lly-lx1',
            'lyo-l01' => 'huawei=huawei lyo-l01',
            'lyo-l02' => 'huawei=huawei lyo-l02',
            'ine-lx2' => 'huawei=huawei ine-lx2',
            'ine-al00' => 'huawei=huawei ine-al00',
            'ine-tl00' => 'huawei=huawei ine-tl00',
            'lld-tl10' => 'huawei=huawei lld-tl10',
            'lld-al30' => 'huawei=huawei lld-al30',
            'lld-al20', 'lld-al20-al20' => 'huawei=huawei lld-al20',
            'lld-al10' => 'huawei=huawei lld-al10',
            'lld-al00' => 'huawei=huawei lld-al00',
            'ath-al00' => 'huawei=huawei ath-al00',
            'ath-tl00h' => 'huawei=huawei ath-tl00h',
            'ath-ul00' => 'huawei=huawei ath-ul00',
            'ath-ul01' => 'huawei=huawei ath-ul01',
            'ath-ul06' => 'huawei=huawei ath-ul06',
            'fcp-an10' => 'huawei=huawei fcp-an10',
            'hdl-al09' => 'huawei=huawei hdl-al09',
            'hdl-w09' => 'huawei=huawei hdl-w09',
            'tgr-w10' => 'huawei=huawei tgr-w10',
            'plu-al10' => 'huawei=huawei plu-al10',
            'cet-al60' => 'huawei=huawei cet-al60',
            'cet-al00' => 'huawei=huawei cet-al00',
            'cet-lx9' => 'huawei=huawei cet-lx9',
            'mga-al00' => 'huawei=huawei mga-al00',
            'mga-al40' => 'huawei=huawei mga-al40',
            'mga-lx9n' => 'huawei=huawei mga-lx9n',
            'mga-lx9' => 'huawei=huawei mga-lx9',
            'mga-lx3' => 'huawei=huawei mga-lx3',
            'dvc-an00' => 'huawei=huawei dvc-an00',
            'cnd-an00' => 'huawei=huawei cnd-an00',
            'cdy-tn20' => 'huawei=huawei cdy-tn20',
            'cdl-an50' => 'huawei=huawei cdl-an50',
            'lio-tn00' => 'huawei=huawei lio-tn00',
            'lio-tl10' => 'huawei=huawei lio-tl10',
            'lio-tl00' => 'huawei=huawei lio-tl00',
            'lio-an00p' => 'huawei=huawei lio-an00p',
            'lio-an00m' => 'huawei=huawei lio-an00m',
            'lio-an00' => 'huawei=huawei lio-an00',
            'lio-al10' => 'huawei=huawei lio-al10',
            'lio-al00' => 'huawei=huawei lio-al00',
            'lio-n29' => 'huawei=huawei lio-n29',
            'lio-l29' => 'huawei=huawei lio-l29',
            'lio-l09' => 'huawei=huawei lio-l09',
            'ppg-an00' => 'huawei=huawei ppg-an00',
            'moa-tl00' => 'huawei=huawei moa-tl00',
            'moa-al20' => 'huawei=huawei moa-al20',
            'moa-al00' => 'huawei=huawei moa-al00',
            'moa-lx9n' => 'huawei=huawei moa-lx9n',
            'nmo-l22' => 'huawei=huawei nmo-l22',
            'nmo-l31', 'huawei nmo-l31' => 'huawei=huawei nmo-l31',
            'hol-t00', 'huawei hol-t00' => 'huawei=huawei hol-t00',
            'hol-u10', 'huawei hol-u10' => 'huawei=huawei hol-u10',
            'hol-u19', 'huawei hol-u19' => 'huawei=huawei hol-u19',
            'hn3-u00', 'huawei hn3-u00' => 'huawei=huawei hn3-u00',
            'hn3-u01', 'huawei hn3-u01' => 'huawei=huawei hn3-u01',
            'huawei mate 60 pro' => 'huawei=huawei mate 60 pro',
            'ntn-l22', 'huawei ntn-l22' => 'huawei=huawei ntn-l22',
            'ntn-lx3', 'huawei ntn-lx3' => 'huawei=huawei ntn-lx3',
            'jdn-w09', 'huawei jdn-w09' => 'huawei=huawei jdn-w09',
            'jdn-l01', 'huawei jdn-l01' => 'huawei=huawei jdn-l01',
            'nxt-al10', 'huawei nxt-al10' => 'huawei=huawei nxt-al10',
            'nxt-l09', 'huawei nxt-l09' => 'huawei=huawei nxt-l09',
            'nxt-l29', 'huawei nxt-l29' => 'huawei=huawei nxt-l29',
            'nxt-tl00', 'huawei nxt-tl00' => 'huawei=huawei nxt-tl00',
            'nxt-ul00', 'huawei nxt-ul00' => 'huawei=huawei nxt-ul00',
            'nxt-cl00', 'huawei nxt-cl00' => 'huawei=huawei nxt-cl00',
            'nxt-dl00', 'huawei nxt-dl00' => 'huawei=huawei nxt-dl00',
            'bkq-n49', 'huawei bkq-n49' => 'huawei=huawei bkq-n49',
            'bkq-an90', 'huawei bkq-an90' => 'huawei=huawei bkq-an90',
            'bkq-an10', 'huawei bkq-an10' => 'huawei=huawei bkq-an10',
            'mey-an00', 'huawei mey-an00' => 'huawei=huawei mey-an00',
            'mep-an00', 'huawei mep-an00' => 'huawei=huawei mep-an00',
            'nla-lx2', 'huawei nla-lx2' => 'huawei=huawei nla-lx2',
            'log-an00', 'huawei log-an00' => 'huawei=huawei log-an00',
            'ascend g310', 'huawei ascend g310' => 'huawei=huawei ascend g310',
            'huawei p30' => 'huawei=huawei p30',
            'kob-l09', 'huawei kob-l09' => 'huawei=huawei kob-l09',
            'kob-w09', 'huawei kob-w09' => 'huawei=huawei kob-w09',
            'fig-tl10', 'huawei fig-tl10' => 'huawei=huawei fig-tl10',
            'fig-tl00', 'huawei fig-tl00' => 'huawei=huawei fig-tl00',
            'fig-al00', 'huawei fig-al00' => 'huawei=huawei fig-al00',
            'fig-lx1', 'huawei fig-lx1' => 'huawei=huawei fig-lx1',
            'fig-lx2', 'huawei fig-lx2' => 'huawei=huawei fig-lx2',
            'fig-lx3', 'huawei fig-lx3' => 'huawei=huawei fig-lx3',
            'fig-la1', 'huawei fig-la1' => 'huawei=huawei fig-la1',
            'fig-l31', 'huawei fig-l31' => 'huawei=huawei fig-l31',
            'fig-l11', 'huawei fig-l11' => 'huawei=huawei fig-l11',
            'bvl-an00', 'huawei bvl-an00' => 'huawei=huawei bvl-an00',
            'alt-l29', 'huawei alt-l29' => 'huawei=huawei alt-l29',
            'tfy-an00', 'huawei tfy-an00' => 'huawei=huawei tfy-an00',
            'tfy-lx3', 'huawei tfy-lx3' => 'huawei=huawei tfy-lx3',
            'tfy-lx2', 'huawei tfy-lx2' => 'huawei=huawei tfy-lx2',
            'tfy-lx1', 'huawei tfy-lx1' => 'huawei=huawei tfy-lx1',
            'wod-lx3', 'huawei wod-lx3' => 'huawei=huawei wod-lx3',
            'wod-lx2', 'huawei wod-lx2' => 'huawei=huawei wod-lx2',
            'wod-lx1', 'huawei wod-lx1' => 'huawei=huawei wod-lx1',
            'had-w24', 'huawei had-w24' => 'huawei=huawei had-w24',
            'had-w32', 'huawei had-w32' => 'huawei=huawei had-w32',
            'bzi-w20', 'huawei bzi-w20' => 'huawei=huawei bzi-w20',
            'bzi-w00', 'huawei bzi-w00' => 'huawei=huawei bzi-w00',
            'bzi-al00', 'huawei bzi-al00' => 'huawei=huawei bzi-al00',
            'huawei mate 60' => 'huawei=huawei mate 60',
            'aln-al10', 'huawei aln-al10' => 'huawei=huawei aln-al10',
            'aln-al00', 'huawei aln-al00' => 'huawei=huawei aln-al00',
            'bra-al00', 'huawei bra-al00' => 'huawei=huawei bra-al00',
            'huawei_c8813d' => 'huawei=huawei c8813d',
            'aum-l41', 'huawei aum-l41' => 'huawei=huawei aum-l41',
            'aum-al00', 'huawei aum-al00' => 'huawei=huawei aum-al00',
            'aum-al20', 'huawei aum-al20' => 'huawei=huawei aum-al20',
            'aum-al29', 'huawei aum-al29' => 'huawei=huawei aum-al29',
            'aum-tl20', 'huawei aum-tl20' => 'huawei=huawei aum-tl20',
            'aum-l33', 'huawei aum-l33' => 'huawei=huawei aum-l33',
            'aum-l29', 'huawei aum-l29' => 'huawei=huawei aum-l29',
            'aum-l20', 'huawei aum-l20' => 'huawei=huawei aum-l20',
            'ctr-l91', 'huawei ctr-l91' => 'huawei=huawei ctr-l91',
            'ctr-lx1', 'huawei ctr-lx1' => 'huawei=huawei ctr-lx1',
            'ctr-lx2', 'huawei ctr-lx2' => 'huawei=huawei ctr-lx2',
            'ctr-lx3', 'huawei ctr-lx3' => 'huawei=huawei ctr-lx3',
            'ctr-al00', 'huawei ctr-al00' => 'huawei=huawei ctr-al00',
            'ctr-al20', 'huawei ctr-al20' => 'huawei=huawei ctr-al20',
            'hry-l21', 'huawei hry-l21' => 'huawei=huawei hry-l21',
            'hry-lx1', 'huawei hry-lx1' => 'huawei=huawei hry-lx1',
            'hry-lx1t', 'huawei hry-lx1t' => 'huawei=huawei hry-lx1t',
            'hry-lx1meb', 'huawei hry-lx1meb' => 'huawei=huawei hry-lx1meb',
            'hry-lx2', 'huawei hry-lx2' => 'huawei=huawei hry-lx2',
            'hry-al00', 'huawei hry-al00' => 'huawei=huawei hry-al00',
            'hry-al00a', 'huawei hry-al00a' => 'huawei=huawei hry-al00a',
            'hry-al00t', 'huawei hry-al00t' => 'huawei=huawei hry-al00t',
            'hry-al00ta', 'huawei hry-al00ta' => 'huawei=huawei hry-al00ta',
            'hry-al01', 'huawei hry-al01' => 'huawei=huawei hry-al01',
            'hry-tl00', 'huawei hry-tl00' => 'huawei=huawei hry-tl00',
            'hry-tl00t', 'huawei hry-tl00t' => 'huawei=huawei hry-tl00t',
            'hwi-al00', 'huawei hwi-al00' => 'huawei=huawei hwi-al00',
            'hwi-tl00', 'huawei hwi-tl00' => 'huawei=huawei hwi-tl00',
            'bkl-tl10', 'huawei bkl-tl10' => 'huawei=huawei bkl-tl10',
            'hma-tl00', 'huawei hma-tl00' => 'huawei=huawei hma-tl00',
            'hma-al00', 'huawei hma-al00' => 'huawei=huawei hma-al00',
            'hma-lx9', 'huawei hma-lx9' => 'huawei=huawei hma-lx9',
            'hma-l29', 'huawei hma-l29' => 'huawei=huawei hma-l29',
            'hma-l09', 'huawei hma-l09' => 'huawei=huawei hma-l09',
            'ebg-tn00', 'huawei ebg-tn00' => 'huawei=huawei ebg-tn00',
            'ebg-an10', 'huawei ebg-an10' => 'huawei=huawei ebg-an10',
            'ebg-an00', 'huawei ebg-an00' => 'huawei=huawei ebg-an00',
            'ebg-n19', 'huawei ebg-n19' => 'huawei=huawei ebg-n19',
            'gfy-lx3', 'huawei gfy-lx3' => 'huawei=huawei gfy-lx3',
            'naa-lx2p', 'huawei naa-lx2p' => 'huawei=huawei naa-lx2p',
            'nla-lx1', 'huawei nla-lx1' => 'huawei=huawei nla-lx1',
            'nla-lx3', 'huawei nla-lx3' => 'huawei=huawei nla-lx3',
            'lgn-nx1', 'huawei lgn-nx1', 'lgn-nx1-n31' => 'huawei=huawei lgn-nx1',
            'lgn-nx3', 'huawei lgn-nx3' => 'huawei=huawei lgn-nx3',
            'bla-l09s', 'huawei bla-l09s' => 'huawei=huawei bla-l09s',
            'bla-tl00', 'huawei bla-tl00' => 'huawei=huawei bla-tl00',
            'bla-al10', 'huawei bla-al10' => 'huawei=huawei bla-al10',
            'bla-l09', 'huawei bla-l09' => 'huawei=huawei bla-l09',
            'bla-al00', 'huawei bla-al00' => 'huawei=huawei bla-al00',
            'bla-l29', 'huawei bla-l29' => 'huawei=huawei bla-l29',
            'bla-a09', 'huawei bla-a09' => 'huawei=huawei bla-a09',
            'honor 30 pro' => 'huawei=huawei honor 30 pro',
            'bmh-tn10', 'huawei bmh-tn10' => 'huawei=huawei bmh-tn10',
            'bmh-an20', 'huawei bmh-an20' => 'huawei=huawei bmh-an20',
            'bmh-an10', 'huawei bmh-an10' => 'huawei=huawei bmh-an10',
            'eve-lx9n', 'huawei eve-lx9n' => 'huawei=huawei eve-lx9n',
            'eve-lx9', 'huawei eve-lx9' => 'huawei=huawei eve-lx9',
            'eve-lx3', 'huawei eve-lx3' => 'huawei=huawei eve-lx3',
            'jdy-lx3p', 'huawei jdy-lx3p' => 'huawei=huawei jdy-lx3p',
            'jef-n29', 'huawei jef-n29' => 'huawei=huawei jef-n29',
            'jsc-an00a', 'huawei jsc-an00a' => 'huawei=huawei jsc-an00a',
            'lya-al00l', 'huawei lya-al00l' => 'huawei=huawei lya-al00l',
            'lya-tl00', 'huawei lya-tl00' => 'huawei=huawei lya-tl00',
            'lya-al10', 'huawei lya-al10' => 'huawei=huawei lya-al10',
            'lya-al00', 'huawei lya-al00' => 'huawei=huawei lya-al00',
            'lya-l29', 'huawei lya-l29' => 'huawei=huawei lya-l29',
            'lya-l0c', 'huawei lya-l0c' => 'huawei=huawei lya-l0c',
            'lya-l09', 'huawei lya-l09' => 'huawei=huawei lya-l09',
            'mar-l03a', 'huawei mar-l03a' => 'huawei=huawei mar-l03a',
            'mar-l21h', 'huawei mar-l21h' => 'huawei=huawei mar-l21h',
            'mar-tl00', 'huawei mar-tl00' => 'huawei=huawei mar-tl00',
            'mar-al00', 'huawei mar-al00' => 'huawei=huawei mar-al00',
            'mar-lx3bm', 'huawei mar-lx3bm' => 'huawei=huawei mar-lx3bm',
            'mar-lx3am', 'huawei mar-lx3am' => 'huawei=huawei mar-lx3am',
            'mar-lx3a', 'huawei mar-lx3a' => 'huawei=huawei mar-lx3a',
            'mar-lx2j', 'huawei mar-lx2j' => 'huawei=huawei mar-lx2j',
            'mar-lx2b', 'huawei mar-lx2b' => 'huawei=huawei mar-lx2b',
            'mar-lx2', 'huawei mar-lx2' => 'huawei=huawei mar-lx2',
            'mar-lx1m', 'huawei mar-lx1m' => 'huawei=huawei mar-lx1m',
            'mar-lx1h', 'huawei mar-lx1h' => 'huawei=huawei mar-lx1h',
            'mar-lx1b', 'huawei mar-lx1b' => 'huawei=huawei mar-lx1b',
            'mar-lx1a', 'huawei mar-lx1a' => 'huawei=huawei mar-lx1a',
            'mar-l22b', 'huawei mar-l22b' => 'huawei=huawei mar-l22b',
            'mar-l22a', 'huawei mar-l22a' => 'huawei=huawei mar-l22a',
            'mar-l21mea', 'huawei mar-l21mea' => 'huawei=huawei mar-l21mea',
            'mar-l21bx', 'huawei mar-l21bx' => 'huawei=huawei mar-l21bx',
            'mar-l21b', 'huawei mar-l21b' => 'huawei=huawei mar-l21b',
            'mar-l21a', 'huawei mar-l21a' => 'huawei=huawei mar-l21a',
            'mar-l01a', 'huawei mar-l01a' => 'huawei=huawei mar-l01a',
            'marie-l21bx', 'huawei marie-l21bx' => 'huawei=huawei marie-l21bx',
            'matepad 10.8 lte' => 'huawei=huawei matepad 10.8 lte',
            'matepad 10.8 wi-fi' => 'huawei=huawei matepad 10.8 wi-fi',
            'scmr-al09', 'huawei scmr-al09' => 'huawei=huawei scmr-al09',
            'scmr-w09', 'huawei scmr-w09' => 'huawei=huawei scmr-w09',
            'matepad 5g' => 'huawei=huawei matepad 5g',
            'bah3-an10', 'huawei bah3-an10' => 'huawei=huawei bah3-an10',
            'bah3-al00', 'huawei bah3-al00' => 'huawei=huawei bah3-al00',
            'bah3-w59', 'huawei bah3-w59' => 'huawei=huawei bah3-w59',
            'bah3-w09', 'huawei bah3-w09' => 'huawei=huawei bah3-w09',
            'bah3-l09', 'huawei bah3-l09' => 'huawei=huawei bah3-l09',
            'matepad lte' => 'huawei=huawei matepad lte',
            'matepad pro 5g' => 'huawei=huawei matepad pro 5g',
            'matepad pro' => 'huawei=huawei matepad pro',
            'matepad pro wi-fi' => 'huawei=huawei matepad pro wi-fi',
            'matepad wi-fi' => 'huawei=huawei matepad wi-fi',
            'bah4-w19', 'huawei bah4-w19' => 'huawei=huawei bah4-w19',
            'bah4-al10', 'huawei bah4-al10' => 'huawei=huawei bah4-al10',
            'bah4-w39', 'huawei bah4-w39' => 'huawei=huawei bah4-w39',
            'bah4-w29', 'huawei bah4-w29' => 'huawei=huawei bah4-w29',
            'bah4-w09', 'huawei bah4-w09' => 'huawei=huawei bah4-w09',
            'bah4-l09', 'huawei bah4-l09' => 'huawei=huawei bah4-l09',
            'bky-w10', 'huawei bky-w10' => 'huawei=huawei bky-w10',
            'bky-w20', 'huawei bky-w20' => 'huawei=huawei bky-w20',
            'bky-w00', 'huawei bky-w00' => 'huawei=huawei bky-w00',
            'bky-w09', 'huawei bky-w09' => 'huawei=huawei bky-w09',
            'btkr-w00', 'huawei btkr-w00' => 'huawei=huawei btkr-w00',
            'btkr-w09', 'huawei btkr-w09' => 'huawei=huawei btkr-w09',
            'btk-w00', 'huawei btk-w00' => 'huawei=huawei btk-w00',
            'btk-w09', 'huawei btk-w09', 'btk-w09-w09' => 'huawei=huawei btk-w09',
            'btk-al09', 'huawei btk-al09' => 'huawei=huawei btk-al09',
            'dbr-w00', 'huawei dbr-w00' => 'huawei=huawei dbr-w00',
            'dbr-w19', 'huawei dbr-w19' => 'huawei=huawei dbr-w19',
            'dbr-w10', 'huawei dbr-w10' => 'huawei=huawei dbr-w10',
            'dbr-w09', 'huawei dbr-w09' => 'huawei=huawei dbr-w09',
            'dby2-al00', 'huawei dby2-al00' => 'huawei=huawei dby2-al00',
            'dby2-w09', 'huawei dby2-w09' => 'huawei=huawei dby2-w09',
            'dby2-w00', 'huawei dby2-w00' => 'huawei=huawei dby2-w00',
            'dby2-l09', 'huawei dby2-l09' => 'huawei=huawei dby2-l09',
            'hed-al00', 'huawei hed-al00' => 'huawei=huawei hed-al00',
            'hed-lx9', 'huawei hed-lx9' => 'huawei=huawei hed-lx9',
            'lem-al50', 'huawei lem-al50' => 'huawei=huawei lem-al50',
            'lem-al00', 'huawei lem-al00' => 'huawei=huawei lem-al00',
            'slg-w09', 'huawei slg-w09' => 'huawei=huawei slg-w09',
            'slg-w10', 'huawei slg-w10' => 'huawei=huawei slg-w10',
            'slg-w50', 'huawei slg-w50' => 'huawei=huawei slg-w50',
            'psd-al00', 'huawei psd-al00' => 'huawei=huawei psd-al00',
            'brp-an80', 'huawei brp-an80' => 'huawei=huawei brp-an80',
            'dby2-l09ck', 'huawei dby2-l09ck' => 'huawei=huawei dby2-l09ck',
            'lya-al00p', 'huawei lya-al00p' => 'huawei=huawei lya-al00p',
            'lna-lx2', 'huawei lna-lx2' => 'huawei=huawei lna-lx2',
            'ags6-w10', 'huawei ags6-w10' => 'huawei=huawei ags6-w10',
            'lna-nx1', 'huawei lna-nx1' => 'huawei=huawei lna-nx1',
            'bkq-an00', 'huawei bkq-an00' => 'huawei=huawei bkq-an00',
            'tlr-lx9', 'huawei tlr-lx9' => 'huawei=huawei tlr-lx9',
            'psd-al80', 'huawei psd-al80' => 'huawei=huawei psd-al80',
            'btk-al00', 'huawei btk-al00' => 'huawei=huawei btk-al00',
            'ags6-w00', 'huawei ags6-w00' => 'huawei=huawei ags6-w00',
            'ags6-w09', 'huawei ags6-w09' => 'huawei=huawei ags6-w09',
            'ags6-l09', 'huawei ags6-l09' => 'huawei=huawei ags6-l09',
            'nla-an00', 'huawei nla-an00' => 'huawei=huawei nla-an00',
            'log-an10', 'huawei log-an10' => 'huawei=huawei log-an10',
            'lgn-lx3', 'honor lgn-lx3' => 'huawei=huawei lgn-lx3',
            'ndl2-w09', 'huawei ndl2-w09' => 'huawei=huawei ndl2-w09',
            'ndl2-l09', 'huawei ndl2-l09' => 'huawei=huawei ndl2-l09',
            'eln2-w09', 'huawei eln2-w09' => 'huawei=huawei eln2-w09',
            'vkj-nx9', 'huawei vkj-nx9', 'vkj-nx9-n39' => 'huawei=huawei vkj-nx9',
            'lly-nx3', 'huawei lly-nx3' => 'huawei=huawei lly-nx3',
            'med-lx2', 'huawei med-lx2' => 'huawei=huawei med-lx2',
            'ags3-w09hn', 'huawei ags3-w09hn' => 'huawei=huawei ags3-w09hn',
            'ntn-an20', 'huawei ntn-an20' => 'huawei=huawei ntn-an20',
            'vkj-an00', 'huawei vkj-an00' => 'huawei=huawei vkj-an00',
            'vkj-an90', 'huawei vkj-an90' => 'huawei=huawei vkj-an90',
            'fig-al10', 'huawei fig-al10' => 'huawei=huawei fig-al10',
            'ali-nx3p', 'huawei ali-nx3p' => 'huawei=huawei ali-nx3p',
            'abr-nx3', 'huawei abr-nx3' => 'huawei=huawei abr-nx3',
            'aak-an00', 'huawei aak-an00' => 'huawei=huawei aak-an00',
            'lna-lx3', 'huawei lna-lx3' => 'huawei=huawei lna-lx3',
            'ldy-an00', 'huawei ldy-an00' => 'huawei=huawei ldy-an00',
            'lab-lx1', 'huawei lab-lx1' => 'huawei=huawei lab-lx1',
            'lab-lx2', 'huawei lab-lx2' => 'huawei=huawei lab-lx2',
            'lab-lx3', 'huawei lab-lx3' => 'huawei=huawei lab-lx3',
            'chg-w60', 'huawei chg-w60' => 'huawei=huawei chg-w60',
            'aap-an00', 'huawei aap-an00' => 'huawei=huawei aap-an00',
            'wdy-lx3', 'huawei wdy-lx3' => 'huawei=huawei wdy-lx3',
            'bre-al00b', 'huawei bre-al00b' => 'huawei=huawei bre-al00b',
            'bre-al00a', 'huawei bre-al00a' => 'huawei=huawei bre-al00a',
            'bre-al80a', 'huawei bre-al80a' => 'huawei=huawei bre-al80a',
            'bre-al80', 'huawei bre-al80' => 'huawei=huawei bre-al80',
            'ndl-l03', 'huawei ndl-l03' => 'huawei=huawei ndl-l03',
            'honor v30' => 'huawei=huawei honor v30',
            'honor v30 pro' => 'huawei=huawei honor v30 pro',
            'jny-l02a', 'huawei jny-l02a' => 'huawei=huawei jny-l02a',
            'jny-l02', 'huawei jny-l02' => 'huawei=huawei jny-l02',
            'jny-l01', 'huawei jny-l01' => 'huawei=huawei jny-l01',
            'pot-l41b', 'huawei pot-l41b' => 'huawei=huawei pot-l41b',
            'mtn-nx3', 'honor mtn-nx3' => 'huawei=huawei mtn-nx3',
            'ser-an00', 'huawei ser-an00' => 'huawei=huawei ser-an00',
            'pnm-an20', 'huawei pnm-an20' => 'huawei=huawei pnm-an20',
            'pnm-an10', 'huawei pnm-an10' => 'huawei=huawei pnm-an10',
            'pnm-n49', 'huawei pnm-n49' => 'huawei=huawei pnm-n49',
            'sne-lx2', 'huawei sne-lx2' => 'huawei=huawei sne-lx2',
            'sne-lx3', 'huawei sne-lx3' => 'huawei=huawei sne-lx3',
            'sne-l21', 'huawei sne-l21' => 'huawei=huawei sne-l21',
            'pot-l21t', 'huawei pot-l21t' => 'huawei=huawei pot-l21t',
            'pot-tl00a', 'huawei pot-tl00a' => 'huawei=huawei pot-tl00a',
            'pot-al10', 'huawei pot-al10' => 'huawei=huawei pot-al10',
            'pot-al00', 'huawei pot-al00' => 'huawei=huawei pot-al00',
            'pot-lx3', 'huawei pot-lx3' => 'huawei=huawei pot-lx3',
            'pot-lx2j', 'huawei pot-lx2j' => 'huawei=huawei pot-lx2j',
            'pot-lx2', 'huawei pot-lx2' => 'huawei=huawei pot-lx2',
            'pot-lx1rua', 'huawei pot-lx1rua' => 'huawei=huawei pot-lx1rua',
            'cdy-tn90', 'huawei cdy-tn90' => 'huawei=huawei cdy-tn90',
            'cdy-tn00', 'huawei cdy-tn00' => 'huawei=huawei cdy-tn00',
            'cdy-nx9b', 'huawei cdy-nx9b' => 'huawei=huawei cdy-nx9b',
            'cdy-an95', 'huawei cdy-an95' => 'huawei=huawei cdy-an95',
            'cdy-an90', 'huawei cdy-an90' => 'huawei=huawei cdy-an90',
            'cdy-an00', 'huawei cdy-an00' => 'huawei=huawei cdy-an00',
            'nla-nx1', 'huawei nla-nx1' => 'huawei=huawei nla-nx1',
            'honor x8' => 'huawei=huawei honor x8',
            'honor magic6 pro' => 'huawei=huawei honor magic 6 pro',
            'hey2-w19', 'huawei hey2-w19' => 'huawei=huawei hey2-w19',
            'vkp-nx9', 'huawei vkp-nx9' => 'huawei=huawei vkp-nx9',
            'vki-an00', 'huawei vki-an00' => 'huawei=huawei vki-an00',
            'lgn-lx2', 'huawei lgn-lx2' => 'huawei=huawei lgn-lx2',
            'hey3-w10', 'huawei hey3-w10' => 'huawei=huawei hey3-w10',
            'bkq-an20', 'huawei bkq-an20' => 'huawei=huawei bkq-an20',
            'rod2-w09', 'huawei rod2-w09' => 'huawei=huawei rod2-w09',
            'rol-w10', 'huawei rol-w10' => 'huawei=huawei rol-w10',
            'cgl-w00', 'huawei cgl-w00' => 'huawei=huawei cgl-w00',
            'cga-w00', 'huawei cga-w00' => 'huawei=huawei cga-w00',
            'bkq-an80', 'huawei bkq-an80' => 'huawei=huawei bkq-an80',
            'grl-al20', 'huawei grl-al20' => 'huawei=huawei grl-al20',
            'gem-w09', 'huawei gem-w09' => 'huawei=huawei gem-w09',
            'gem-w00', 'huawei gem-w00' => 'huawei=huawei gem-w00',
            'jms-w09', 'huawei jms-w09' => 'huawei=huawei jms-w09',
            'jms-l09', 'huawei jms-l09' => 'huawei=huawei jms-l09',
            'huawei mate x9' => 'huawei=huawei mate x9',
            'med-lx9', 'huawei med-lx9', 'med-lx9-lx9' => 'huawei=huawei med-lx9',
            'honor tab 5 8.0' => 'huawei=huawei honor tab 5 8.0',
            'honor 10i' => 'huawei=huawei honor 10i',
            'honor 20' => 'huawei=huawei honor 20',
            'honor 8a' => 'huawei=huawei honor 8a',
            'jat-tl00', 'huawei jat-tl00' => 'huawei=huawei jat-tl00',
            'jat-al00', 'huawei jat-al00' => 'huawei=huawei jat-al00',
            'jat-lx3', 'huawei jat-lx3' => 'huawei=huawei jat-lx3',
            'jat-lx1', 'huawei jat-lx1' => 'huawei=huawei jat-lx1',
            'jat-l41', 'huawei jat-l41' => 'huawei=huawei jat-l41',
            'jat-l29', 'huawei jat-l29' => 'huawei=huawei jat-l29',
            'jat-l09', 'huawei jat-l09' => 'huawei=huawei jat-l09',
            'honor 8s' => 'huawei=huawei honor 8s',
            'kse-lx9', 'huawei kse-lx9' => 'huawei=huawei kse-lx9',
            'ksa-al10', 'huawei ksa-al10' => 'huawei=huawei ksa-al10',
            'ksa-al00', 'huawei ksa-al00' => 'huawei=huawei ksa-al00',
            'ksa-lx9', 'huawei ksa-lx9' => 'huawei=huawei ksa-lx9',
            'ksa-lx3', 'huawei ksa-lx3' => 'huawei=huawei ksa-lx3',
            'ksa-lx2', 'huawei ksa-lx2' => 'huawei=huawei ksa-lx2',
            'honor 9x' => 'huawei=huawei honor 9x',
            'hlk-tl00', 'huawei hlk-tl00' => 'huawei=huawei hlk-tl00',
            'hlk-al10', 'huawei hlk-al10' => 'huawei=huawei hlk-al10',
            'hlk-al00a', 'huawei hlk-al00a' => 'huawei=huawei hlk-al00a',
            'hlk-al00', 'huawei hlk-al00' => 'huawei=huawei hlk-al00',
            'hlk-l42', 'huawei hlk-l42' => 'huawei=huawei hlk-l42',
            'hlk-l41', 'huawei hlk-l41' => 'huawei=huawei hlk-l41',
            'honor 9x pro' => 'huawei=huawei honor 9x pro',
            'honor play 3' => 'huawei=huawei honor play 3',
            'ask-al20', 'huawei ask-al20' => 'huawei=huawei ask-al20',
            'ask-al00x', 'huawei ask-al00x' => 'huawei=huawei ask-al00x',
            'honor magic 2 3d' => 'huawei=huawei honor magic 2 3d',
            'angela-l02b', 'huawei angela-l02b' => 'huawei=huawei angela-l02b',
            'pot-al00a', 'huawei pot-al00a' => 'huawei=huawei pot-al00a',
            'cdy-an20', 'huawei cdy-an20' => 'huawei=huawei cdy-an20',
            'honor 9s' => 'huawei=huawei honor 9s',
            'dua-tl00', 'huawei dua-tl00' => 'huawei=huawei dua-tl00',
            'dua-al00', 'huawei dua-al00' => 'huawei=huawei dua-al00',
            'dua-lx9', 'huawei dua-lx9' => 'huawei=huawei dua-lx9',
            'dua-lx3', 'huawei dua-lx3' => 'huawei=huawei dua-lx3',
            'dua-l22', 'huawei dua-l22' => 'huawei=huawei dua-l22',
            'mrt-al10', 'huawei mrt-al10' => 'huawei=huawei mrt-al10',
            'ascend g-510' => 'huawei=huawei g510',
            'honor play 8a' => 'huawei=huawei honor play 8a',
            'honor play 8' => 'huawei=huawei honor play 8',
            'honor 20i' => 'huawei=huawei honor 20i',
            'honor play 3e' => 'huawei=huawei honor play 3e',
            'honor 8a pro' => 'huawei=huawei honor 8a pro',
            'honor 9x lite' => 'huawei=huawei honor 9x lite',
            'pra-tl10', 'huawei pra-tl10' => 'huawei=huawei pra-tl10',
            'pra-al00x', 'huawei pra-al00x' => 'huawei=huawei pra-al00x',
            'pra-al00', 'huawei pra-al00' => 'huawei=huawei pra-al00',
            'pra-la1', 'huawei pra-la1' => 'huawei=huawei pra-la1',
            'pra-lx3', 'huawei pra-lx3' => 'huawei=huawei pra-lx3',
            'pra-lx2', 'huawei pra-lx2' => 'huawei=huawei pra-lx2',
            'pra-lx1', 'huawei pra-lx1' => 'huawei=huawei pra-lx1',
            'nova 5z' => 'huawei=huawei nova 5z',
            'spn-tl00', 'huawei spn-tl00' => 'huawei=huawei spn-tl00',
            'spn-al00', 'huawei spn-al00' => 'huawei=huawei spn-al00',
            'hera-bd00', 'huawei hera-bd00' => 'huawei=huawei hera-bd00',
            'vyg-al30', 'huawei vyg-al30' => 'huawei=huawei vyg-al30',
            'vyg-al00', 'huawei vyg-al00' => 'huawei=huawei vyg-al00',
            'ava-pa00', 'huawei ava-pa00' => 'huawei=huawei ava-pa00',
            // other
            default => null,
        };
    }
}
