<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>
    Statistik
</h2>
<script type="text/javascript">
var targetUrl = '<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview')); ?>';
</script>
<div class="navList ui-widget-content">
    <?php echo $this->filterform->render(); ?>
</div>
<div id="other" style="display:none;">&nbsp;</div>
<div id="jqAnchor" class="ui-widget-content">&nbsp;</div>
<div class="statisticsList" id="jqTemplate" style="display:none;">
    <div class="head" style="display:none;"><span>&nbsp;</span></div>
    <div class="content">
        <div id="table_" class="tablePlot">
            <table class="CalcData plot" id="tablePlot" summary="Statistik">
                <tbody>
                    <tr><td>&nbsp;</td></tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="bottom" style="display:none;"><span>&nbsp;</span></div>
</div>