<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: new.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<h2 class="newStatistics">
    grafische Statistik
</h2>
<div id="tabs" class="newStatistics">
    <ul class="tabs">
        <li><a href="#click" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'click')); ?>');">Clicks</a></li>
        <li><a href="#pageimpression" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'pageimpression')); ?>');">Pageimpressions</a></li>
        <li><a href="#info" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'info')); ?>');">Info-Button</a></li>
        <li><a href="#clickout" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'clickout')); ?>');">Kreditantr&auml;ge</a></li>
        <li><a href="#sale" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'sale')); ?>');">Leads</a></li>
        <li><a href="#other" onclick="this.href=getOverviewUrlNew('<?php echo $this->basedUrl(array('module'=>'kredit-admin','controller'=>'statistics','action'=>'overview-new','detailValue'=>'other')); ?>');">Anderes</a></li>
    </ul>
    <div class="panes">
        <div id="other">&nbsp;</div>
    </div>
</div>


<div id="jqAnchorGraphic" class="newStatistics ui-corner-all ui-widget-content">&nbsp;</div>

<div class="statisticsListGraphic" id="jqTemplate" style="display:none;">
    <div class="head"><span>&nbsp;</span></div>
    <div class="content">
        <div id="excStat_" class="statPlotGraphic"></div>
        <div id="table_" class="tablePlotGraphic">
            <table class="CalcData plot" id="tablePlot" summary="Statistik">
                <tbody>
                    <tr><td>&nbsp;</td></tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="bottom" style="display:none;"><span>&nbsp;</span></div>
</div>