<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<script type="text/javascript">
/* <![CDATA[ */

    var template = null;

    clearStatistic();

    jsonEvents = getevents();

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Campaign_Click', 'Anzahl Klicks', 'Calc', 'Portal / Kampagne', '#,###,###,###.', 'pie');

<?php
if ($this->type == 'other') {
?>
    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_BrowserType', 'genutzte Browser-Typen', 'AgentType', 'Browsertyp', '#,###,###,###.', 'pie');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Browser', 'genutzte Browser', 'Agent', 'Browser', '#,###,###,###.', 'pie');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Os', 'genutzte Betriebssysteme', 'BS', 'Betriebssystem', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Ie', 'Internet Explorer', 'IE', 'Version des IE', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Firefox', 'Firefox', 'FF', 'Version des FF', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Opera', 'Opera', 'Opera', 'Version von Opera', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Chrome', 'Chrome', 'Chrome', 'Version von Chrome', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Safari', 'Safari', 'Safari', 'Version von Safari', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Mozilla', 'Mozilla', 'Mozilla', 'Version von Mozilla', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Aol', 'AOL', 'AOL', 'Version von AOL', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Flock', 'Flock', 'Flock', 'Version von Flock', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Iron', 'Iron', 'Iron', 'Version von Iron', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Kmeleon', 'K-Meleon', 'K-Meleon', 'Version von K-Meleon', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Konqueror', 'Konqueror', 'Konqueror', 'Version von Konqueror', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_Netscape', 'Netscape', 'Netscape', 'Version von Netscape', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_SeaMonkey', 'SeaMonkey', 'SeaMonkey', 'Version von SeaMonkey', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_MobileBrowser', 'mobile Browser', 'mobil', 'Browser', '#,###,###,###.', 'no');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Agent_SyndicationReader', 'Syndication Reader', 'Reader', 'Reader', '#,###,###,###.', 'no');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Agent_Others', 'andere Browser', 'andere', 'Browser', '#,###,###,###.', 'no');
<?php
} elseif ($this->type == 'clickout' || $this->type == 'sale') { ?>
    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Summary_QuoteClicks', 'Click/Sale Quote', 'Quote', 'Portal / Kampagne', '#,###,###,###.## %', 'bar');

    <?php if ($this->sparte == 'Kredit') { ?>
    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Campaign_Summary', 'Kreditsumme', 'Summary', 'Portal / Kampagne', 'EUR #,###,###,###.##', 'pie');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Campaign_SummaryPercent', 'mittl. Kreditsumme', 'DSummary', 'Portal / Kampagne', 'EUR #,###,###,###.##', 'bar');

    template = jQuery('#jqTemplate').clone();
    template.appendTo('#jqAnchorGraphic');
    template.css('display', 'block');
    statistic(template, 'Campaign_TimePercent', 'mittl. LoanPeriods', 'LoanPeriodsen', 'Portal / Kampagne', '#,###,###,###.##', 'bar');

    //template = jQuery('#jqTemplate').clone();
    //template.appendTo('#jqAnchorGraphic');
    //template.css('display', 'block');
    //statistic(template, 'Campaign_Provision', 'Summe Provisionen', 'Provision', 'Portal / Kampagne', 'EUR #,###,###,###.##', 'pie');
    <?php } ?>
<?php
}
?>
/* ]]> */
</script>