<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: overview.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<script type="text/javascript">
/* <![CDATA[ */

    var template = null;

    clearStatistic();

    var clickouts = [];
    jQuery('#clickouts-element input:checkbox:checked').each(function(i){
        clickouts.push(jQuery(this).attr('value'));
    });
    var clickoutsales = [];
    jQuery('#clickoutsales-element input:checkbox:checked').each(function(i){
        clickoutsales.push(jQuery(this).attr('value'));
    });
    var sales = [];
    jQuery('#sales-element input:checkbox:checked').each(function(i){
        sales.push(jQuery(this).attr('value'));
    });

    var id = 1;

    jQuery.each(clickouts, function(i){
        template = jQuery('#jqTemplate').clone();
        template.appendTo('#jqAnchor');
        template.css('display', '');
        template.css('top', '0');
        template.attr('id', 'cloned_' + id);

        info = this.split(',');

        statisticTable(template, info[1], info[2], id, info[0]);

        id++;
    });

    jQuery.each(clickoutsales, function(i){
        template = jQuery('#jqTemplate').clone();
        template.appendTo('#jqAnchor');
        template.css('display', '');
        template.css('top', '0');
        template.attr('id', 'cloned_' + id);

        info = this.split(',');

        statisticTable(template, info[1], info[2], id, info[0]);

        id++;
    });

    jQuery.each(sales, function(i){
        template = jQuery('#jqTemplate').clone();
        template.appendTo('#jqAnchor');
        template.css('display', '');
        template.css('top', '0');
        template.attr('id', 'cloned_' + id);

        info = this.split(',');

        statisticTable(template, info[1], info[2], id, info[0]);

        id++;
    });
/* ]]> */
</script>