<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<xml dataset="<?php echo $this->reportNr; ?>">
    <anrede><?php echo ((isset($this->rData['anrede'])) ? $this->rData['anrede'] : ''); ?></anrede>
    <titel><?php echo ((isset($this->rData['titel'])) ? $this->rData['titel'] : ''); ?></titel>
    <vorname><?php echo ((isset($this->rData['vorname'])) ? $this->rData['vorname'] : ''); ?></vorname>
    <nachname><?php echo ((isset($this->rData['nachname'])) ? $this->rData['nachname'] : ''); ?></nachname>
    <land>Info nicht verfuegbar</land>
    <strasse><?php echo ((isset($this->rData['strasse'])) ? $this->rData['strasse'] : ''); ?></strasse>
    <hausnr><?php echo ((isset($this->rData['hausnr'])) ? $this->rData['hausnr'] : ''); ?></hausnr>
    <plz><?php echo ((isset($this->rData['plz'])) ? $this->rData['plz'] : ''); ?></plz>
    <ort><?php echo ((isset($this->rData['ort'])) ? $this->rData['ort'] : ''); ?></ort>
    <email><?php echo ((isset($this->rData['email'])) ? $this->rData['email'] : ''); ?></email>
    <vorwahl><?php echo ((isset($this->rData['vorwahl'])) ? $this->rData['vorwahl'] : ''); ?></vorwahl>
    <telefon><?php echo ((isset($this->rData['telefon'])) ? $this->rData['telefon'] : ''); ?></telefon>
    <vorwahlmobil>Info nicht verfuegbar</vorwahlmobil>
    <mobilfunk>Info nicht verfuegbar</mobilfunk>
    <gebdatumtag>Info nicht verfuegbar</gebdatumtag>
    <gebdatummonat>Info nicht verfuegbar</gebdatummonat>
    <gebdatumjahr>Info nicht verfuegbar</gebdatumjahr>
    <berufsgruppe><?php echo ((isset($this->rData['berufsgruppe'])) ? $this->rData['berufsgruppe'] : ''); ?></berufsgruppe>
    <probezeit><?php echo ((isset($this->rData['probezeit'])) ? $this->rData['probezeit'] : ''); ?></probezeit>
    <dreimonate>Info nicht verfuegbar</dreimonate>
    <schufaeinv><?php echo ((isset($this->rData['schufaeinv'])) ? $this->rData['schufaeinv'] : ''); ?></schufaeinv>
    <dateneinv>Info nicht verfuegbar</dateneinv>
    <agbeinv><?php echo $this->rData['agbeinv']; ?></agbeinv>
    <paid><?php echo $this->rData['paid']; ?></paid>
    <kreditbetrag><?php echo $this->rData['kreditbetrag']; ?></kreditbetrag>
    <laufzeit><?php echo $this->rData['laufzeit']; ?></laufzeit>
    <vzweck><?php echo ((isset($this->rData['zweck'])) ? $this->rData['zweck'] : ''); ?></vzweck>
    <test><?php echo ((isset($this->rData['test'])) ? $this->rData['test'] : ''); ?></test>
    <kreditinstitut><?php echo $this->rData['kreditinstitut']; ?></kreditinstitut>
    <sparte><?php echo $this->rData['sparte']; ?></sparte>
    <bonitaet><?php echo ((isset($this->rData['boniLevel'])) ? $this->rData['boniLevel'] : 'medium'); ?></bonitaet>
    <uuid><?php echo $this->uuid; ?></uuid>
</xml>