<?php
/**
 * Layout für den Index-Controller
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>
    Sparten
</h2>
<div class="list">
    <div class="content">
        <div class="filter">
            <div class="buttons">
                <a href="<?php echo $this->basedUrl(array(
                    'module' => 'kredit-admin',
                    'controller' => 'categories',
                    'action' => 'edit',
                    'sparte' => 0
                )) ?>/">neue Sparte anlegen</a>
            </div>
        </div>
        <div class="table">
            <table id="sortableTable" class="Data" summary="Spartenübersicht">
                <colgroup>
                    <col style="width:20px;" />
                    <col span="7" />
                </colgroup>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Standart-LoanPeriods in Monaten</th>
                        <th>ID im Leadsystem</th>
                        <th>Code f&uuml;r Antr&auml;ge</th>
                        <th>aktiv</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
<?php
if (isset($this->paginator) && is_object($this->paginator)) :
foreach ($this->paginator->getItemsByPage($this->paginator->getCurrentPageNumber()) as $sparte) :
?>
                    <tr class="<?php echo $this->cycle(array('fstRow','scdRow'))->next(); ?>" title="die Sparte '<?php echo $sparte->name; ?>' ist <?php if (!$sparte->active) { echo 'nicht ';} ?>aktiviert">
                        <td class="first edit" title="Sparte bearbeiten"><a href="<?php echo $this->basedUrl(array(
                            'module' => 'kredit-admin',
                            'controller' => 'categories',
                            'action' => 'edit',
                            'sparte' => $sparte->idCategories
                        )); ?>">&nbsp;</a>
                        </td>
                        <td><?php echo $sparte->idCategories; ?></td>
                        <td><?php echo $sparte->name; ?></td>
                        <td><?php echo $sparte->defaultLoanPeriods; ?></td>
                        <td><?php echo $sparte->LEAD_Id; ?></td>
                        <td><?php echo $sparte->Code; ?></td>
<?php
if (!$sparte->active) {
    $class = 'nok';
    $title = "die Sparte '$sparte->name' aktivieren";
} else {
    $class = 'ok';
    $title = "die Sparte '$sparte->name' deaktivieren";
}
?>
                        <td class="<?php echo $class; ?>" title="<?php echo $title; ?>">
                            <a href="<?php echo $this->basedUrl(array(
                                'module' => 'kredit-admin',
                                'controller' => 'categories',
                                'action' => 'activate',
                                'sparte' => $sparte->idCategories,
                                'aktiv'  => $sparte->active
                            )) ?>/">&nbsp;</a></td>
                        <td>
                            <div class="info" title="Products anzeigen">
                                <a href="<?php echo $this->basedUrl(array(
                                    'module' => 'kredit-admin',
                                    'controller' => 'products',
                                    'action' => 'index',
                                    'sparte' => $sparte->idCategories
                                )) ?>/">Products anzeigen</a>
                            </div>
                            <div class="small">TODO: l&ouml;schen ??, Details anzeigen</div>
                        </td>
                    </tr>
<?php
endforeach;
endif;
?>
                </tbody>
            </table>
        </div>
        <div class="filter">
            <?php if (null !== $this->queryPaginator) echo $this->paginationControl($this->queryPaginator, 'Sliding', 'pagination.phtml', array('module' => 'kredit-admin','controller' => 'categories','action'  => 'index')); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="bottom"><span>&nbsp;</span></div>
</div>