<?php

namespace BrowserDetectorTest\Detector\Device\Mobile\FaktorZwei;

use BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:40:08.
 */
class Fx2Pad10Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Fx2Pad10
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Fx2Pad10('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::detectOs
     * @todo   Implement testDetectOs().
     */
    public function testDetectOs()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getDeviceName
     * @todo   Implement testGetDeviceName().
     */
    public function testGetDeviceName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getDualOrientation
     * @todo   Implement testGetDualOrientation().
     */
    public function testGetDualOrientation()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getHasQwertyKeyboard
     * @todo   Implement testGetHasQwertyKeyboard().
     */
    public function testGetHasQwertyKeyboard()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getMarketingName
     * @todo   Implement testGetMarketingName().
     */
    public function testGetMarketingName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getNfcSupport
     * @todo   Implement testGetNfcSupport().
     */
    public function testGetNfcSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getPointingMethod
     * @todo   Implement testGetPointingMethod().
     */
    public function testGetPointingMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getResolutionHeight
     * @todo   Implement testGetResolutionHeight().
     */
    public function testGetResolutionHeight()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getResolutionWidth
     * @todo   Implement testGetResolutionWidth().
     */
    public function testGetResolutionWidth()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getSmsSupport
     * @todo   Implement testGetSmsSupport().
     */
    public function testGetSmsSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\FaktorZwei\Fx2Pad10::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
