<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>Status des Datensatzes &auml;ndern</h2>
<div class="list">

    <div class="head">
        <span></span>
    </div>
    <div class="content">
    <?php echo $this->form ?>
    </div>
    <div class="bottom"><span></span></div>
</div>