<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>
    Antr&auml;ge
</h2>

<div class="list">
    <div class="content">
        <div class="filter">
            &nbsp;
        </div>

        <div class="table">
        <table id="sortableTable" class="Data sortableTable" summary="Antragsübersicht">
            <colgroup>
                <col style="width:20px" />
                <col span="7" />
            </colgroup>
            <thead>
                <tr>
                    <th scope="col">&nbsp;</th>
                    <th scope="col">Schl&uuml;ssel</th>
                    <th scope="col">erstellt</th>
                    <th scope="col">Antragsteller</th>
                    <th scope="col">Status</th>
                    <th scope="col">Gesellschaft<br />Tarif</th>
                    <th scope="col">Sparte</th>
                    <th scope="col">Aktivit&auml;t</th>
                    <th scope="col">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
<?php
if (isset($this->paginator) && is_object($this->paginator)) :
    foreach ($this->paginator->getItemsByPage($this->paginator->getCurrentPageNumber()) as $row) :
?>
                <tr class="<?php echo $this->cycle(array('cycle1', 'cycle2'))->next(); ?>" >
                    <td>

                    </td>
                    <td>
                        <?php echo $row->processID; ?>
                    </td>
                    <td>
                        <?php echo date('d.m.Y H:i', strtotime($row->date)); ?> Uhr
                    </td>
                    <td><?php echo $this->escape($row->name); ?></td>
                    <td>
                        ohne Status
                    </td>
                    <td>
                        <?php echo $this->escape($row->institut); ?><br />
                        <?php //echo $this->escape($row->institut); ?>
                    </td>
                    <td><?php echo $this->escape($row->sparte); ?></td>
                    <td>
                        keine Aktivität
                    </td>
                    <td>

                    </td>
                </tr>
<?php
    endforeach;
endif;
?>
            </tbody>
        </table>
        </div>
        <div class="filter">
            <?php if (null !== $this->queryPaginator) echo $this->paginationControl($this->queryPaginator, 'Sliding', 'pagination.phtml', array('module' => 'kredit-admin','controller' => 'application-list','action'  => 'index')); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="bottom"><span>&nbsp;</span></div>
    <div class="content">
        <div class="table">
            <a href="<?php echo $this->basedUrl(array('module' => 'kredit-admin', 'controller' => 'application-list', 'action' => 'export-not-sent-datasets'), 'default', true);?>" style="color:#000;">Export aller Datens&auml;tze, die nicht per Service &uuml;bermittelt werden konnten</a>
        </div>
    </div>
    <div class="bottom"><span>&nbsp;</span></div>
</div>
<script type="text/javascript">
/* <![CDATA[ */
   addTableSorter('sortableTable');
/* ]]> */
</script>