<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

$functionName = 'show_calc_'.$this->sparteId.'_'.$this->caid.'_'.$this->loanPeriod.'_'.$this->zweck.'_'.$this->betrag;
if ($this->bestOnly) {
    $functionName .= '_bestonly';
}
if ($this->boni !== null && $this->boni) {
    $functionName .= '_boni';
}
if ($this->boni !== null && !$this->boni) {
    $functionName .= '_noboni';
}
if ($this->institut) {
   $functionName .= '_'.$this->institut;
}
?>
jQuery.creditcalc.<?php echo $functionName; ?> = function() {
    var s = this;

    s.setCalculationContent('<?php echo $this->calcText; ?>', '../kampagne/<?php echo $this->campaignId; ?>/js/<?php echo $this->mode; ?>/calc.js', '../kampagne/<?php echo $this->campaignId; ?>/css/<?php echo $this->mode; ?>/calc.css');

    s.c[s.c.length] = '<?php echo $functionName; ?>';
}

jQuery.creditcalc.<?php echo $functionName; ?>();