<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

$functionName = 'show_form_'.$this->sparteId.'_'.$this->caid.'_'.$this->loanPeriod.'_'.$this->zweck.'_'.$this->betrag;

?>
jQuery.creditcalc.<?php echo $functionName; ?> = function() {
    var s = this;

    s.setFormContent('<?php echo $this->formText; ?>');
}

jQuery.creditcalc.<?php echo $functionName; ?>();