<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

$functionName = 'show_info_'.$this->sparteId.'_'.$this->caid.'_'.$this->product;

?>
function <?php echo $functionName; ?>() {
    showInfo('<div class="help"><?php echo $this->infoText; ?></div>');
    called_functions[called_functions.length] = '<?php echo $functionName; ?>';
}

<?php echo $functionName; ?>();