<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<html>
<body>
<h2>E-Mail zum Kreditantrag</h2>
<table cellpadding="0" cellspacing="0" class="kredite">
<?php foreach ($this->requestData as $key => $item) { ?>
<?php if ($key != 'lnktype' && $key != 'partner_id' && $key != 'ccstart' && $key != 'nav_id' && $key != 'datei_name' && $key != 'berufsgruppeLabel' && $key != 'kredit_antrag' && $key != 'vzweckLabel') { ?>
<?php $cycleClass = $this->cycle(array('fstRow','scdRow'))->next(); ?>
    <tr class="<?php echo $cycleClass; ?>">
        <td><label><?php echo $key; ?></label>:</td><td><span><?php if ($key != 'berufsgruppe'){ echo $item; } else { echo $this->berufsgruppe; } ?></span></td>
    </tr>
<?php } ?>
<?php } ?>
</table>
<br />
<br />
<table cellpadding="0" cellspacing="0" class="kredite">
    <tr class="fstRow">
        <td><label>CSV:</label>:</td><td><span><?php echo $this->csv; ?></span></td>
    </tr>
</table>
</body>
</html>