<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Controller
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @license   http://www.unister.de  Unister License
 * @version   SVN: $Id$
 * @link      todo
 */
?>
<h1>An error occurred</h1>
<h2><?php echo $this->message; ?></h2>
<h3>Exception information:</h3>
<p>
<strong>Message:</strong> <?php echo $this->exception->getMessage(); ?>
</p>
<h3>Aufruf:</h3>
<pre><?php echo $this->request->getRequestUri(); ?></pre>
<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
<h3>Request Parameters:</h3>
<pre><?php var_dump($this->request->getParams()) ?></pre>
<h4>other Information</h4>
<pre><?php var_dump($this->request) ?></pre>
<h4>SERVER Information</h4>
<pre><?php var_dump($_SERVER) ?></pre>
<h4>REQUEST Information</h4>
<pre><?php var_dump($_REQUEST) ?></pre>