<?php
/**
 * Layout für den Index-Controller
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<h2>
    Products
</h2>
<div class="list">
    <div class="content">
        <div class="filter">
            <div class="buttons">
                <a href="<?php echo $this->newUrl; ?>/">neues Produkt anlegen</a>
            </div>
        </div>
        <div class="table">
            <table id="sortableTable" class="Data" summary="Produktübersicht">
                <colgroup>
                    <col style="width:20px;" />
                    <col span="12" />
                </colgroup>
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>Institut</th>
                        <th>Sparte</th>
                        <th>Produkt</th>
                        <th>Minimalbetrag in Euro</th>
                        <th>Maximalbetrag in Euro</th>
                        <th>Annahme in Prozent</th>
                        <th>Entscheidungs-zeitraum</th>
                        <th>Testsiegerbild vorhanden</th>
                        <th>bonit&auml;tsabh&auml;ngig</th>
                        <th>aktiv</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
<?php
if (isset($this->paginator) && is_object($this->paginator)) :
foreach ($this->paginator->getItemsByPage($this->paginator->getCurrentPageNumber()) as $product) :
if (!is_object($product)) {
    continue;
}
//Produkt, Institut uns Sparte sind aktiviert
$active  = ($product->active && $product->active && $product->s_active);
//Institut uns Sparte sind aktiviert
$active2 = ($product->active && $product->s_active);
?>
                    <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
                        <td class="first edit" title="Produkt bearbeiten"><a href="<?php echo str_replace(array('###product###', '%23%23%23product%23%23%23'), $product->idProducts, $this->editUrl); ?>/">&nbsp;</a>
                        </td>
                        <td><?php echo $product->idProducts; ?></td>
                        <td><?php echo $product->institut; ?></td>
                        <td><?php echo $product->sparte; ?></td>
                        <td><?php echo $product->kp_desc; ?></td>
                        <td><?php echo $product->min; ?></td>
                        <td><?php echo $product->max; ?></td>
                        <td><?php echo $product->annahme; ?></td>
                        <td><?php echo $product->entscheidung; ?></td>
<?php
if (!$product->testsieger) {
    $class = 'nok';
} else {
    $class = 'ok';
}
?>
                        <td class="<?php echo $class; ?>">&nbsp;</td>
<?php
if (!$product->boni) {
    $class = 'nok';
} else {
    $class = 'ok';
}
?>
                        <td class="<?php echo $class; ?>">&nbsp;</td>
<?php
if (!$active2) {
    $class = 'lock';
    $title = '';
    if (!$product->active) { $title .= 'das Institut'; }
    if (!$product->s_active) { $title .= 'die Sparte'; }
    $title .= ' ist nicht aktiviert';
} elseif(!$active) {
    $class = 'nok';
    $title = "das Produkt '$product->kp_desc' aktivieren";
} else {
    $class = 'ok';
    $title = "das Produkt '$product->kp_desc' deaktivieren";
}
?>
                        <td class="<?php echo $class; ?>" title="<?php echo $title; ?>">
                            <?php if ($active2) { ?>
                            <a href="<?php echo $this->basedUrl(array(
                                    'module' => 'kredit-admin',
                                    'controller' => 'products',
                                    'action'  => 'activate',
                                    'product' => $product->idProducts,
                                    'aktiv'   => $product->active
                                )) ?>/">
                            <?php } ?>
                            &nbsp;
                            <?php if ($active2) { ?>
                            </a>
                            <?php } ?>
                        </td>
                        <td>
                            <div class="info" title="Produkt-Details anzeigen">
                                <a href="<?php echo $this->basedUrl(array(
                                    'module' => 'kredit-admin',
                                    'controller' => 'products',
                                    'action'  => 'detail',
                                    'product' => $product->idProducts
                                )) ?>/">Produkt-Details anzeigen</a>
                            </div>
                            <div class="small">TODO: l&ouml;schen ??</div>
                        </td>
                    </tr>
<?php
endforeach;
endif;
?>
                </tbody>
            </table>
        </div>
        <div class="filter">
            <?php echo $this->paginationControl($this->queryPaginator, 'Sliding', 'pagination.phtml', array('module' => 'kredit-admin','controller' => 'products','action'  => 'index')); ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="bottom"><span>&nbsp;</span></div>
</div>