<?php
/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2017, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);
namespace BrowserDetectorTest\Factory\Device\Mobile;

use BrowserDetector\Factory\Device\Mobile\NokiaFactory;
use BrowserDetector\Loader\DeviceLoader;
use Cache\Adapter\Filesystem\FilesystemCachePool;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Stringy\Stringy;

/**
 * Test class for \BrowserDetector\Detector\Device\Mobile\GeneralMobile
 */
class NokiaFactoryTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var \BrowserDetector\Factory\Device\Mobile\NokiaFactory
     */
    private $object = null;

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $adapter      = new Local(__DIR__ . '/../../../../cache/');
        $cache        = new FilesystemCachePool(new Filesystem($adapter));
        $loader       = new DeviceLoader($cache);
        $this->object = new NokiaFactory($loader);
    }

    /**
     * @dataProvider providerDetect
     *
     * @param string $agent
     * @param string $deviceName
     * @param string $marketingName
     * @param string $manufacturer
     * @param string $brand
     * @param string $deviceType
     * @param bool   $dualOrientation
     * @param string $pointingMethod
     */
    public function testDetect($agent, $deviceName, $marketingName, $manufacturer, $brand, $deviceType, $dualOrientation, $pointingMethod)
    {
        $s = new Stringy($agent);

        /** @var \UaResult\Device\DeviceInterface $result */
        list($result) = $this->object->detect($agent, $s);

        self::assertInstanceOf('\UaResult\Device\DeviceInterface', $result);

        self::assertSame(
            $deviceName,
            $result->getDeviceName(),
            'Expected device name to be "' . $deviceName . '" (was "' . $result->getDeviceName() . '")'
        );
        self::assertSame(
            $marketingName,
            $result->getMarketingName(),
            'Expected marketing name to be "' . $marketingName . '" (was "' . $result->getMarketingName() . '")'
        );
        self::assertSame(
            $manufacturer,
            $result->getManufacturer()->getName(),
            'Expected manufacturer name to be "' . $manufacturer . '" (was "' . $result->getManufacturer()->getName() . '")'
        );
        self::assertSame(
            $brand,
            $result->getBrand()->getBrandName(),
            'Expected brand name to be "' . $brand . '" (was "' . $result->getBrand()->getBrandName() . '")'
        );
        self::assertSame(
            $deviceType,
            $result->getType()->getName(),
            'Expected device type to be "' . $deviceType . '" (was "' . $result->getType()->getName() . '")'
        );
        self::assertSame(
            $dualOrientation,
            $result->getDualOrientation(),
            'Expected dual orientation to be "' . $dualOrientation . '" (was "' . $result->getDualOrientation() . '")'
        );
        self::assertSame(
            $pointingMethod,
            $result->getPointingMethod(),
            'Expected pointing method to be "' . $pointingMethod . '" (was "' . $result->getPointingMethod() . '")'
        );
    }

    /**
     * @return array[]
     */
    public function providerDetect()
    {
        return [
            [
                'this is a fake ua to trigger the fallback',
                'general Nokia Device',
                'general Nokia Device',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; NokiaC2-03/06.96; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/5.0.0.0.31',
                'C2-03',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia205/2.0 (03.19) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia205) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '205',
                'Asha 205',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia311/5.0 (03.81) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia311) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '311',
                'Asha 311',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-01/5.0 (08.71) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaX2-01) U2/1.0.0 UCBrowser/9.4.1.377 U2/1.0.0 Mobile',
                'X2-01',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia110/2.0 (03.47) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia110) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '110',
                '110',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'NokiaC2-03/2.0 (07.63) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaC2-03) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                'C2-03',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia206/2.0 (04.52) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia206) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '206',
                'Asha 206',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia200/2.0 (12.04) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia200) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '200',
                'Asha 200',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-02/2.0 (11.57) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaX2-02) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                'X2-02',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia308/2.0 (05.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia308) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '308',
                'Asha 308',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia305/2.0 (07.42) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia305) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '305',
                'Asha 305',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'NokiaC1-01/2.0 (03.35) Profile/MIDP-2.1 Configuration/CLDC-1.1 nokiac1-01/UC Browser7.6.1.82/69/351 UNTRUSTED/1.0',
                'C1-01',
                'C1',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 Nokia500/111.021.0028; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.1.4 Mobile Safari/535.1 3gpp-gba',
                '500',
                'Asha 500',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series30Plus; Nokia220/10.03.11; Profile/Series30Plus Configuration/Series30Plus) Gecko/20100401 S40OviBrowser/3.8.1.0.5',
                '220',
                'Asha 220',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Lumia 650',
                'Lumia 650',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 535) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Lumia 535',
                'Lumia 535',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; Lumia 640 LTE) like Gecko',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 540 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Lumia 540',
                'Lumia 540',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Java; U; MIDP-2.0; Nokia203/20.37) U2/1.0.0 UCBrowser/8.7.0.218 U2/1.0.0 Mobile',
                '203',
                'Asha 203',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6120c/3.83; Profile/MIDP-2.0 Configuration/CLDC-1.1 Google',
                '6120c',
                '6120 Classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-974_1080) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-974',
                'Lumia 635 International',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-1045_1012) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-1045',
                'Lumia 930 International',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Nokia6303classic/2.0 (08.90) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '6303 classic',
                '6303 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia6300/2.0 (05.50) Profile/MIDP-2.0 Configuration/CLDC-1.1',
                '6300',
                '6300',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-976_1166) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-976',
                'Lumia 630',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'NokiaC2-01/5.0 (11.20) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'C2-01',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (Series40; Nokia301.1/08.02; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.3.0.0.55',
                '301.1',
                'Asha 301',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'NokiaC3-01/5.0 (07.15) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'C3-01',
                'C3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia309/2.0 (08.22) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia309) U2/1.0.0 UCBrowser/9.4.1.377 U2/1.0.0 Mobile',
                '309',
                'Asha 309',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia6303iclassic/5.0 (06.61) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '6303i classic',
                '6303i classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia300/5.0 (07.57) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '300',
                'Asha 300',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'NokiaX3-00/5.0 (08.40) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X3-00',
                'X3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-846_eu_euro2_357) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-846',
                'Lumia 620',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-1038_1009) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-1038',
                'Lumia 735',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; Microsoft; RM-1089_1011) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-1089',
                'Lumia 535',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 650',
                'Lumia 650',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 1520) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 1520',
                'Lumia 1520',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 640 LTE Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 Edge/14.14332',
                'Lumia 950',
                'Lumia 950',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 950 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 950 XL',
                'Lumia 950 XL',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 640 XL Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 640 XL',
                'Lumia 640 XL',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 930) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/14.14295',
                'Lumia 930',
                'Lumia 930',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 550) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 550',
                'Lumia 550',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 920) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 920',
                'Lumia 920',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; 909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 1020',
                'Lumia 1020',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 1320) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 1320',
                'Lumia 1320',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 535 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10536',
                'Lumia 535',
                'Lumia 535',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 535) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10512',
                'Lumia 535',
                'Lumia 535',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 640 LTE) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10536',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 830) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Lumia 830',
                'Lumia 830',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; id336-2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Edge/12.10154',
                'Lumia 650',
                'Lumia 650',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.4.2; genm14 Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Mobile Safari/537.36 OPR/21.0.1437.75439',
                'XL2',
                'XL2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1113) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1075_1011)',
                'RM-1075',
                'Lumia 640 Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1067_1013)',
                'RM-1067',
                'Lumia 640 XL Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1090) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1090',
                'Lumia 535 Dual SIM',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1031_1004) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari',
                'RM-1031',
                'Lumia 532',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; RM-994_eu_poland_1155) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari',
                'RM-994',
                'Lumia 1320',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; NOKIA; RM-1010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393',
                'RM-1010',
                'Lumia 638',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.0.4; N1 Build/IMM76D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.114 Mobile Safari/537.36',
                'N1',
                'N1',
                'Nokia',
                'Nokia',
                'Tablet',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 7.0; Windows Phone OS 7.0; Trident/3.1; IEMobile/7.0; NOKIA; Lumia 720)',
                'Lumia 720',
                'Lumia 720',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 Nokia5800d-1/52.0.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.6.9 3gpp-gba',
                '5800 XpressMusic',
                'XpressMusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 521) like Gecko',
                'Lumia 521',
                'Lumia 521',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 Nokia5230/21.0.004; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.5.2 3gpp-gba',
                '5230',
                'Nuron',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaN8-00/013.016; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.8.10 3gpp-gba',
                'N8-00',
                'N8',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaN95_8GB/31.0.015; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N95',
                'N95',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 540 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393',
                'Lumia 540',
                'Lumia 540',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V3; ru; NOKIA6700s) U2/1.0.0 UCBrowser/9.0.1.317 U2/1.0.0 Mobile',
                '6700s',
                '6700 slide',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'Lumia 520',
                'Lumia 520',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; NOKIA; Lumia 735) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14915',
                'Lumia 735',
                'Lumia 735',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 635) like Gecko',
                'Lumia 635',
                'Lumia 635',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 710)',
                'Lumia 710',
                'Lumia 710',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 610)',
                'Lumia 610',
                'Lumia 610',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Windows Phone Search (Windows Phone OS 7.10;NOKIA;Lumia 900;7.10;8862)',
                'Lumia 900',
                'Lumia 900',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; 909)',
                'Lumia 1020',
                'Lumia 1020',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 630) like Gecko',
                'Lumia 630',
                'Lumia 630',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 510)',
                'Lumia 510',
                'Lumia 510',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 925) like Gecko',
                'Lumia 925',
                'Lumia 925',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11;IEMobile/11.0; NOKIA; Lumia 928) like Gecko',
                'Lumia 928',
                'Lumia 928',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 620) like Gecko',
                'Lumia 620',
                'Lumia 620',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 820) like Gecko',
                'Lumia 820',
                'Lumia 820',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 625) like Gecko',
                'Lumia 625',
                'Lumia 625',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 530 Dual SIM) like Gecko',
                'Lumia 530',
                'Lumia 530',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; RM-997) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-997',
                'Lumia 526',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Java; U; MIDP-2.0; ru; nokiaasha500dualsim) U2/1.0.0 UCBrowser/9.2.0.311 U2/1.0.0 Mobile UNTRUSTED/1.0',
                '500',
                'Asha 500',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Nokia210/2.0 (06.09) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia210) U2/1.0.0 UCBrowser/9.4.1.377 U2/1.0.0 Mobile',
                '210',
                'Asha 210',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia200/2.0 (11.95) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia200) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '200',
                'Asha 200',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile: Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Nokia; Lumia 730 Dual Sim',
                'Lumia 730',
                'Lumia 730',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; RM-976_1166)',
                'RM-976',
                'Lumia 630',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; RM-1045_1012)',
                'RM-1045',
                'Lumia 930 International',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; id336-2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Edge/12.10154',
                'Lumia 650',
                'Lumia 650',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; Lumia 640 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1075',
                'Lumia 640 Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; Lumia 435) like Gecko',
                'Lumia 435',
                'Lumia 435',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 800)',
                'Lumia 800',
                'Lumia 800',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Nokia 925) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'Lumia 925',
                'Lumia 925',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'NokiaN70-1/2.0539.1.2 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1',
                'N70',
                'N70',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.1.2; Nokia_XL Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Mobile Safari/537.36 OPR/36.2.2126.102826',
                'XL',
                'XL',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'NokiaX3-02/5.0 (05.60) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X3-02',
                'X3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaC6-01/011.010; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.7.2 3gpp-gba',
                'C6-01',
                'C6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Nokia6700c-1/2.0 (07.60) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '6700 classic',
                '6700 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'NokiaN82/GoBrowser/1.6.86',
                'N82',
                'N82',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaC5-00/071.005; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.26 Mobile Safari/533.4 3gpp-gba',
                'C5-00',
                'C5',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; de-DE; NOKIA; RM-978_1034) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-978',
                'Lumia 630 Dual SIM',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaC6-00/40.0.021; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.25 3gpp-gba',
                'C6-00',
                'C6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaC6-01/40.0.021; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.25 3gpp-gba',
                'C6-01',
                'C6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE71-1/400.21.013; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E71-1',
                'E71',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE71/400.21.013; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E71',
                'E71',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia501) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '501',
                '501',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia7230/5.0 (06.90) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '7230',
                '7230',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaX6-00/40.0.002; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.33 Mobile Safari/533.4 3gpp-gba',
                'X6-00',
                'X6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-00/5.0 (04.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X2-00',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-01/5.0 (04.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X2-01',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-02/5.0 (04.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X2-02',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-05/5.0 (04.80) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'X2-05',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1074) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1074',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1072) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1072',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1073) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1073',
                'Lumia 640 LTE (AT&T)',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1076) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1076',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1077) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1077',
                'Lumia 640 Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1062)',
                'RM-1062',
                'Lumia 640 XL LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1063)',
                'RM-1063',
                'Lumia 640 XL LTE (AT&T)',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1064)',
                'RM-1064',
                'Lumia 640 XL LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1065)',
                'RM-1065',
                'Lumia 640 XL Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1066)',
                'RM-1066',
                'Lumia 640 XL LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; en-US; NOKIA; RM-914_im_mea3_394) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-914',
                'Lumia 520',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 640 Dual SIM) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'RM-1075',
                'Lumia 640 Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaN81-1/10.0.026 Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N81',
                'N81',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaN85-1/10.034; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N85',
                'N85',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaN8-00/111.040.1511; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.1.4 Mobile Safari/535.1 3gpp-gba',
                'N8-00',
                'N8',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'NokiaN90-1/3.0545.5.1 Series60/2.8 Profile/MIDP-2.0 Configuration/CLDC-1.1 (en-US; rv:9.3.3) Clecko/20141026 Classilla/CFM',
                'N90',
                'N90 DUAL CORE2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'joystick',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaN96-1/3.00; Profile/MIDP-2.1 Configuration/CLDC-1.1;) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N96',
                'N96',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaN97-4/12.0.110; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/525 (KHTML, like Gecko) BrowserNG/7.1.4',
                'N97',
                'N97',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (MeeGo; NokiaN9) AppleWebKit/534.13 (KHTML, like Gecko) NokiaBrowser/8.5.0 Mobile Safari/534.13',
                'N9',
                'N9',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaN78-2/1.00 Profile/MIDP-2.0 Configuration/CLDC-1.1) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N78',
                'N78',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaN79-1/10.034; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'N79',
                'N79',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.3; NokiaX2DS Build/JLS36C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.114 Mobile Safari/537.36',
                'X2DS',
                'X2 Dual SIM',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX2-02/2.0 (12.04) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaX2-02) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile UNTRUSTED/1.0',
                'X2-02',
                'X2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaX3-02/5.0 (07.51) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaX3-02) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                'X3-02',
                'X3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaX6-00/10.5.089; Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/525 (KHTML, like Gecko) BrowserNG/7.2.3.1',
                'X6-00',
                'X6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaX7-00/111.030.0609; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'X7-00',
                'X7',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaX7-01/111.030.0609; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'X7',
                'X7',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaE7-00/111.030.0609; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'E7-00',
                'E7',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaE72-1/073.001; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.26 Mobile Safari/533.4 3gpp-gba',
                'E72',
                'E72',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 NokiaE75-1/100.48.78 Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E75',
                'E75',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaE7/111.030.0609; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'E7',
                'E7',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaE6-00/111.130.0625; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'E6-00',
                'E6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 NokiaE6/111.130.0625; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.2.6 Mobile Safari/533.4 3gpp-gba',
                'E6',
                'E6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE63-2/410.21.010; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E63',
                'E63',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE66-1/102.07.81; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E66',
                'E66',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V3; en-US; NOKIAE5-00u) U2/1.0.0 UCBrowser/9.2.0.336 U2/1.0.0 Mobile',
                'E5-00',
                'Mystic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V3; en-US; NOKIAE5) U2/1.0.0 UCBrowser/9.2.0.336 U2/1.0.0 Mobile',
                'E5',
                'E5',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.1; U; [de]; NokiaE50-1/06.41.3.0 Series60/3.0) AppleWebKit/413 (KHTML, like Gecko) Safari/413,gzip(gfe),gzip(gfe)',
                'E50',
                'E50',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE51-2/151.34.20; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E51',
                'E51',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaE52-1/052.003; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.6.2 3gpp-gba',
                'E52',
                'E52',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2 U Series60/3.1 NokiaE90-1/210.34.75 Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                'E90',
                'E90',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaC7-00/025.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.37 Mobile Safari/533.4 3gpp-gba',
                'C7-00',
                'Astound',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaC7/025.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.37 Mobile Safari/533.4 3gpp-gba',
                'C7',
                'C7',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaC6/011.010; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.7.2 3gpp-gba',
                'C6',
                'C6',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 NokiaC5-03/22.0.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.33 Mobile Safari/533.4 3gpp-gba',
                'C5-03',
                'C5',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V5; en-US; NokiaC5-05) U2/1.0.0 UCBrowser/9.2.0.336 U2/1.0.0 Mobile',
                'C5-05',
                'C5',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V5; en-US; NokiaC5) U2/1.0.0 UCBrowser/9.2.0.336 U2/1.0.0 Mobile',
                'C5',
                'C5',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaC3-00/5.0 (08.70) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'C3-00',
                'C3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'NokiaC3/5.0 (08.70) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                'C3',
                'C3',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; NokiaC2-05/08.79; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/4.0.0.0.45',
                'C2-05',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; NokiaC2-06/07.48; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/1.0.2.26.9',
                'C2-06',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; NokiaC2/07.48; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/1.0.2.26.9',
                'C2',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaC1-01/2.0 (03.35) Profile/MIDP-2.1 Configuration/CLDC-1.1 nokiac1-01/UC Browser7.6.1.82/69/351 UNTRUSTED/1.0',
                'C1-01',
                'C1',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaC1/2.0 (03.35) Profile/MIDP-2.1 Configuration/CLDC-1.1 nokiac1-01/UC Browser7.6.1.82/69/351 UNTRUSTED/1.0',
                'C1-01',
                'C1',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6610I/1.0 (3.10) Profile/MIDP-1.0 Configuration/CLDC-1.0 UP.Link/5.1.2.7 (Google WAP Proxy/1.0)',
                '6610I',
                '6610I',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 Nokia6220c-1/03.23; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                '6220 classic',
                '6220 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; U; Series60/3.2 Nokia6210Navigator/03.25; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                '6210',
                'Navigator',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6120c/3.83; Profile/MIDP-2.0 Configuration/CLDC-1.1',
                '6120c',
                '6120 Classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Symbian; U; S60 V5; en-US; Nokia5800 XpressMusic) U2/1.0.0 UCBrowser/9.2.0.336 U2/1.0.0 Mobile',
                '5800',
                'XpressMusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 Nokia5530c-2/32.0.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.6.9 3gpp-gba',
                '5530 classic',
                '5530 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 Nokia5530/32.0.007; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.6.9 3gpp-gba',
                '5530 classic',
                '5530 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 Nokia5250/10.0.021; Profile/MIDP-2.0 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413',
                '5250',
                '5250',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; U; Series60/5.0 Nokia5233-2G/10.0.055; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/413 (KHTML, like Gecko) Safari/413 Schemas used: uaprof, MMS, streaming',
                '5233',
                '5233',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5130c-2/2.0 (07.91) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia5130c-2) U2/1.0.0 UCBrowser/9.3.0.326 U2/1.0.0 Mobile',
                '5130c-2',
                '5130c-2 Xpressmusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5130c/2.0 (07.91) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia5130c-2) U2/1.0.0 UCBrowser/9.3.0.326 U2/1.0.0 Mobile',
                '5130c-2',
                '5130c-2 Xpressmusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia301.1/08.02; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/5.0.0.0.31',
                '301.1',
                'Asha 301',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia2320c-2b/2.0(ATT.11.10) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2320c',
                '2320 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.5 Nokia808PureView/113.010.1508; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.2.21 Mobile Safari/535.1 3gpp-gba',
                '808 PureView',
                '808 PureView',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 Nokia701/111.010.1009; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.4.1.12 Mobile Safari/533.4 3gpp-gba',
                '701',
                '701',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.5 Nokia700/113.010.1506; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.2.21 Mobile Safari/535.1 3gpp-gba',
                '700',
                '700',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.5 Nokia603/113.010.1506; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.2.21 Mobile Safari/535.1 3gpp-gba',
                '603',
                '603',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia515/10.34; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.3.0.0.55',
                '515',
                '515',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia306/03.63; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/3.9.0.0.22',
                '306',
                'Asha 306',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia302/14.26; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/1.0.2.26.11',
                '302',
                'Asha 302',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'joystick',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia201/11.95; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.2.0.0.36',
                '201',
                'Asha 201',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia112/03.26; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/5.0.0.0.31',
                '112',
                '112',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (Series40; Nokia109/04.10; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/4.0.0.0.45',
                '109',
                '109',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; Lumia 640 LTE) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; Lumia 640 LTE)',
                'RM-1113',
                'Lumia 640 LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaN86-1/30.009;; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.1.19424',
                'N86',
                'N86',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaN91-5/3.0 (06wk04) SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1',
                'N91',
                'N91',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                true,
                'joystick',
            ],
            [
                'NokiaE62-1/3.0 (2.0618.06.17); SymbianOS/9.1 Series60/3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1)',
                'E62',
                'E62',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 NokiaE55-1/033.002; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.1.5',
                'E55',
                'E55',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaC2-02/2.0 (06.96) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; NokiaC2-02) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                'C2-02',
                'C2',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'NokiaC1-02/2.0 (03.40) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                'C1',
                'C1',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 5.0; Series80/2.0 Nokia9500/5.22 Profile/MIDP-2.0 Configuration/CLDC-1.1)',
                '9500',
                '9500',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 ( Nokia7510Supernova/2.0 (03.80) Profile/MIDP-2.1 Configuration/CLDC-1.1) AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '7510',
                '7510',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 Nokia6730c-1/023.010; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.1.19424',
                '6730 classic',
                '6730 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 Nokia6720c/032.001; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.2.3.1',
                '6720 classic',
                '6720 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.3; Series60/3.2 Nokia6710s/021.013; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/525 (KHTML, like Gecko) Version/3.0 BrowserNG/7.1.13841',
                '6710 slide',
                '6710 slide',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6630/1.0 (6.03.40) SymbianOS/8.0 Series60/2.6 Profile/MIDP-2.0 Configuration/CLDC-1.1/UC Browser7.9.1.120/27/351/UCWEB',
                '6630',
                '6630',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6500s-1/2.0 (06.60) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 (Java; U; en-us; nokia6500s-1) UCBrowser8.2.0.132/70/355/UCWEB Mobile',
                '6500 slide',
                '6500 slide',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6500c/2.0 (04.84) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '6500 classic',
                '6500 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6131/2.0 (06.60) Profile/MIDP-2.0 Configuration/CLDC-1.1',
                '6131',
                '6131',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5310XpressMusic/2.0 (10.10) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '5310 XpressMusic',
                'XpressMusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (SymbianOS/9.4; Series60/5.0 Nokia5228/51.1.002; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.1.33 Mobile Safari/533.4 3gpp-gba',
                '5228',
                '5228',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5220XpressMusic/2.0 (04.00) Profile/MIDP-2.1 Configuration/CLDC-1.1 Novarra-Vision/8.0',
                '5220 XpressMusic',
                '5220 XpressMusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5130c-2/2.0 (07.95) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia5130c-2) U2/1.0.0 UCBrowser/9.4.1.377 U2/1.0.0 Mobile',
                '5130c-2',
                '5130c-2 Xpressmusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia3710fold/5.0 (04.30) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 AppleWebKit/420+ (KHTML, like Gecko) Safari/420+',
                '3710',
                '3710',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia301/09.04; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/5.5.0.0.27',
                '301',
                'Asha 301',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Nokia2760/2.0 (07.60) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2760',
                '2760',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2730c-1/2.0 (10.47) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia2730c-1) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile UNTRUSTED/1.0',
                '2730 classic',
                '2730 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2720a-2/2.0 (09.85) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2720a',
                '2720a',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2700c-2/2.0 (07.15) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2700 classic',
                '2700 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2630/2.0 (07.60) Profile/MIDP-2.1 Configuration/CLDC-1.1  UNTRUSTED/1.0',
                '2630',
                '2630',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2330c-2/2.0 (09.85) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2330 classic',
                '2330 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia2323c-2/2.0 (08.20) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '2323c',
                '2323 classic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia303/5.0 (14.76) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; es-LA; Nokia303) U2/1.0.0 UCBrowser/9.4.1.377 U2/1.0.0 Mobile',
                '303',
                'Asha 303',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Series40; Nokia113/03.09; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/3.2.0.0.6',
                '113',
                '113',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                null,
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; Lumia 640 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1075',
                'Lumia 640 Dual SIM LTE',
                'Microsoft Corporation',
                'Microsoft',
                'Mobile Phone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (X11; U; Linux armv7l; de-DE; rv:1.9.2.3pre) Gecko/20100723 Firefox/3.5 Maemo Browser 1.7.4.8 RX-51 N900',
                'N900',
                'N900',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia6555/2.0 (03.43) Profile/MIDP-2.1 Configuration/CLDC-1.1',
                '6555',
                '6555',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Nokia5130c-2/2.0 (07.95) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia5130c-2) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile',
                '5130c-2',
                '5130c-2 Xpressmusic',
                'Nokia',
                'Nokia',
                'Mobile Phone',
                false,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.1.2; Nokia_X Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.82 Mobile Safari/537.36 NokiaBrowser/1.2.0.12',
                'X',
                'X',
                'Nokia',
                'Nokia',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 8.10; en-IN; Microsoft; RM-1099_1005) U2/1.0.0 UCBrowser/4.2.1.541 U2/1.0.0 Mobile',
                'RM-1099',
                'Lumia 430 Dual SIM',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0.13333.0; U; pt-BR; Microsoft RM-1114_1000)',
                'RM-1114',
                'Lumia 435 Dual SIM DTV',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.1; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1092_1002)',
                'RM-1092',
                'Lumia 535 Dual SIM',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1141) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'RM-1141',
                'Lumia 540 Dual SIM',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone OS 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1127_15119)',
                'RM-1127',
                'Lumia 550',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 8.10.15148.0; U; pt-BR; Microsoft RM-1109_1002)',
                'RM-1109',
                'Lumia 640 Dual SIM DTV',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; RM-1154) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'RM-1154',
                'Lumia 650 Dual SIM',
                'Microsoft Corporation',
                'Microsoft',
                'Smartphone',
                true,
                'touchscreen',
            ],
        ];
    }
}
