<?php
/**
 * View für autoComplete-Funktion für die PLZ
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: ort.phtml 30 2011-01-06 21:58:02Z tmu $
 */

//$this->layout()->disableLayout();
?>
<ul class="Ort">
<?php foreach ($this->data as $ort) : ?>
<li class="Ort">
<a href="javascript:void(0);" onclick="return updateOrt('<?php echo $ort['name']; ?>');document.getElementById('email').focus();return false;">
<?php echo $ort['name']; ?>
</a>
</li>
<?php endforeach; ?>
</ul>