<?php
/**
 * View für autoComplete-Funktion für die PLZ
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: plz.phtml 30 2011-01-06 21:58:02Z tmu $
 */

//$this->layout()->disableLayout();
?>
<ul class="Plz">
<?php foreach ($this->data as $plz) : ?>
<li class="Plz" onclick="updatePlz('<?php echo $plz['id']; ?>');updateOrt('<?php echo $plz['name']; ?>');document.getElementById('email').focus();return false;"><?php echo $plz['id'] . ' ' . $plz['name']; ?></li>
<?php endforeach; ?>
</ul>