<?php

return [
    'browscap-issue-1011-A' => [
        'ua'         => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '47.0',
            'Platform_Name'           => 'MacOSX',
            'Platform_Version'        => '10.11.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'Macintosh',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Macintosh',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '47.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-1011-B' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '47.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '8.1.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '47.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-1011-C' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '47.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '7.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '47.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-1011-D' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '47.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '10.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '47.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
