<?php

return [
    'browscap-issue-648-A' => [
        'ua'         => 'AppleCoreMedia/1.0.0.12F69 (Apple TV; U; CPU OS 8_3 like Mac OS X; en_us)',
        'properties' => [
            'Browser_Name'            => 'AppleCoreMedia',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Name'           => 'ATV OS X',
            'Platform_Version'        => '8.3',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'AppleTV',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'AppleTV',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-648-B' => [
        'ua'         => 'Mail/53 CFNetwork/711.2.23 Darwin/14.0.0',
        'properties' => [
            'Browser_Name'            => 'Apple Mail',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '8.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-648-C' => [
        'ua'         => 'Safari/10600.3.18 CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)',
        'properties' => [
            'Browser_Name'            => 'Safari',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '8.0',
            'Platform_Name'           => 'MacOSX',
            'Platform_Version'        => '10.10',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'Macintosh',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Macintosh',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
