<?php

return [
    'browscap-issue-341-A' => [
        'ua'         => 'Mozilla/5.0 (Linux; GoogleTV 3.2; NSZ-GS7/GX70 Build/MASTER) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.77 Safari/534.24',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.0',
            'Platform_Name'           => 'Android for GoogleTV',
            'Platform_Version'        => '3.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'NSZ-GS7/GX70',
            'Device_Maker'            => 'Sony',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'NSZ-GS7/GX70',
            'Device_Brand_Name'       => 'Sony',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-341-B' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.77 Large Screen Safari/534.24 GoogleTV/092754',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.0',
            'Platform_Name'           => 'Linux',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Google TV',
            'Device_Maker'            => 'Sony',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Google TV',
            'Device_Brand_Name'       => 'Sony',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
