<?php

return [
    'browscap-issue-919-A' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 OPR/36.0.2130.32',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '36.0',
            'Platform_Name'           => 'Win8.1',
            'Platform_Version'        => '6.3',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'browscap-issue-919-B' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.46',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '36.0',
            'Platform_Name'           => 'Linux',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
