<?php

return [
    'browscap-issue-526-A' => [
        'ua'         => 'bot-pge.chlooe.com/1.0.0 (+http://www.chlooe.com/)',
        'properties' => [
            'Browser_Name'            => 'chlooe Bot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'AsiaWS network',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-526-B' => [
        'ua'         => 'seebot/2.0 (+http://www.seegnify.com/bot)',
        'properties' => [
            'Browser_Name'            => 'SeeBot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Seegnify',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
