<?php

return [
    'browscap-issue-650-A' => [
        'ua'         => 'Opera/9.80 (Linux armv7l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;Vendor/THOM;SW-Version/V8-MT51F01-LF1V307;Cnt/DEU;Lan/bul) Presto/2.12.362 Version/12.11',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '12.11',
            'Platform_Name'           => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'LF1V307',
            'Device_Maker'            => 'Thomson',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'LF1V307',
            'Device_Brand_Name'       => 'Thomson',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => '2.12',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
    'browscap-issue-650-B' => [
        'ua'         => 'Opera/9.80 (Linux armv7l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;Vendor/THOMSON;SW-Version/V8-MT51F01-LF1V325;Cnt/HRV;Lan/swe; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0) Presto/2.12.362 Version/12.11',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '12.11',
            'Platform_Name'           => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'LF1V325',
            'Device_Maker'            => 'Thomson',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'LF1V325',
            'Device_Brand_Name'       => 'Thomson',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => '2.12',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
    'browscap-issue-650-C' => [
        'ua'         => 'Opera/9.80 (Linux armv6l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;THOM LF1V373; en) Presto/2.10.250 Version/11.60',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.60',
            'Platform_Name'           => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'LF1V373',
            'Device_Maker'            => 'Thomson',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'LF1V373',
            'Device_Brand_Name'       => 'Thomson',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => '2.10',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
    'browscap-issue-650-D' => [
        'ua'         => 'Opera/9.80 (Linux armv6l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;THOMSON LF1V394; en) Presto/2.10.250 Version/11.60',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.60',
            'Platform_Name'           => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'LF1V394',
            'Device_Maker'            => 'Thomson',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'LF1V394',
            'Device_Brand_Name'       => 'Thomson',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => '2.10',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
    'browscap-issue-650-E' => [
        'ua'         => 'Opera/9.80 (Linux armv6l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;THOMSON LF1V401; en) Presto/2.10.250 Version/11.60',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.60',
            'Platform_Name'           => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'LF1V401',
            'Device_Maker'            => 'Thomson',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'LF1V401',
            'Device_Brand_Name'       => 'Thomson',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => '2.10',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
];
