<?php

return [
    'browscap-issue-873-A' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Android 5.1; en-US; XT1021 Build/LPC23.13-34.8) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.7.5.658 U3/0.8.0 Mobile Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.7',
            'Platform_Name'           => 'Android',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Moto E',
            'Device_Maker'            => 'Motorola',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'XT1021',
            'Device_Brand_Name'       => 'Motorola',
            'RenderingEngine_Name'    => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'UCWeb Inc.',
        ],
    ],
    'browscap-issue-873-B' => [
        'ua'         => 'Mozilla/5.0 (Android 5.1; Mobile; rv:43.0) Gecko/43.0 Firefox/43.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '43.0',
            'Platform_Name'           => 'Android',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Phone',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Phone',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '43.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
