<?php

return [
    'browscap-issue-578-A' => [
        'ua'         => 'check_http/v1.4.16 (nagios-plugins 1.4.16)',
        'properties' => [
            'Browser_Name'            => 'Nagios',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Nagios Enterprises, LLC.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.4',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-578-B' => [
        'ua'         => 'check_http/v2.0 (nagios-plugins 2.0)',
        'properties' => [
            'Browser_Name'            => 'Nagios',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Nagios Enterprises, LLC.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
