<?php

return [
    'browscap-issue-113-F' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Win64; x64; Trident/6.0)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.0',
            'Platform_Name'           => 'Win8',
            'Platform_Version'        => '6.2',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '6.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-113-E' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/6.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'IE 7.0 Compatibility Mode',
            'Browser_Version'         => '10.0',
            'Platform_Name'           => 'Win8',
            'Platform_Version'        => '6.2',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '6.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-113-D' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Win64; x64; Trident/5.0)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '9.0',
            'Platform_Name'           => 'Win8',
            'Platform_Version'        => '6.2',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '5.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-113-C' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '7.0',
            'Platform_Name'           => 'Win8',
            'Platform_Version'        => '6.2',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-113-B' => [
        'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MAFSJS)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'IE 7.0 Compatibility Mode',
            'Browser_Version'         => '11.0',
            'Platform_Name'           => 'Win7',
            'Platform_Version'        => '6.1',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-113-A' => [
        'ua'         => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/6.0)',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'IE 9.0 Compatibility Mode',
            'Browser_Version'         => '10.0',
            'Platform_Name'           => 'Win7',
            'Platform_Version'        => '6.1',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '6.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
];
