<?php

return [
    'browscap-issue-750-A' => [
        'ua'         => 'TestApp/1.0 CFNetwork/758.0.2 Darwin/15.0.0',
        'properties' => [
            'Browser_Name'            => 'CFNetwork',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '9.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-750-B' => [
        'ua'         => 'AtomicBrowser/5.8.0 CFNetwork/485.13.9 Darwin/11.0.0',
        'properties' => [
            'Browser_Name'            => 'Atomic Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Richard Trautvetter',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '5.8',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '4.3',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
