<?php

return [
    'browscap-issue-038-b' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/30.0.1599.16 Mobile/11A501 Safari/8536.25',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '30.0',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '7.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-038-a' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) CriOS/28.0.1500.16 Mobile/11A4449d Safari/8536.25',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '28.0',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '7.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
