<?php

return [
    'browscap-issue-920-A' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 UBrowser/5.6.10764.1203 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '5.6',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '6.1',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'browscap-issue-920-B' => [
        'ua'         => 'Mozilla/5.0 (iPad; U; CPU OS 5_1 like Mac OS X) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B367 Safari/531.21.10 UCBrowser/3.4.3.532',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.4',
            'Platform_Name'           => 'iOS',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'iPad',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPad',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-920-C' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.2.2; en-US; IdealTab 10 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.8.730 U3/0.8.0 Mobile Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.8',
            'Platform_Name'           => 'Android',
            'Platform_Version'        => '4.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Device_Name'             => 'IdealTab 10',
            'Device_Maker'            => 'Lenovo',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'IdealTab 10',
            'Device_Brand_Name'       => 'Lenovo',
            'RenderingEngine_Name'    => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'UCWeb Inc.',
        ],
    ],
];
