<?php

return [
    'browscap-issue-983-A' => [
        'ua'         => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36 Vivaldi/1.1.453.52',
        'properties' => [
            'Browser_Name'            => 'Vivaldi',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Vivaldi Technologies',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.1',
            'Platform_Name'           => 'MacOSX',
            'Platform_Version'        => '10.11.4',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Device_Name'             => 'Macintosh',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Macintosh',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'browscap-issue-983-B' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36 Vivaldi/1.0.321.3',
        'properties' => [
            'Browser_Name'            => 'Vivaldi',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Vivaldi Technologies',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Name'           => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'browscap-issue-983-C' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.88 Safari/537.36 Vivaldi/1.0.380.2',
        'properties' => [
            'Browser_Name'            => 'Vivaldi',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Vivaldi Technologies',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Name'           => 'Win10',
            'Platform_Version'        => '10.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
