<?php

return [
    'browscap-issue-269-A' => [
        'ua'         => 'Slackbot-LinkExpanding (+https://api.slack.com/robots)',
        'properties' => [
            'Browser_Name'            => 'Slackbot-Link-Expanding',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'slack.com',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => true,
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-269-B' => [
        'ua'         => 'Slackbot (+https://api.slack.com/robots)',
        'properties' => [
            'Browser_Name'            => 'Slackbot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'slack.com',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => true,
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
