<?php

return [
    'browscap-issue-337-A' => [
        'ua' => 'Mozilla/5.0 (Linux; U; Android 4.2.2; de-de; FP1 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
        'properties' => [
            'Browser' => 'Android',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '4.0',
            'Platform' => 'Android',
            'Platform_Version' => '4.2',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'FP1',
            'Device_Maker' => 'Fairphone',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'FP1',
            'Device_Brand_Name' => 'Fairphone',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
    'browscap-issue-337-B' => [
        'ua' => 'Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; FP1 Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 UCBrowser/9.8.0.435 U3/0.8.0 Mobile Safari/533.1',
        'properties' => [
            'Browser' => 'UC Browser',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'UCWeb Inc.',
            'Browser_Modus' => 'unknown',
            'Version' => '9.8',
            'Platform' => 'Android',
            'Platform_Version' => '4.2',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'FP1',
            'Device_Maker' => 'Fairphone',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'FP1',
            'Device_Brand_Name' => 'Fairphone',
            'RenderingEngine_Name' => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'UCWeb Inc.',
        ],
    ],
    'browscap-issue-337-C' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 4.2.2; FP1 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.141 Mobile Safari/537.36',
        'properties' => [
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '35.0',
            'Platform' => 'Android',
            'Platform_Version' => '4.2',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'FP1',
            'Device_Maker' => 'Fairphone',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'FP1',
            'Device_Brand_Name' => 'Fairphone',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
];
