<?php

return [
    'browscap-issue-966-A' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36',
        'properties' => [
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '41.0',
            'Platform' => 'Android',
            'Platform_Version' => '6.0',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Nexus 5X',
            'Device_Maker' => 'LG',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Nexus 5X',
            'Device_Brand_Name' => 'Google',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
    'browscap-issue-966-B' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6P Build/MHC19Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36',
        'properties' => [
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '50.0',
            'Platform' => 'Android',
            'Platform_Version' => '6.0',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Nexus 6P',
            'Device_Maker' => 'Huawei',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Nexus 6P',
            'Device_Brand_Name' => 'Google',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
];
