<?php

return [
    'browscap-issue-493-A' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 4.4.2; SM-P600 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Safari/537.36',
        'properties' => [
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '19.0',
            'Platform' => 'Android',
            'Platform_Version' => '4.4',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => true,
            'Crawler' => false,
            'Device_Name' => 'Galaxy Note 10.1 2014 Edition Wi-Fi',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-P600',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
    'browscap-issue-493-B' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 4.3; de-de; SAMSUNG SM-P600 Build/JSS15J) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Safari/537.36',
        'properties' => [
            'Browser' => 'Android WebView',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '1.5',
            'Platform' => 'Android',
            'Platform_Version' => '4.3',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => true,
            'Crawler' => false,
            'Device_Name' => 'Galaxy Note 10.1 2014 Edition Wi-Fi',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-P600',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
    'browscap-issue-493-C' => [
        'ua' => 'Mozilla/5.0 (Linux; Android 4.3; SM-P600 Build/JSS15J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.141 Safari/537.36',
        'properties' => [
            'Browser' => 'Chrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Google Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '35.0',
            'Platform' => 'Android',
            'Platform_Version' => '4.3',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => true,
            'Crawler' => false,
            'Device_Name' => 'Galaxy Note 10.1 2014 Edition Wi-Fi',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Tablet',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SM-P600',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
];
