<?php

return [
    'browscap-issue-562-A' => [
        'ua'         => 'Cyberduck/4.6.4 (16610) (Windows XP/5.1) (x86)',
        'properties' => [
            'Browser_Name'            => 'Cyberduck',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'iterate GmbH',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.6',
            'Platform_Name'           => 'WinXP',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-562-B' => [
        'ua'         => 'Lynx/2.8.5rel.1 libwww-FM/2.15FC SSL-MM/1.4.1c OpenSSL/0.9.7e-dev',
        'properties' => [
            'Browser_Name'            => 'Lynx',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Thomas Dickey',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.8',
            'Platform_Name'           => 'Linux',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'general Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
