<?php

return [
    'browscap-issue-176-A' => [
        'ua'         => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:27.0) Gecko/20100101 Firefox/27.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '27.0',
            'Platform_Name'           => 'Ubuntu',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Canonical Foundation',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '27.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-176-B' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.1; rv:27.0) Gecko/20100101 Firefox/27.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '27.0',
            'Platform_Name'           => 'Win7',
            'Platform_Version'        => '6.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '27.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
