<?php

return [
    'browscap-issue-114-D' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1200.0 Iron/21.0.1200.0 Safari/537.1',
        'properties' => [
            'Browser_Name'            => 'Iron',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'SRWare',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '21.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-114-C' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/534.30 (KHTML, like Gecko) Iron/12.0.750.0 Chrome/12.0.750.0 Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'Iron',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'SRWare',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '12.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-114-B' => [
        'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.4) Gecko/20091016 Firefox/3.5.4 (.NET CLR 3.5.30729)',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.5',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '1.9.1',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-114-A' => [
        'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7 (.NET CLR 3.5.30729)',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '5.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Win16'                   => false,
            'Win32'                   => true,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '1.9.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
