<?php

return [
    'browscap-issue-315-A' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36 Nichrome/self/33',
        'properties' => [
            'Browser' => 'Nichrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'rambler.ru',
            'Browser_Modus' => 'unknown',
            'Version' => '33.0',
            'Platform' => 'Win7',
            'Platform_Version' => '6.1',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Microsoft Corporation',
            'Win16' => false,
            'Win32' => true,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'Various',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
    'browscap-issue-315-B' => [
        'ua' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36 Nichrome/self/33',
        'properties' => [
            'Browser' => 'Nichrome',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'rambler.ru',
            'Browser_Modus' => 'unknown',
            'Version' => '33.0',
            'Platform' => 'Win8.1',
            'Platform_Version' => '6.3',
            'Platform_Bits' => 64,
            'Platform_Maker' => 'Microsoft Corporation',
            'Win16' => false,
            'Win32' => false,
            'Win64' => true,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Windows Desktop',
            'Device_Maker' => 'Various',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Windows Desktop',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Google Inc',
        ],
    ],
];
