<?php

return [
    'browscap-issue-968-A' => [
        'ua'         => 'HbbTV/1.1.1 (;;;;;) Maple_2011',
        'properties' => [
            'Browser'                 => 'Samsung',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Samsung',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '0.0',
            'Platform'                => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Smart TV',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'Smart TV',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-968-B' => [
        'ua'         => 'HbbTV/1.1.1 (;Panasonic;VIERA 2011;1.805;0071-7702 2000-0000;)',
        'properties' => [
            'Browser'                 => 'SmartViera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Panasonic',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '0.0',
            'Platform'                => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Viera TV',
            'Device_Maker'            => 'Panasonic',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'Viera TV',
            'Device_Brand_Name'       => 'Panasonic',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-968-C' => [
        'ua'         => 'HbbTV/1.1.1 (;Samsung;SmartTV2012;;;) WebKit',
        'properties' => [
            'Browser'                 => 'Samsung',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Samsung',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '0.0',
            'Platform'                => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Smart TV',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'Smart TV',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
