<?php

return [
    'browscap-issue-526-A' => [
        'ua' => 'bot-pge.chlooe.com/1.0.0 (+http://www.chlooe.com/)',
        'properties' => [
            'Browser' => 'chlooe Bot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 0,
            'Browser_Maker' => 'AsiaWS network',
            'Browser_Modus' => 'unknown',
            'Version' => '1.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 0,
            'Platform_Maker' => 'unknown',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
    ],
    'browscap-issue-526-B' => [
        'ua' => 'seebot/2.0 (+http://www.seegnify.com/bot)',
        'properties' => [
            'Browser' => 'SeeBot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 0,
            'Browser_Maker' => 'Seegnify',
            'Browser_Modus' => 'unknown',
            'Version' => '2.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 0,
            'Platform_Maker' => 'unknown',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
    ],
];
