<?php

return [
    'browscap-issue-860-A' => [
        'ua' => 'SoundCloud/3.0.0 build 2547; iPhone/iPhone OS/7.1.1',
        'properties' => [
            'Browser' => 'SoundCloud App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'SoundCloud Limited',
            'Browser_Modus' => 'unknown',
            'Version' => '3.0',
            'Platform' => 'iOS',
            'Platform_Version' => '7.1',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Apple Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'iPhone',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'iPhone',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
    'browscap-issue-860-B' => [
        'ua' => 'SoundCloud-Android/14.08.21-17 (Android 4.4.2; samsung SAMSUNG-SGH-I337)',
        'properties' => [
            'Browser' => 'SoundCloud App',
            'Browser_Type' => 'Application',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'SoundCloud Limited',
            'Browser_Modus' => 'unknown',
            'Version' => '14.08',
            'Platform' => 'Android',
            'Platform_Version' => '4.4',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Google Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Galaxy S4 (AT&T)',
            'Device_Maker' => 'Samsung',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'SGH-I337',
            'Device_Brand_Name' => 'Samsung',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
];
