<?php

return [
    'browscap-issue-841-A' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) Sprint:MotoQ9c',
        'properties' => [
            'Browser' => 'IEMobile',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '7.11',
            'Platform' => 'WinCE',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Microsoft Corporation',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Q9c',
            'Device_Maker' => 'Motorola',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'Q9c',
            'Device_Brand_Name' => 'Motorola',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => '3.1',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-841-B' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 8.12; MSIEMobile 6.0) T-Mobile_LEO',
        'properties' => [
            'Browser' => 'IEMobile',
            'Browser_Type' => 'Browser',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Microsoft Corporation',
            'Browser_Modus' => 'unknown',
            'Version' => '8.12',
            'Platform' => 'WinCE',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Microsoft Corporation',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => true,
            'isTablet' => false,
            'Crawler' => false,
            'Device_Name' => 'Leo',
            'Device_Maker' => 'HTC',
            'Device_Type' => 'Mobile Phone',
            'Device_Pointing_Method' => 'touchscreen',
            'Device_Code_Name' => 'Leo',
            'Device_Brand_Name' => 'T-Mobile',
            'RenderingEngine_Name' => 'Trident',
            'RenderingEngine_Version' => '3.1',
            'RenderingEngine_Maker' => 'Microsoft Corporation',
        ],
    ],
];
