<?php

return [
    'browscap-issue-803-A' => [
        'ua'         => 'Instagram 3.4.1 (iPhone5,1; iPhone OS 6.0.2; en_US; en) AppleWebKit/420+',
        'properties' => [
            'Browser'                 => 'Instagram App',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Facebook',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '3.4',
            'Platform'                => 'iOS',
            'Platform_Version'        => '6.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-803-B' => [
        'ua'         => 'Instagram 7.8.0 (iPhone5,3; iPhone OS 9_0_2; en_US; en-US; scale=2.00; 640x1136) AppleWebKit/420+',
        'properties' => [
            'Browser'                 => 'Instagram App',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Facebook',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '7.8',
            'Platform'                => 'iOS',
            'Platform_Version'        => '9.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-803-C' => [
        'ua'         => 'Mozilla/5.0 (Android 4.1.2; Tablet; rv:41.0) Gecko/41.0 Firefox/41.0',
        'properties' => [
            'Browser'                 => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '41.0',
            'Platform'                => 'Android',
            'Platform_Version'        => '4.1',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => true,
            'Crawler'                 => false,
            'Device_Name'             => 'general Tablet',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Tablet',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '41.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
