<?php

return [
    'browscap-issue-358-A' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; it-it; SAMSUNG SM-N9005 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Mobile Safari/537.36',
        'properties' => [
            'Browser'                 => 'Android WebView',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '1.5',
            'Platform'                => 'Android',
            'Platform_Version'        => '4.4',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Galaxy Note 3 LTE',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'SM-N9005',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'browscap-issue-358-B' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; SM-N9005 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.141 Mobile Safari/537.36',
        'properties' => [
            'Browser'                 => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '35.0',
            'Platform'                => 'Android',
            'Platform_Version'        => '4.4',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Galaxy Note 3 LTE',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'SM-N9005',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
