<?php

return [
    'browscap-issue-826-A' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)',
        'properties' => [
            'Browser' => 'Applebot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '0.1',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Apple Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
    'browscap-issue-826-B' => [
        'ua' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1)',
        'properties' => [
            'Browser' => 'Applebot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 32,
            'Browser_Maker' => 'Apple Inc',
            'Browser_Modus' => 'unknown',
            'Version' => '0.1',
            'Platform' => 'MacOSX',
            'Platform_Version' => '10',
            'Platform_Bits' => 32,
            'Platform_Maker' => 'Apple Inc',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'Macintosh',
            'Device_Maker' => 'Apple Inc',
            'Device_Type' => 'Desktop',
            'Device_Pointing_Method' => 'mouse',
            'Device_Code_Name' => 'Macintosh',
            'Device_Brand_Name' => 'Apple',
            'RenderingEngine_Name' => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'Apple Inc',
        ],
    ],
];
