<?php

return [
    'browscap-issue-046-a' => [
        'ua'         => 'Mozilla/5.0 (compatible; Ezooms/1.0; ezooms.bot@gmail.com)',
        'properties' => [
            'Browser'                 => 'Ezooms',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'SEOmoz, Inc.',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '1.0',
            'Platform'                => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => true,
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-046-b' => [
        'ua'         => 'Mozilla/5.0 (compatible; Ezooms/1.0; help@moz.com)',
        'properties' => [
            'Browser'                 => 'Ezooms',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'SEOmoz, Inc.',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '1.0',
            'Platform'                => 'unknown',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 0,
            'Platform_Maker'          => 'unknown',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => true,
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
