<?php

return [
    'browscap-issue-928-A' => [
        'ua'         => 'Mozilla/5.0 (iOS; U; en) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0',
        'properties' => [
            'Browser'                 => 'Adobe AIR',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Adobe Systems Incorporated',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '13.0',
            'Platform'                => 'iOS',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-928-B' => [
        'ua'         => 'Mozilla/5.0 (iOS; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0',
        'properties' => [
            'Browser'                 => 'Adobe AIR',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Adobe Systems Incorporated',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '13.0',
            'Platform'                => 'iOS',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-928-C' => [
        'ua'         => 'Mozilla/5.0 (iOS; U; en-GB) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0',
        'properties' => [
            'Browser'                 => 'Adobe AIR',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Adobe Systems Incorporated',
            'Browser_Modus'           => 'unknown',
            'Version'                 => '13.0',
            'Platform'                => 'iOS',
            'Platform_Version'        => 'unknown',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Win16'                   => false,
            'Win32'                   => false,
            'Win64'                   => false,
            'isMobileDevice'          => true,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'general Mobile Device',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'general Mobile Device',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
