<?php

return [
    'browscap-issue-590-A' => [
        'ua' => 'Mozilla/5.0 (compatible; HyperCrawl/0.2; +http://www.seograph.net/bot.html)',
        'properties' => [
            'Browser' => 'HyperCrawl',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 0,
            'Browser_Maker' => 'SEOGraph',
            'Browser_Modus' => 'unknown',
            'Version' => '0.2',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 0,
            'Platform_Maker' => 'unknown',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
    ],
    'browscap-issue-590-B' => [
        'ua' => 'iZSearch.com',
        'properties' => [
            'Browser' => 'iZSearch Bot',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 0,
            'Browser_Maker' => 'iZSearch',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 0,
            'Platform_Maker' => 'unknown',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
    ],
    'browscap-issue-590-C' => [
        'ua' => 'Mozilla/2.0 (compatible; ARCHIVE.ORG.UA crawler)',
        'properties' => [
            'Browser' => 'Internet Archive',
            'Browser_Type' => 'Bot/Crawler',
            'Browser_Bits' => 0,
            'Browser_Maker' => 'archive.org',
            'Browser_Modus' => 'unknown',
            'Version' => '0.0',
            'Platform' => 'unknown',
            'Platform_Version' => 'unknown',
            'Platform_Bits' => 0,
            'Platform_Maker' => 'unknown',
            'Win16' => false,
            'Win32' => false,
            'Win64' => false,
            'isMobileDevice' => false,
            'isTablet' => false,
            'Crawler' => true,
            'Device_Name' => 'unknown',
            'Device_Maker' => 'unknown',
            'Device_Type' => 'unknown',
            'Device_Pointing_Method' => 'unknown',
            'Device_Code_Name' => 'unknown',
            'Device_Brand_Name' => 'unknown',
            'RenderingEngine_Name' => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker' => 'unknown',
        ],
    ],
];
