<?php

return [
    'test-0063-0' => [
        'ua' => 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; eSafeUser=CN=Kohl\\, Dirk,OU=Mitarbeiter,OU=Benutzer,OU=KDU,DC=SanaServices,DC=net; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E; InfoPath.3)',
        'properties' => [
            'Browser_Name'            => 'Internet Explorer',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '8.0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => 'XP',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'test-0063-1' => [
        'ua' => 'Mozilla/5.0 (Windows; U; Windows NT 6.2; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/C:\\Program Files (x86)\\Google\\Chrome\\Application Anonymisiert durch AlMiSoft Browser-Anonymisierer 85863746',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '8',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'isMobileDevice'          => false,
            'isTablet'                => false,
            'Crawler'                 => false,
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
