<?php

return [
    'test-0036-2109' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; AlexaToolbar/amzni-3.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; OfficeLiveConnector.1.5; OfficeLivePatch.1.3; InfoPath.3; AlexaToolbar/amzni-3.0)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '7.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0036-2110' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; ms-office; MSOffice 14)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '7.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0036-2111' => [
            'ua'         => 'Airmail 2.0 rv:289 (Macintosh; Mac OS X 10.10.2; de_CH)',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Mac OS X',
                'Platform_Version'        => '10.10.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Apple Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0036-2112' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Q312464)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '6.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0036-2113' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Trident/5.0; anonymized by Abelssoft 1210122909; InfoPath.3; .NET4.0C; .NET4.0E; anonymized by Abelssoft 173819108; ms-office)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '7.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'Vista.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0036-2114' => [
            'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; pl; rv:1.9.0.9) Gecko/2009040821 Firefox/3.0.9',
            'properties' => [
                'Browser_Name'            => 'Firefox',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Mozilla Foundation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '3.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Gecko',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Mozilla Foundation',
            ],
        ],
    'test-0036-2115' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; .NET CLR 1.1.4322; InfoPath.1; InfoPath.2; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '8.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0036-2116' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; Tablet PC 2.0; yie10),gzip(gfe)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '7.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0036-2117' => [
            'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/530.0 (KHTML, like Gecko) Chrome/2.0.160.0 Safari/530.0',
            'properties' => [
                'Browser_Name'            => 'Chrome',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '2.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0036-2118' => [
            'ua'         => 'Mozilla/5.0 (Linux; Android 5.0.2; C6903 Build/14.5.A.0.242; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/42.0.2311.137 Mobile Safari/537.36 ACHEETAHI/2100501080',
            'properties' => [
                'Browser_Name'            => 'CM Browser',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Cheetah Mobile',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '5.0.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Blink',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Google Inc',
            ],
        ],
];
