<?php

return [
    'test-0018-2900' => [
            'ua'         => 'Mozilla/5.0 (X11; U; Linux; C) AppleWebKit/532.4 (KHTML, like Gecko) Qt/4.6.3 Safari/532.4',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Linux',
                'Platform_Version'        => '0.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Linux Foundation',
                'Device_Name'             => 'Linux Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Linux Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0018-2901' => [
            'ua'         => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; HPDTDFJS)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '10.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
];
