<?php

return [
    'test-0019-1801' => [
            'ua'         => 'Mozilla/5.0 (Linux; Android 5.1.1; C6603 Build/10.7.A.0.228; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 ACHEETAHI/2100502012',
            'properties' => [
                'Browser_Name'            => 'CM Browser',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Cheetah Mobile',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '5.1.1',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Blink',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Google Inc',
            ],
        ],
    'test-0019-1802' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; InfoPath.3; ms-office; MSOffice 15)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '7.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '10.0.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0019-1803' => [
            'ua'         => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; Trident/7.0; tb-webde/2.6.1; (webde/1.4.0.0); rv:11.0) like Gecko',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 64,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '10.0.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0019-1804' => [
            'ua'         => 'Mozilla/4.0 (compatible  MSIE 8.0  Windows NT 5.1  Trident/4.0  MRSPUTNIK 2, 3, 0, 104  MRA 5.6 (build 03403)  .NET CLR 1.1.4322  .NET CLR 2.0.50727  .NET CLR 3.0.04506.30  .NET CLR 3.0.4506.2152  .NET CLR 3.5.30729)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '8.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0019-1805' => [
            'ua'         => 'Mozilla/4.0 (compatible  MSIE 8.0  Windows NT 6.1  Trident/4.0  SLCC2  .NET CLR 2.0.50727  .NET CLR 3.5.30729  .NET CLR 3.0.30729  InfoPath.2  Tablet PC 2.0)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '8.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0019-1806' => [
            'ua'         => 'Mozilla/5.0 (Windows; U; Windows NT 6.0; de; rv:1.9.2.8) Gecko/20100802 Thunderbird/3.1.2',
            'properties' => [
                'Browser_Name'            => 'Thunderbird',
                'Browser_Type'            => 'Email Client',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Mozilla Foundation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '3.1',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'Vista.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Gecko',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Mozilla Foundation',
            ],
        ],
    'test-0019-1807' => [
            'ua'         => '[FBAN/FB4A;FBAV/59.0.0.15.313;FBBV/20097196;FBDM/{density=4.0,width=1440,height=2560};FBLC/de_DE;FBCR/Vodafone.de;FBMF/samsung;FBBD/samsung;FBPN/com.facebook.katana;FBDV/SM-G920F;FBSV/5.1.1;nullFBCA/armeabi-v7a:armeabi;]',
            'properties' => [
                'Browser_Name'            => 'Facebook App',
                'Browser_Type'            => 'Application',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Facebook',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '59.0',
                'Platform_Name'           => 'unknown',
                'Platform_Version'        => '0.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => '',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0019-1808' => [
            'ua'         => 'Mercury/910 CFNetwork/672.0.8 Darwin/14.0.0',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Darwin',
                'Platform_Version'        => '14.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Apple Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0019-1809' => [
            'ua'         => 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '5.5',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => 'XP.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0019-1810' => [
            'ua'         => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; MAAU; tb-gmx/2.6.6; rv:11.0) like Gecko',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 64,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0019-1811' => [
            'ua'         => 'Opera/8.82 (X11; Linux i686; U; en-US) Presto/2.9.188 Version/10.00',
            'properties' => [
                'Browser_Name'            => 'Opera',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Opera Software ASA',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '10.00',
                'Platform_Name'           => 'Linux',
                'Platform_Version'        => '0.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Linux Foundation',
                'Device_Name'             => 'Linux Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Linux Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Presto',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Opera Software ASA',
            ],
        ],
    'test-0019-1812' => [
            'ua'         => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; MS-RTC LM 8; SFIEAUTH1)',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '9.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '7.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
];
