<?php

return [
    'test-0102-0' => [
            'ua'         => '\\',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'unknown',
                'Platform_Version'        => '0.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => '',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0102-1' => [
            'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; GT-I9500 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36',
            'properties' => [
                'Browser_Name'            => 'Android WebView',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '4.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.4.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Blink',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Google Inc',
            ],
        ],
    'test-0102-2' => [
            'ua'         => 'Dalvik/1.6.0 (Linux; U; Android 4.4.2; GT-I9500 Build/KOT49H)',
            'properties' => [
                'Browser_Name'            => 'Dalvik',
                'Browser_Type'            => 'Application',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.4.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0102-3' => [
            'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.1.2; nl-nl; GT-I8190N Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
            'properties' => [
                'Browser_Name'            => 'Android',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '4.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.1.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0102-4' => [
            'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/40.0.2214.73 Mobile/11B554a Safari/9537.53',
            'properties' => [
                'Browser_Name'            => 'Chrome',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '40.0',
                'Platform_Name'           => 'iOS',
                'Platform_Version'        => '7.0.4',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Apple Inc',
                'Device_Name'             => 'iPhone',
                'Device_Maker'            => 'Apple Inc',
                'Device_Type'             => 'Mobile Phone',
                'Device_Pointing_Method'  => 'touchscreen',
                'Device_Code_Name'        => 'iPhone',
                'Device_Brand_Name'       => 'Apple',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0102-5' => [
            'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; GT-I9205 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30',
            'properties' => [
                'Browser_Name'            => 'Android',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '4.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.2.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0102-6' => [
            'ua'         => 'socialcast.com',
            'properties' => [
                'Browser_Name'            => 'Default Browser',
                'Browser_Type'            => 'unknown',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'unknown',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '0.0',
                'Platform_Name'           => 'unknown',
                'Platform_Version'        => '0.0.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => '',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'unknown',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'unknown',
            ],
        ],
    'test-0102-7' => [
            'ua'         => 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; HTC; Windows Phone 8X by HTC; 5.20.161.01) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '11.0',
                'Platform_Name'           => 'Windows Phone OS',
                'Platform_Version'        => '8.1.0',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'WebKit',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Apple Inc',
            ],
        ],
    'test-0102-8' => [
            'ua'         => 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; MATPJS; rv:11.0) like Gecko',
            'properties' => [
                'Browser_Name'            => 'Internet Explorer',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 64,
                'Browser_Maker'           => 'Microsoft Corporation',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '11.0',
                'Platform_Name'           => 'Windows',
                'Platform_Version'        => '8.1.0',
                'Platform_Bits'           => 64,
                'Platform_Maker'          => 'Microsoft Corporation',
                'Device_Name'             => 'Windows Desktop',
                'Device_Maker'            => 'Various',
                'Device_Type'             => 'Desktop',
                'Device_Pointing_Method'  => 'mouse',
                'Device_Code_Name'        => 'Windows Desktop',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Trident',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Microsoft Corporation',
            ],
        ],
    'test-0102-9' => [
            'ua'         => 'Mozilla/5.0 (Linux; U; Android 4.4.2; ko-kr; LG-F200K/30g Build/KOT49I.F200K30g) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.1599.103 Mobile Safari/537.36',
            'properties' => [
                'Browser_Name'            => 'Android WebView',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '4.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.4.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Blink',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Google Inc',
            ],
        ],
    'test-0102-10' => [
            'ua'         => 'Mozilla/5.0 (Linux; Android 4.4.2; LG-F200K Build/KOT49I.F200K30g) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.103 Mobile Safari/537.36',
            'properties' => [
                'Browser_Name'            => 'Chrome',
                'Browser_Type'            => 'Browser',
                'Browser_Bits'            => 32,
                'Browser_Maker'           => 'Google Inc',
                'Browser_Modus'           => 'unknown',
                'Browser_Version'         => '30.0',
                'Platform_Name'           => 'Android',
                'Platform_Version'        => '4.4.2',
                'Platform_Bits'           => 32,
                'Platform_Maker'          => 'Google Inc',
                'Device_Name'             => 'unknown',
                'Device_Maker'            => 'unknown',
                'Device_Type'             => 'unknown',
                'Device_Pointing_Method'  => 'unknown',
                'Device_Code_Name'        => 'unknown',
                'Device_Brand_Name'       => 'unknown',
                'RenderingEngine_Name'    => 'Blink',
                'RenderingEngine_Version' => 'unknown',
                'RenderingEngine_Maker'   => 'Google Inc',
            ],
        ],
];
