<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<colgroup>
    <col width="12%" style="width:17%;" />
    <col width="8%" style="width:8%;" />
    <col width="30%" style="width:25%;" />
    <col width="13%" style="width:13%;" />
    <col width="13%" style="width:13%;" />
    <col width="11%" style="width:11%;" />
    <col width="13%" style="width:13%;" />
</colgroup>
<thead>
    <tr class="highlight">
        <th class="center"></th>
        <th class="center">Test-<br />sieger</th>
        <th class="left">Anbieter</th>
        <th class="center">Haben-Zins<span class="red">*</span><br />Dispo-Zins<span class="red">*</span></th>
        <th class="center">Min. / Max.<br />Anlage</th>
        <th class="center">Kreditkartengeb&uuml;hr<br />(j&auml;hrlich)</th>
        <th class="center">Konto<br />er&ouml;ffnen</th>
    </tr>
</thead>