<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<thead>
    <tr class="highlight">
        <th>&nbsp;</th>
        <th>Test-<br />sieger</th>
        <th>Kreditinstitut</th>
        <th>Effektiver<br />Jahrezins<span class="red">*</span></th>
        <th>monatl. Rate/<br />Kreditkosten</th>
        <th class="center">Bonit&auml;t</th>
        <th class="center">Kreditantrag</th>
    </tr>
</thead>