<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */
?>
<div class="options">
    <strong>Kreditbetrag:</strong> <?php echo $this->euroFormat($this->kreditbetrag); ?>
    &nbsp;&nbsp;
    <strong>LoanPeriods:</strong> <?php echo $this->loanPeriodName; ?>
    &nbsp;&nbsp;
    <strong>Verwendung:</strong> <?php echo $this->vzweckLabel; ?>
</div>