<?php
/**
 * View
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: _trustbox.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<div class="trustbox">
    <div class="testsieger">&nbsp;</div>
    <ul>
        <li>Sie stellen lediglich eine Anfrage</li>
        <li>Ihre Anfrage wird ohne negativen Schufaeintrag gestellt</li>
        <li>Auszahlung erst nach Zusendung des unterschriebenen Antrages <br />inkl. der erforderlichen Unterlagen per Post-Ident an die Bank</li>
    </ul>
    <div class="clearer"></div>
</div>