<?php
/**
 * Layout f&uuml;r den Festgeld-Vergleich
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<td class="center lnk weiter"
    onclick="<?php echo $this->goto; ?>"
    onmousedown="logThisClick('<?php echo $this->sparte; ?>_<?php echo $this->kreditinstitut; ?>');"
    title="Jetzt ein <?php echo ucfirst($this->sparte); ?> Konto bei der <?php echo $firma->kreditInstitutTitle; ?> er&ouml;ffnen!">
    &nbsp;
</td>