<?php
/**
 * Layout fuer den Kredit-Vergleich
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id$
 */

?>
<td class="zinsCol"
    onclick="<?php echo $this->goto; ?>"
    onmousedown="logThisClick('<?php echo $this->sparte; ?>_<?php echo $this->kreditinstitut; ?>');"
    title="Online Antrag <?php echo $this->kreditInstitutTitle; ?>">
    <strong class="bigger"><?php echo number_format($this->effZins, 2, ',', '.'); ?> %</strong>
</td>