<?php

namespace BrowserDetectorTest\Detector\Device\Mobile\Acer;

use BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:40:02.
 */
class AcerIconiaB1711Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AcerIconiaB1711
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AcerIconiaB1711('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::detectOs
     * @todo   Implement testDetectOs().
     */
    public function testDetectOs()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getDeviceName
     * @todo   Implement testGetDeviceName().
     */
    public function testGetDeviceName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getDualOrientation
     * @todo   Implement testGetDualOrientation().
     */
    public function testGetDualOrientation()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getHasQwertyKeyboard
     * @todo   Implement testGetHasQwertyKeyboard().
     */
    public function testGetHasQwertyKeyboard()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getMarketingName
     * @todo   Implement testGetMarketingName().
     */
    public function testGetMarketingName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getNfcSupport
     * @todo   Implement testGetNfcSupport().
     */
    public function testGetNfcSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getPointingMethod
     * @todo   Implement testGetPointingMethod().
     */
    public function testGetPointingMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getResolutionHeight
     * @todo   Implement testGetResolutionHeight().
     */
    public function testGetResolutionHeight()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getResolutionWidth
     * @todo   Implement testGetResolutionWidth().
     */
    public function testGetResolutionWidth()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getSmsSupport
     * @todo   Implement testGetSmsSupport().
     */
    public function testGetSmsSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaB1711::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
