<?php

namespace BrowserDetectorTest\Detector\Device\Mobile\Acer;

use BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:40:02.
 */
class AcerIconiaA501Test extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AcerIconiaA501
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AcerIconiaA501('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::detectOs
     * @todo   Implement testDetectOs().
     */
    public function testDetectOs()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getDeviceName
     * @todo   Implement testGetDeviceName().
     */
    public function testGetDeviceName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getDualOrientation
     * @todo   Implement testGetDualOrientation().
     */
    public function testGetDualOrientation()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getHasQwertyKeyboard
     * @todo   Implement testGetHasQwertyKeyboard().
     */
    public function testGetHasQwertyKeyboard()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getMarketingName
     * @todo   Implement testGetMarketingName().
     */
    public function testGetMarketingName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getNfcSupport
     * @todo   Implement testGetNfcSupport().
     */
    public function testGetNfcSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getPointingMethod
     * @todo   Implement testGetPointingMethod().
     */
    public function testGetPointingMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getResolutionHeight
     * @todo   Implement testGetResolutionHeight().
     */
    public function testGetResolutionHeight()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getResolutionWidth
     * @todo   Implement testGetResolutionWidth().
     */
    public function testGetResolutionWidth()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getSmsSupport
     * @todo   Implement testGetSmsSupport().
     */
    public function testGetSmsSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Acer\AcerIconiaA501::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
