<?php
/**
 * Main-Layout für direkten Aufruf oder Aufruf im IFrame
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @version   SVN: $Id: get-error-list.phtml 30 2011-01-06 21:58:02Z tmu $
 */
?>
<table id="sortableTable" class="Data sortableTable" summary="Übersicht über Unerwartete Ausnahmen">
    <thead>
        <tr>
            <th class="first" colspan="2" scope="col">Trace</th>
            <th scope="col">Zeit/Datum</th>
            <th scope="col">Kontext</th>
            <th scope="col">Nachricht</th>
            <th scope="col">Level</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->paginator->getItemsByPage($this->paginator->getCurrentPageNumber()) as $item): ?>
        <tr class="<?php echo $this->cycle(array('cycle1','cycle2'))->next() ?>" style="width: 100%" >
            <td class="first error jq_exception_tooltip">
                <div class="exceptionTooltip">
                    <?php echo nl2br(htmlentities('Fehler-Trace' . $item->Trace)); ?>
                </div>
            </td>
            <td class="first cog jq_exception_tooltip">
                <div class="exceptionTooltip">
                    <?php echo var_dump(unserialize($item->Request)); ?>
                </div>
            </td>
            <td>
                    <?php echo $item->Throw ?>
            </td>
            <td>
                <span style="color:<?php echo $this->colors[$item->Enviroment]; ?>">
                    <strong>
                        <?php echo $item->Enviroment; ?>
                    </strong>
                </span>
            </td>
            <td>
                <?php echo $item->Message; ?>
            </td>
            <td>
                <?php echo $item->level; ?>
            </td>
        </tr>
<?php endforeach ?>
    </tbody>
</table>