<?php
/**
 * This file is part of the browser-detector package.
 *
 * Copyright (c) 2012-2017, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);
namespace BrowserDetectorTest\Factory;

use BrowserDetector\Factory\NormalizerFactory;
use BrowserDetector\Factory\PlatformFactory;
use BrowserDetector\Loader\PlatformLoader;
use Cache\Adapter\Filesystem\FilesystemCachePool;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use UaResult\Os\Os;

/**
 * Test class for \BrowserDetector\Detector\Device\Mobile\GeneralMobile
 */
class PlatformFactoryTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var \BrowserDetector\Factory\PlatformFactory
     */
    private $object = null;

    /**
     * @var \Psr\Cache\CacheItemPoolInterface|null
     */
    private $cache = null;

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $adapter      = new Local(__DIR__ . '/../../cache/');
        $this->cache  = new FilesystemCachePool(new Filesystem($adapter));
        $loader       = new PlatformLoader($this->cache);
        $this->object = new PlatformFactory($loader);
    }

    /**
     * @dataProvider providerDetect
     *
     * @param string $userAgent
     * @param string $platform
     * @param string $version
     * @param string $manufacturer
     * @param int    $bits
     */
    public function testDetect($userAgent, $platform, $version, $manufacturer, $bits)
    {
        $normalizer = (new NormalizerFactory())->build();

        $normalizedUa = $normalizer->normalize($userAgent);

        /** @var \UaResult\Os\OsInterface $result */
        $result = $this->object->detect($normalizedUa);

        self::assertInstanceOf('\UaResult\Os\OsInterface', $result);
        self::assertSame(
            $platform,
            $result->getName(),
            'Expected platform name to be "' . $platform . '" (was "' . $result->getName() . '")'
        );

        self::assertInstanceOf('\BrowserDetector\Version\Version', $result->getVersion());
        self::assertSame(
            $version,
            $result->getVersion()->getVersion(),
            'Expected version to be "' . $version . '" (was "' . $result->getVersion()->getVersion() . '")'
        );

        self::assertSame(
            $manufacturer,
            $result->getManufacturer()->getName(),
            'Expected manufacturer name to be "' . $manufacturer . '" (was "' . $result->getManufacturer()->getName() . '")'
        );

        self::assertSame(
            $bits,
            $result->getBits(),
            'Expected bits count to be "' . $bits . '" (was "' . $result->getBits() . '")'
        );
    }

    /**
     * @return array[]
     */
    public function providerDetect()
    {
        return [
            [
                'Mozilla/5.0 (iPad; CPU OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B440 Safari/600.1.4',
                'iOS',
                '8.1.2',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0C; .NET4.0E)',
                'Windows NT 5.2',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; Android 4.3; de-de; GT-I9300 Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
                'Android',
                '4.3.0',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.1.25 (KHTML, like Gecko)',
                'Mac OS X',
                '10.10.1',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko',
                'Windows NT 6.3',
                '0.0.0',
                'Microsoft Corporation',
                64,
            ],
            [
                'Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.2.2.1609 Mobile Safari/537.35+',
                'RIM OS',
                '10.2.2.1609',
                'Research In Motion Limited',
                32,
            ],
            [
                'Mozilla/5.0 (Nintendo 3DS; U; ; de) Version/1.7567.EU',
                'Nintendo OS',
                '0.0.0',
                'Nintendo',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 930) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'Windows Phone OS',
                '8.1.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0',
                'Windows NT 10.0',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (hp-tablet; Linux; hpwOS/3.0.5; U; fr-CA) AppleWebKit/534.6 (KHTML, like Gecko) wOSBrowser/234.83 Safari/534.6 Touchpad/1.0',
                'webOS',
                '3.0.5',
                'HP',
                32,
            ],
            [
                'SAMSUNG-SGH-T528g/T528UDKE4[TF355314045027030009640018153425713] Dolfin/1.5 SMM-MMS/1.2.0 profile/MIDP-2.1 configuration/CLDC-1.1',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'SonyEricssonS312/R1EA Browser/OpenWave/1.0 Profile/MIDP-2.1 Configuration/CLDC-1.1',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Huawei/1.0/HUAWEI-G7300 Browser/Opera MMS/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; it-IT) Presto/2.5.28 Version/10.10',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'SAMSUNG-GT-E3309T Opera/9.80 (J2ME/MIDP; Opera Mini/4.4.34189/34.1016; U; en) Presto/2.8.119 Version/11.10',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'UCWEB/2.0 (Linux; U; Opera Mini/7.1.32052/30.3697; en-US; AX5_Duo) U2/1.0.0 UCBrowser/8.8.1.359 Mobile',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'MicromaxX650 ASTRO36_TD/v3 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Sync/SyncClient1.1 Profile/MIDP-2.0 Configuration/CLDC-1.1 Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Opera/9.80 (MAUI Runtime; Opera Mini/4.4.31762/34.1000; U; en) Presto/2.8.119 Version/11.10',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'SAMSUNG-GT-B7722/DDKD1 SHP/VPP/R5 Dolfin/1.5 Nextreaming SMM-MMS/1.2.0 profile/MIDP-2.1 configuration/CLDC-1.1',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Opera/9.80 (SpreadTrum; Opera Mini/4.4.31492/34.1000; U; en) Presto/2.8.119 Version/11.10',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'Wget/1.17.1 (cygwin)',
                'Cygwin',
                '0.0.0',
                null,
                32,
            ],
            [
                'Opera/9.80 (VRE; Opera Mini/4.2/34.1000; U; en) Presto/2.8.119 Version/11.10',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1 Installatron (Mimicking WebKit)',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; rv:1.9a3pre) Gecko/20070330',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.2.1; AT10-A Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.102 Safari/537.36',
                'Android',
                '4.2.1',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.4.2; SM-T235 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.102 Safari/537.36',
                'Android',
                '4.4.2',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; Lumia 928) like Gecko',
                'Windows Phone OS',
                '8.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 920; Vodafone ES) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
                'Windows Phone OS',
                '8.1.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'ASTRO36_TD/v3 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Profile/MIDP-2.0 Configuration/CLDC-1.1 Sync/SyncClient1.1 Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'YUANDA50_12864_11B_HW (MRE\\2.5.00(800) resolution\\320480 chipset\\MT6250 touch\\1 tpannel\\1 camera\\1 gsensor\\0 keyboard\\reduced) C529AH_JY_539_W1.11B.V2.2 Release/2012.09.26 WAP Browser/MAUI (HTTP PGDL; HTTPS) Profile/ Q03C1-2.40 fr-FR',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'SYM.S200.SYM.T63.DEWAV60A_64_11B_HW (MRE/3.1.00(1280);MAUI/_DY33891_Symphony_L102;BDATE/2014/04/18 14:22;LCD/240320;CHIP/MT6260;KEY/Normal;TOUCH/0;CAMERA/1;SENSOR/0;DEV/DEWAV60A_64_11B_HW;WAP Browser/MAUI (HTTP PGDL;HTTPS);GMOBI/001;MBOUNCE/002;MOMAGIC/003;INDEX/004;SPICEI2I/005;GAMELOFT/006;) Y3389_DY33891_Symphony_L102 Release/2014.04.18 WAP Browser/MAUI (HTTP PGDL; HTTPS) Profile/  Q03C1-2.40 en-US',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Dorado WAP-Browser/1.0.0',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Lynx/2.8.5rel.1 libwww-FM/2.15FC SSL-MM/1.4.1c OpenSSL/0.9.7e-dev',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; Android 4.1.2; de-de; CINK PEAX 2 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
                'Android',
                '4.1.2',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; Android 4.0.4; ru; HTC T328w Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/9.8.9.457 U3/0.8.0 Mobile Safari/534.30',
                'Android',
                '4.0.4',
                'Google Inc',
                32,
            ],
            [
                'UCWEB/2.0 (MIDP-2.0; U; Adr 4.2.0; ru; iPhone5) U2/1.0.0 UCBrowser/10.1.2.571 U2/1.0.0 Mobile',
                'Android',
                '4.2.0',
                'Google Inc',
                32,
            ],
            [
                'Opera/9.80 (Linux armv7l; U; NETRANGEMMH;HbbTV/1.1.1;CE-HTML/1.0;Vendor/THOM;SW-Version/V8-MT51F01-LF1V307;Cnt/DEU;Lan/bul) Presto/2.12.362 Version/12.11',
                'Maemo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Dalvik/1.6.0 (Linux; U; Android 4.4.4; MI PAD MIUI/5.11.1)',
                'Miui OS',
                '5.11.1',
                'Xiaomi Tech',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; Windows Mobile; WCE; Opera Mobi/WMD-50433; U; de) Presto/2.4.13 Version/10.00',
                'Windows CE',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/4.77C-SGI [en] (X11; I; IRIX64 6.5 IP30)',
                'IRIX',
                '0.0.0',
                null,
                64,
            ],
            [
                'Mozilla/4.77 [en] (X11; U; HP-UX B.11.00 9000/800)',
                'HP-UX',
                '0.0.0',
                'HP',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; OSF1 alpha; en-US; rv:0.9.4.1) Gecko/20020517 Netscape6/6.2.3',
                'Tru64 UNIX',
                '0.0.0',
                'HP',
                64,
            ],
            [
                'Opera/9.80 (J2ME/MIDP; Opera Mini/4.3.24214 (Windows; U; Windows NT 6.1) AppleWebKit/24.838; U; id) Presto/2.5.25 Version/10.54',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Opera/9.80 (J2ME/MIDP; Opera Mini/4.3.24214; iPhone; CPU iPhone OS 4_2_1 like Mac OS X; AppleWebKit/24.783; U; en) Presto/2.5.25 Version/10.54',
                'iOS',
                '4.2.1',
                'Apple Inc',
                32,
            ],
            [
                'amarok/2.8.0 (Phonon/4.8.0; Phonon-VLC/0.8.0) LibVLC/2.2.1',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux arm7tdmi; rv:1.8.1.11) Gecko/20071130 Minimo/0.025',
                'Maemo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 6.0; Windows 95; PalmSource; Blazer 3.0) 16; 160x160',
                'PalmOS',
                '0.0.0',
                'Palm',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1b4pre) Gecko/20090311 Ubuntu/9.04 (jaunty) Shiretoko/3.1b4pre',
                'Ubuntu',
                '9.04.0',
                'Canonical Foundation',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) Opera 8.60 [en]',
                'Windows NT 5.1',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/4.41  (BEOS; U ;Nav)',
                'BeOS',
                '0.0.0',
                'Access',
                32,
            ],
            [
                'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; rv:1.7.2) Gecko/20040804 Netscape/7.2',
                'Mac OS X',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Darwin; FreeBSD 5.6; en-GB; rv:1.8.1.17pre) Gecko/20080716 K-Meleon/1.5.0',
                'FreeBSD',
                '5.6.0',
                'FreeBSD Foundation',
                32,
            ],
            [
                'Mozilla/4.08 (Charon; Inferno)',
                'Inferno OS',
                '0.0.0',
                'Vita Nuova Holdings Ltd',
                32,
            ],
            [
                'Mozilla/5.0 (compatible; ABrowse 0.4; Syllable)',
                'Syllable',
                '0.0.0',
                'Syllable Project',
                32,
            ],
            [
                'Mozilla/5.0 Gecko/20030306 Camino/0.7',
                'Mac OS X',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Macintosh; ARM Mac OS X) AppleWebKit/538.15 (KHTML, like Gecko) Safari/538.15 Version/6.0 Raspbian/8.0 (1:3.8.2.0-0rpi27rpi1g) Epiphany/3.8.2',
                'Debian',
                '8.0.0',
                'Software in the Public Interest, Inc.',
                32,
            ],
            [
                'Mozilla/5.0 (Maemo; Linux; U; Jolla; Sailfish; like Android) AppleWebKit/538.1 (KHTML, like Gecko) Mobile Safari/538.1 (compatible)',
                'SailfishOS',
                '0.0.0',
                'Jolla Ltd.',
                32,
            ],
            [
                'Lemon B556',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'LAVA Spark284/MIDP-2.0 Configuration/CLDC-1.1/Screen-240x320',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'KKT20/MIDP-2.0 Configuration/CLDC-1.1/Screen-240x320',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Microsoft-CryptoAPI/6.3',
                null,
                '0.0.0',
                null,
                32,
            ],
            [
                'UCS (ESX) - 4.0-3 errata302 - 28d414cc-2dac-4c0e-a34a-734020b8af66 - 00000000-0000-0000-0000-000000000000 -',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) Sprint:MotoQ9c',
                'Windows CE',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; en-us; Velocitymicro/T408) AppleWebKit/530.17(KHTML, like Gecko) Version/4.0Safari/530.17',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (SAMSUNG; SAMSUNG-GT-S5380/Z3x_tmXXKK4',
                'Bada',
                '0.0.0',
                'Samsung',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:32.0) Gecko/20100101 Firefox/32.0',
                'Firefox OS',
                '2.0.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'SAMSUNG-GT-C3312R Opera/9.80 (X11; Linux zvav; U; en) Presto/2.12.423 Version/12.16',
                'Java',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'TinyBrowser/2.0 (TinyBrowser Comment; rv:1.9.1a2pre) Gecko/20201231',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Android; Linux armv7l; rv:5.0) Gecko/20110603 Firefox/5.0 Fennec/5.0',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; Android 4.0.4; ja-jp; SH-10D Build/S4180; DOCOMO; mediatap) 720X1184 SHARP SH-10D AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
                'Android',
                '4.0.4',
                'Google Inc',
                32,
            ],
            [
                'Apple-PubSub/65.28',
                'Mac OS X',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'integrity/4',
                'Mac OS X',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Symbian/3; Series60/5.3 Nokia500/111.021.0028; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/535.1 (KHTML, like Gecko) NokiaBrowser/8.3.1.4 Mobile Safari/535.1 3gpp-gba',
                'Symbian OS',
                '0.0.0',
                'Symbian Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Windows Phone OS',
                '10.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Windows Phone OS',
                '10.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586',
                'Windows Phone OS',
                '10.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; Ubuntu; Linux armv7l; rv:17.0) Gecko/20100101 Firefox/17.0',
                'Ubuntu',
                '0.0.0',
                'Canonical Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (SMART-TV; X11; Linux armv7l) AppleWebKit/537.42 (KHTML, like Gecko) Chromium/25.0.1349.2 Chrome/25.0.1349.2 Safari/537.42',
                'Maemo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Debian APT-HTTP/1.3 (1.0.1ubuntu2)',
                'Debian',
                '0.0.0',
                'Software in the Public Interest, Inc.',
                32,
            ],
            [
                'Mozilla/5.0 (Nintendo WiiU) AppleWebKit/536.30 (KHTML, like Gecko) NX/3.0.4.2.12 NintendoBrowser/4.3.1.11264.EU',
                'Nintendo OS',
                '0.0.0',
                'Nintendo',
                32,
            ],
            [
                'Mozilla/5.0 CommonCrawler Node W6YSWFNKODF3CZPDD35IT2L6RYMGKYY3KPEZCTKI6DDCMYEVJZBRYY23GDPZCQW.A.ZNMSHA2FQHEQOZF4KOG43OH2FKIMIUIWH6ZREWD7F6T44AJK.cdn0.common.crawl.zone',
                null,
                '0.0.0',
                null,
                32,
            ],
            [
                'microSearch-Crawler/V1.0.0.730',
                null,
                '0.0.0',
                null,
                32,
            ],
            [
                'DWDS-Crawler +http://odo.dwds.de/dwds-crawler.html',
                null,
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; OSF1 alpha; en-US; rv:1.7.5) Gecko/20050112 Firefox/1.0',
                'Tru64 UNIX',
                '0.0.0',
                'HP',
                64,
            ],
            [
                'Mozilla/5.0 (X11; Fedora; Linux armv7l; rv:38.0) Gecko/20100101 Firefox/38.0',
                'Fedora Linux',
                '0.0.0',
                'Red Hat Inc',
                32,
            ],
            [
                'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) profiler Safari/534.34',
                'Linux',
                '0.0.0',
                'Linux Foundation',
                64,
            ],
            [
                'Mozilla/5.0 (Linux; Android 4.4.4; GT-S8530 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36',
                'Android',
                '4.4.4',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Macintosh; ARM Mac OS X) AppleWebKit/538.15 (KHTML, like Gecko) Safari/538.15 Version/6.0 Debian/7.8 (3.8.2.0-0rpi18rpi1) Epiphany/3.8.2',
                'Debian',
                '7.8.0',
                'Software in the Public Interest, Inc.',
                32,
            ],
            [
                'ELinks/0.11.4-2 (textmode; Debian; GNU/kFreeBSD 6.3-1-486 i686; 141x21-2)',
                'Debian with FreeBSD Kernel',
                '6.3.1.486',
                'Software in the Public Interest, Inc.',
                32,
            ],
            [
                'Safari/12602.1.50.0.2 CFNetwork/807.0.1 Darwin/16.0.0 (x86_64)',
                'macOS',
                '10.12.0',
                'Apple Inc',
                64,
            ],
            [
                'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-de) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27',
                'Mac OS X',
                '10.6.8',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; SunOS sun4u; pl-PL; rv:1.8.1.6) Gecko/20071217 Firefox/2.0.0.6',
                'SunOS',
                '0.0.0',
                'Oracle',
                32,
            ],
            [
                'Mozilla/5.0 (X11; NetBSD amd64; rv:43.0) Gecko/20100101 Firefox/43.0',
                'NetBSD',
                '0.0.0',
                null,
                64,
            ],
            [
                'iOS/6.1.3 (10B329) dataaccessd/1.0',
                'iOS',
                '6.1.3',
                'Apple Inc',
                32,
            ],
            [
                'Dalvik/1.6.0 (Linux; U; Android 4.4.2; MI PAD MIUI/KXFCNBF5.0)',
                'Miui OS',
                '0.0.0',
                'Xiaomi Tech',
                32,
            ],
            [
                'Downcast/2.9.10 (Mac OS X Version 10.11.3 (Build 15D21))',
                'Mac OS X',
                '10.11.3',
                'Apple Inc',
                32,
            ],
            [
                'ZDM/4.0; Windows Mobile 8.1',
                'Windows Phone OS',
                '8.1.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Dalvik/2.1.0 (Linux; U; Android 6.0.1; MI 4LTE MIUI/V7.3.2.0.MXDCNDD) NewsArticle/5.1.3',
                'Miui OS',
                '7.3.2.0',
                'Xiaomi Tech',
                32,
            ],
            [
                'Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko)',
                'RIM OS',
                '10.0.0',
                'Research In Motion Limited',
                32,
            ],
            [
                'JUC (Linux; U; 4.0.4; zh-cn; GT-I9100; 480*800) UCWEB7.9.0.94/139/444',
                'Android',
                '4.0.4',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; de-de; GT-I9100 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Safari/533.1',
                'Android',
                '2.3.0',
                'Google Inc',
                32,
            ],
            [
                'Opera/9.80 (BREW; Opera Mini/5.0/27.2339; U; en) Presto/2.8.119 320X240 Samsung SCH-U750',
                'Brew',
                '0.0.0',
                null,
                32,
            ],
            [
                'UCWEB/2.0 (iOS; U; iPh OS 7_0_4; zh-CN; iPh5,2) U2/1.0.0 UCBrowser/9.0.1.284 U2/1.0.0 Mobile',
                'iOS',
                '7.0.4',
                'Apple Inc',
                32,
            ],
            [
                'UCWEB/2.0 (Windows; U; wds 7.10; en-US; SAMSUNG; GT-I8350) U2/1.0.0 UCBrowser/3.2.0.340 U2/1.0.0 Mobile',
                'Windows Phone OS',
                '7.10.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; ARM; Touch; WPDesktop)',
                'Windows Phone OS',
                '8.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (iPad; CPU iPhone OS 501 like Mac OS X) AppleWebKit/534.46 (KHTML like Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3',
                'iOS',
                '5.0.1',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (BlackBerry; U; BlackBerry 9320; de) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.714 Mobile Safari/534.11+',
                'RIM OS',
                '7.1.0.714',
                'Research In Motion Limited',
                32,
            ],
            [
                'Mozilla/5.0 (iPhone; CPU iPhone OS 10_10 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B401 Safari/600.1.4',
                'iOS',
                '8.0.0',
                'Apple Inc',
                32,
            ],
            [
                'LIAuthLibrary:0.0.2 com.linkedin.android:3.4.2 TCL_ALCATEL ONE TOUCH 4037T:android_4.4.2',
                'Android',
                '4.4.2',
                'Google Inc',
                32,
            ],
            [
                'Rocky ChatWork Mobile/3.4.1 iosv7.1.2 (iPhone App iPhone6,1)',
                'iOS',
                '7.1.2',
                'Apple Inc',
                32,
            ],
            [
                'wp-android/3.0.1 (Android 4.4.2; nl_NL; samsung GT-N7100/t03gxx)',
                'Android',
                '4.4.2',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; Android; 4.1.2; GT-I9100 Build/000000) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1234.12 Mobile Safari/537.22 OPR/14.0.123.123',
                'Android',
                '4.1.2',
                'Google Inc',
                32,
            ],
            [
                'MacAppStore/2.0 (Macintosh; OS X 10.10.2; 14C81f) AppleWebKit/0600.3.10.2',
                'Mac OS X',
                '10.10.2',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 10.0; ARM; Lumia 650) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586',
                'Windows Phone OS',
                '10.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.1.1) Gecko/20090725 Moblin/3.5.1-2.5.14.moblin2 Shiretoko/3.5.1',
                'Moblin',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 4.10; rv:44.0) Gecko/20100101 Firefox/44.0',
                'Windows NT 4.10',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 4.1; rv:44.0) Gecko/20100101 Firefox/44.0',
                'Windows NT 4.1',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 4.0; rv:44.0) Gecko/20100101 Firefox/44.0',
                'Windows NT 4.0',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 3.5; rv:44.0) Gecko/20100101 Firefox/44.0',
                'Windows NT 3.5',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 3.1; rv:44.0) Gecko/20100101 Firefox/44.0',
                'Windows NT 3.1',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)',
                'Windows NT',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                '(null) [FBAN/FBIOS;FBAV/15.0.0.16.28;FBBV/4463064;FBDV/iPhone6,1;FBMD/iPhone;FBSN/iPhone OS;FBSV/8.0.2;FBSS/2; FBCR/U.S.Cellular;FBID/phone;FBLC/en_US;FBOP/5]',
                'iOS',
                '8.0.2',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 4.01; Windows 3.11)',
                'Windows 3.11',
                '0.0.0',
                'Microsoft Corporation',
                16,
            ],
            [
                'Mozilla/2.0 (compatible; MSIE 3.0; Windows 3.1)',
                'Windows 3.1',
                '0.0.0',
                'Microsoft Corporation',
                16,
            ],
            [
                'Opera/9.80 (X11; Linux i686; Edition Linux Mint) Presto/2.12.388 Version/12.16',
                'Linux Mint',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; pl-PL; rv:1.9.2a1pre) Gecko/20090330 Kubuntu/8.10 (intrepid) Minefield/3.2a1pre',
                'Kubuntu',
                '8.10.0',
                'Canonical Foundation',
                32,
            ],
            [
                'curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5',
                'Redhat Linux',
                '0.0.0',
                'Red Hat Inc',
                64,
            ],
            [
                'OMozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.9) Gecko/20100827 Red Hat/3.6.9-2.el6 Firefox/3.6.9',
                'Redhat Linux',
                '0.0.0',
                'Red Hat Inc',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.8.0.5) Gecko/20060805 CentOS/1.0.3-0.el4.1.centos4 SeaMonkey/1.0.3',
                'Cent OS Linux',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; CrOS x86_64 14.4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2558.0 Safari/537.36',
                'ChromeOS',
                '0.0.0',
                'Google Inc',
                64,
            ],
            [
                'Mozilla/5.0 (X11; Jolicloud Linux i686) AppleWebKit/537.6 (KHTML, like Gecko) Joli OS/1.2 Chromium/23.0.1240.0 Chrome/23.0.1240.0 Safari/537.6',
                'Joli OS',
                '1.2.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.7) Gecko/2009031120 Mandriva/1.9.0.7-0.1mdv2009.0 (2009.0) Firefox/3.0.7',
                'Mandriva Linux',
                '0.0.0',
                'Mandriva',
                64,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.0.14) Gecko/2009090900 SUSE/3.0.14-0.1 Firefox/3.0.14',
                'Suse Linux',
                '0.0.0',
                'Suse',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; en; rv:1.9) Gecko/20080528 (Gentoo) Epiphany/2.22 Firefox/3.0',
                'Gentoo Linux',
                '0.0.0',
                'Gentoo Foundation Inc',
                32,
            ],
            [
                'Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.30 (KHTML, like Gecko) Slackware/Chrome/12.0.742.100 Safari/534.30',
                'Slackware Linux',
                '0.0.0',
                'Slackware Linux Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; U; Linux Ventana; de-de; Transformer TF101G Build/HTJ85B) AppleWebKit/534.13 (KHTML, like Gecko) Chrome/8.0 Safari/534.13',
                'Ventana Linux',
                '0.0.0',
                'Ventana',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; de; rv:1.9.1.1) Gecko/20090725 Moblin/3.5.1-2.5.14.moblin2 Shiretoko/3.5.1',
                'Moblin',
                '0.0.0',
                null,
                32,
            ],
            [
                'Unibox/87 CFNetwork/808.0.2 Darwin/16.0.0',
                'iOS',
                '10.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/12602.1.43 CFNetwork/802.1 Darwin/16.0.0 (x86_64)',
                'macOS',
                '10.12.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/12602.1.40.4 CFNetwork/798.3 Darwin/16.0.0 (x86_64)',
                'macOS',
                '10.12.0',
                'Apple Inc',
                64,
            ],
            [
                'MobileSafari/602.1 CFNetwork/796.1 Darwin/16.0.0',
                'macOS',
                '10.12.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/12602.1.32.7 CFNetwork/790.2 Darwin/16.0.0 (x86_64)',
                'iOS',
                '10.0.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/11601.5.17.1 CFNetwork/760.4.2 Darwin/15.4.0 (x86_64)',
                'Mac OS X',
                '10.11.0',
                'Apple Inc',
                64,
            ],
            [
                'TestApp/1.0 CFNetwork/758.0.2 Darwin/15.0.0',
                'iOS',
                '9.0.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/601.1 CFNetwork/757 Darwin/15.0.0',
                'iOS',
                '9.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/10600.1.25.1 CFNetwork/720.1.1 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'com.apple.WebKit.WebContent/10600.1.15 CFNetwork/718 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'com.apple.WebKit.WebContent/10600.1.8 CFNetwork/714 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'MobileSafari/600.1.4 CFNetwork/711.5.6 Darwin/14.0.0',
                'iOS',
                '8.4.0',
                'Apple Inc',
                32,
            ],
            [
                'Mercury/894 CFNetwork/711.4.6 Darwin/14.0.0',
                'iOS',
                '8.4.0',
                'Apple Inc',
                32,
            ],
            [
                'Mercury/894 CFNetwork/711.3.18 Darwin/14.0.0',
                'iOS',
                '8.3.0',
                'Apple Inc',
                32,
            ],
            [
                'Mail/53 CFNetwork/711.2.23 Darwin/14.0.0',
                'iOS',
                '8.2.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/600.1.4 CFNetwork/711.1.16 Darwin/14.0.0',
                'iOS',
                '8.1.0',
                'Apple Inc',
                32,
            ],
            [
                'Mercury/870 CFNetwork/711.0.6 Darwin/14.0.0',
                'iOS',
                '8.0.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/600.1.4 CFNetwork/709.1 Darwin/14.0.0',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                32,
            ],
            [
                'Unibox/190 CFNetwork/708.1 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'com.apple.WebKit.WebContent/10538.46 CFNetwork/705 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'com.apple.WebKit.WebContent/10538.39.41 CFNetwork/699 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'Unibox/190 CFNetwork/696.0.2 Darwin/14.0.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/9537.86.3.9.1 CFNetwork/673.6 Darwin/13.4.0 (x86_64) (iMac10%2C1)',
                'Mac OS X',
                '10.9.0',
                'Apple Inc',
                64,
            ],
            [
                'MobileSafari/9537.53 CFNetwork/672.1.15 Darwin/14.0.0',
                'iOS',
                '7.1.0',
                'Apple Inc',
                32,
            ],
            [
                'AtomicBrowser/7.0.1 CFNetwork/672.0.8 Darwin/14.0.0',
                'iOS',
                '7.0.0',
                'Apple Inc',
                32,
            ],
            [
                'AtomicBrowser/7.0.1 CFNetwork/609.1.4 Darwin/13.0.0',
                'iOS',
                '6.1.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/8536.25 CFNetwork/609 Darwin/13.0.0',
                'iOS',
                '6.0.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/8536.25 CFNetwork/602 Darwin/13.0.0',
                'iOS',
                '6.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/8536.30.1 CFNetwork/596.4.3 Darwin/12.4.0 (x86_64) (Macmini6%2C2)',
                'Mac OS X',
                '10.8.0',
                'Apple Inc',
                64,
            ],
            [
                'AdSheet/1.0 CFNetwork/548.1.4 Darwin/11.0.0',
                'iOS',
                '5.1.0',
                'Apple Inc',
                32,
            ],
            [
                'AtomicBrowser/6.0.1 CFNetwork/548.0.4 Darwin/11.0.0',
                'iOS',
                '5.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7537.78.2 CFNetwork/520.5.3 Darwin/11.4.2 (i386) (MacBookPro2%2C2)',
                'Mac OS X',
                '10.7.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/515.1 Darwin/11.0.0 (x86_64) (MacBook7%2C1)',
                'Mac OS X',
                '10.7.0',
                'Apple Inc',
                64,
            ],
            [
                'AtomicBrowser/5.8.0 CFNetwork/485.13.9 Darwin/11.0.0',
                'iOS',
                '4.3.0',
                'Apple Inc',
                32,
            ],
            [
                'CSN%20Philly/1.03.01 CFNetwork/485.12.30 Darwin/10.4.0',
                'iOS',
                '4.2.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/6531.22.7 CFNetwork/485.10.2 Darwin/10.3.1',
                'iOS',
                '4.1.0',
                'Apple Inc',
                32,
            ],
            [
                'MobileSafari/6531.22.7 CFNetwork/485.2 Darwin/10.3.1',
                'iOS',
                '4.0.0',
                'Apple Inc',
                32,
            ],
            [
                'AtomicBrowser/3.7.1 CFNetwork/467.12 Darwin/10.3.1',
                'iOS',
                '3.2.0',
                'Apple Inc',
                32,
            ],
            [
                'Stitcher/3.310746 CFNetwork/459 Darwin/10.0.0d3',
                'iOS',
                '3.1.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/6534.59.10 CFNetwork/454.12.4 Darwin/10.8.0 (i386) (iMac5%2C2)',
                'Mac OS X',
                '10.6.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari5533.22.3 CFNetwork/438.16 Darwin/9.8.0 (i386) (iMac8%2C1)',
                'Mac OS X',
                '10.5.0',
                'Apple Inc',
                32,
            ],
            [
                'ContentBarrier%20X510.5.4%20 CFNetwork/422.15.2 Darwin/9.6.0 (i386) (MacBook5%2C1)',
                'Mac OS X',
                '10.5.0',
                'Apple Inc',
                32,
            ],
            [
                'Cooliris/1.2 CFNetwork/339.3 Darwin/9.4.1',
                'Mac OS X',
                '10.5.0',
                'Apple Inc',
                32,
            ],
            [
                'QuickTime\\\\xaa.7.0.4 (qtver=7.0.4;cpu=PPC;os=Mac 10.3.9)',
                'Mac OS X',
                '10.3.9',
                'Apple Inc',
                32,
            ],
            [
                'S8500 UCWEB6.0/UC Browser7.7.0.81',
                'Bada',
                '0.0.0',
                'Samsung',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.2) Gecko/20090903 Iceweasel/3.5.2 (Zenwalk GNU Linux)',
                'Zenwalk GNU Linux',
                '0.0.0',
                null,
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/647 Darwin/11.0.0',
                'Mac OS X',
                '10.9.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/595 Darwin/11.0.0',
                'Mac OS X',
                '10.8.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/561 Darwin/11.0.0',
                'Mac OS X',
                '10.8.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/433 Darwin/11.0.0',
                'Mac OS X',
                '10.5.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/330 Darwin/11.0.0',
                'Mac OS X',
                '10.5.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/129 Darwin/11.0.0',
                'Mac OS X',
                '10.4.0',
                'Apple Inc',
                32,
            ],
            [
                'Safari/7534.20.8 CFNetwork/4.0 Darwin/11.0.0',
                'Mac OS X',
                '10.3.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36',
                'Windows NT 6.4',
                '0.0.0',
                'Microsoft Corporation',
                64,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0; Touch; MSAppHost/2.0; rv:11.0) like Gecko',
                'Windows RT 6.3',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; ARM; Trident/6.0; Touch)',
                'Windows RT 6.2',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0',
                'Windows NT 6.2',
                '0.0.0',
                'Microsoft Corporation',
                64,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0',
                'Windows NT 6.1',
                '0.0.0',
                'Microsoft Corporation',
                64,
            ],
            [
                'Mozilla/5.0 (Windows NT 6.0; rv:34.0) Gecko/20100101 Firefox/34.0',
                'Windows NT 6.0',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE6.00; Windows 2003)',
                'Windows 2003',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/4.0 (MSIE 6.0; Windows NT 5.3)',
                'Windows NT 5.3',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Opera/8.48 (Windows NT 5.01; en-US) Presto/2.12.346 Version/12.00',
                'Windows NT 5.01',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; KTXN)',
                'Windows NT 5.0',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 ( compatible; MSIE 5.01; AOL 5.0; win9x/NT 4.90 )',
                'Windows ME',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (Windows; U; Win98; de; rv:1.8.1.20) Gecko/20081217 Firefox/2.0.0.20',
                'Windows 98',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Win95; en-US; rv:1.8.1) Gecko/20061125 BonEcho/2.0',
                'Windows 95',
                '0.0.0',
                'Microsoft Corporation',
                32,
            ],
            [
                'MQQBrowser/3.4/Adr (Linux; U; 4.1.2; zh-cn; GT-I9300 Build/JZO54K.I9300ZNEMD2;720*1280)',
                'Android',
                '4.1.2',
                'Google Inc',
                32,
            ],
            [
                'MQQBrowser/2.8/Adr (Linux; U; 2.2; zh-cn; GT-I9000 Build/FROYO.XXJPO;480*800)',
                'Android',
                '2.2.0',
                'Google Inc',
                32,
            ],
            [
                'MQQBrowser/25 (Linux; U; 2.3.3; zh-cn; GT-I9000 Build/GINGERBREAD.XWJVH;480*800)',
                'Android',
                '2.3.3',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (Series40; Nokia300/07.65; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.0.1.62.6',
                'Nokia OS',
                '0.0.0',
                'Nokia',
                32,
            ],
            [
                'Mozilla/5.0 (SAMSUNG; SAMSUNG-GT-S8600/S8600XXLD1; U; Bada/2.0; de-de) AppleWebKit/534.20 (KHTML, like Gecko) Dolfin/3.0 Mobile WVGA SMM-MMS/1.2.0 OPN-B',
                'Bada',
                '2.0.0',
                'Samsung',
                32,
            ],
            [
                'Mozilla/5.0 (MeeGo; NokiaN9) AppleWebKit/534.13 (KHTML, like Gecko) NokiaBrowser/8.5.0 Mobile Safari/534.13',
                'MeeGo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Opera/9.80 (Linux armv7l; Opera Mobi/1; MeeGo) Presto/2.11.355 Version/12.10',
                'MeeGo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; OpenBSD i386; en-US; rv:1.9.1) Gecko/20090702 Firefox/3.5',
                'OpenBSD',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (compatible; Konqueror/4.1; DragonFly) KHTML/4.1.4 (like Gecko)',
                'DragonFly BSD',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; BSD Four) AppleWebKit/534.34 (KHTML, like Gecko) Qt/4.8.5 Safari/534.34',
                'BSD',
                '0.0.0',
                'University of California, Berkeley',
                32,
            ],
            [
                'Mozilla/5.0 (Linux; Tizen 2.3; SAMSUNG SM-Z130H) AppleWebKit/537.3 (KHTML, like Gecko) SamsungBrowser/1.0 Mobile Safari/537.3',
                'Tizen',
                '2.3.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Maemo; Mobile; rv:15.0) Gecko/20120829 Firefox/15.0 Fennec/15.0',
                'Maemo',
                '0.0.0',
                'Linux Foundation',
                32,
            ],
            [
                'Mozilla/4.05 (Macintosh; I; 68K Nav)',
                'Macintosh',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/4.05 (Macintosh; I; PPC Nav)',
                'Macintosh',
                '0.0.0',
                'Apple Inc',
                32,
            ],
            [
                'Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.1.0; en-US) AppleWebKit/536.2+ (KHTML, like Gecko) Version/7.2.1.0 Safari/536.2+',
                'RIM Tablet OS',
                '2.1.0',
                'Research In Motion Limited',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; AIX 000690FC4C00; en-US; rv:1.7.3) Gecko/20041022',
                'AIX',
                '000690.0.0',
                'IBM',
                32,
            ],
            [
                'IBrowse/2.2 (AmigaOS 3.5)',
                'Amiga OS',
                '3.5.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.8) Gecko/20100215 Solaris/10.1 (GNU) Superswan/3.5.8 (Byte/me)',
                'Solaris',
                '10.1.0',
                'Oracle',
                64,
            ],
            [
                'Mozilla/5.0 (X11; U; SunOSi86pc; de-en; rv:1.91b3) Solaris 11.1 Gecko/34 Firefox/34',
                'Solaris',
                '11.1.0',
                'Oracle',
                32,
            ],
            [
                'Mozilla/1.10 [en] (Compatible; RISC OS 3.70; Oregano 1.10)',
                'RISC OS',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/3.04 (compatible; NCBrowser/2.35; ANTFresco/2.17; RISC OS-NC 5.13 Laz1UK1309)',
                'RISC OS',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; OpenVMS AlphaServer_ES40; en-US; rv:1.4) Gecko/20030826 SWB/V1.4 (HP)',
                'OpenVMS',
                '0.0.0',
                'HP',
                32,
            ],
            [
                'Mozilla/4.0 (compatible; MSIE 5.0; UNIX) Opera 6.11 [en]',
                'Unix',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (OS/2; Warp 4.5; rv:2.0.1) Gecko/20100101 Firefox/4.0.1',
                'OS/2',
                '4.5.0',
                'IBM',
                32,
            ],
            [
                'ShitScript/1.0 (CP/M; 8-bit)',
                'CP/M',
                '0.0.0',
                null,
                8,
            ],
            [
                'Kopiczek/9.8.10 (WyderOS 0.3.12; pl)',
                'WyderOS',
                '0.3.12',
                null,
                32,
            ],
            [
                'Mozilla/3.0 (Liberate DTV 1.1)',
                'Liberate',
                '0.0.0',
                null,
                32,
            ],
            [
                'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; HTC_Sensation_Z710e; da-dk) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16',
                'Android',
                '0.0.0',
                'Google Inc',
                32,
            ],
            [
                'Safari/11601.6.17 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)',
                'Mac OS X',
                '10.11.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/11601.5.17.1 CFNetwork/760.4.2 Darwin/15.4.0 (x86_64)',
                'Mac OS X',
                '10.11.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/11601.4.4 CFNetwork/760.2.6 Darwin/15.3.0 (x86_64)',
                'Mac OS X',
                '10.11.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/11601.2.7.2 CFNetwork/760.1.2 Darwin/15.0.0 (x86_64)',
                'Mac OS X',
                '10.11.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/10600.6.3 CFNetwork/720.3.13 Darwin/14.3.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'Safari/10601.2.7.2 CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)',
                'Mac OS X',
                '10.10.0',
                'Apple Inc',
                64,
            ],
            [
                'Mozilla/5.0 (Linux; U; Android Eclair; md-us Build/pandigitalopc1/sourceidDL00000009) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17',
                'Android',
                '2.1.0',
                'Google Inc',
                32,
            ],
            [
                'Mozilla/5.0 (X11; U; Linux i686; de-de) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/531.2+ Debian/squeeze (2.30.6-1) Epiphany/2.30.6',
                'Debian',
                '6.0.0',
                'Software in the Public Interest, Inc.',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:37.0) Gecko/20100101 Firefox/37.0',
                'Firefox OS',
                '2.2.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:34.0) Gecko/20100101 Firefox/34.0',
                'Firefox OS',
                '2.1.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Firefox OS',
                '1.4.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:26.0) Gecko/20100101 Firefox/26.0',
                'Firefox OS',
                '1.2.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:18.0) Gecko/20100101 Firefox/18.0',
                'Firefox OS',
                '1.0.0',
                'Mozilla Foundation',
                32,
            ],
            [
                'Mozilla/5.0 (Mobile; rv:16.0) Gecko/20100101 Firefox/16.0',
                'Firefox OS',
                '0.0.0',
                'Mozilla Foundation',
                32,
            ],
        ];
    }
}
