<?php

namespace BrowserDetectorTest\Detector\Device\Mobile\Twinovo;

use BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-07 at 12:40:31.
 */
class TwinovoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Twinovo
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Twinovo('Test-User-Agent');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::detectOs
     * @todo   Implement testDetectOs().
     */
    public function testDetectOs()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getDeviceName
     * @todo   Implement testGetDeviceName().
     */
    public function testGetDeviceName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getBrand
     * @todo   Implement testGetBrand().
     */
    public function testGetBrand()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getDualOrientation
     * @todo   Implement testGetDualOrientation().
     */
    public function testGetDualOrientation()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getHasQwertyKeyboard
     * @todo   Implement testGetHasQwertyKeyboard().
     */
    public function testGetHasQwertyKeyboard()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getManufacturer
     * @todo   Implement testGetManufacturer().
     */
    public function testGetManufacturer()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getMarketingName
     * @todo   Implement testGetMarketingName().
     */
    public function testGetMarketingName()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getNfcSupport
     * @todo   Implement testGetNfcSupport().
     */
    public function testGetNfcSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getPointingMethod
     * @todo   Implement testGetPointingMethod().
     */
    public function testGetPointingMethod()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getResolutionHeight
     * @todo   Implement testGetResolutionHeight().
     */
    public function testGetResolutionHeight()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getResolutionWidth
     * @todo   Implement testGetResolutionWidth().
     */
    public function testGetResolutionWidth()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getSmsSupport
     * @todo   Implement testGetSmsSupport().
     */
    public function testGetSmsSupport()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getUseragent
     * @todo   Implement testGetUseragent().
     */
    public function testGetUseragent()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getVersion
     * @todo   Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers BrowserDetector\Detector\Device\Mobile\Twinovo\Twinovo::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize()
    {
        // Remove the following lines when you implement this test.
        static::markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
