<?php

return [
    'test-00134-02064' => [
        'ua'         => 'Opera/9.80 (Android; Opera Mini/19.0.2254/37.8841; U; de) Presto/2.12.423 Version/12.16',
        'properties' => [
            'Browser_Name'            => 'Opera',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Opera Software ASA',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '12.16',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Presto',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Opera Software ASA',
        ],
    ],
    'test-00134-02078' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 4.2.2; ALCATEL ONETOUCH P310A Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Chrome',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '51',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '4.2.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
    'test-00134-02080' => [
        'ua'         => 'Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-T550 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Safari/537.36 evaliant',
        'properties' => [
            'Browser_Name'            => 'Samsung Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Samsung',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.3',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '5.0.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Blink',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Google Inc',
        ],
    ],
];
