# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

# file-version: 1.0

name: "Lock closed issue"

on:
  issues:
    types:
      - "closed"

permissions:
  contents: read

jobs:
  lock:
    name: "Lock Issues"
    uses: "mimmi20/ci/.github/workflows/lock-issues.yml@8.5"
    permissions:
      issues: write
