# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

# file-version: 1.0

name: "Reaction Comments"

on:
  issue_comment:
    types:
      - "created"
      - "edited"
  pull_request_review_comment:
    types:
      - "created"
      - "edited"

permissions:
  contents: read
  actions: write
  issues: write
  pull-requests: write

jobs:
  action:
    name: "Comments"
    uses: "mimmi20/ci/.github/workflows/reaction-comments.yml@8.4"
