<?php

return [
    'browscap-issue-1047-A' => [
        'ua'         => 'Kodi/16.1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/16.1-Git:20160424-c327c53',
        'properties' => [
            'Browser_Name'            => 'Kodi Media Center',
            'Browser_Type'            => 'Multimedia Player',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'XBMC Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '16.1',
            'Platform_Codename'       => 'Windows NT 10.0',
            'Platform_Marketingname'  => 'Windows 10',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-1047-B' => [
        'ua'         => 'Kodi/17.0-BETA1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.0-BETA1-Git:20160821-81d5d26',
        'properties' => [
            'Browser_Name'            => 'Kodi Media Center',
            'Browser_Type'            => 'Multimedia Player',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'XBMC Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '17.0',
            'Platform_Codename'       => 'Windows NT 10.0',
            'Platform_Marketingname'  => 'Windows 10',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
