<?php

return [
    'browscap-issue-1093-A' => [
        'ua'         => 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1074) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
        'properties' => [
            'Browser_Name'            => 'IEMobile',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.0',
            'Platform_Codename'       => 'Windows Phone OS',
            'Platform_Marketingname'  => 'Windows Phone OS',
            'Platform_Version'        => '8.1.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Lumia 640 LTE',
            'Device_Maker'            => 'Microsoft Corporation',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'RM-1074',
            'Device_Brand_Name'       => 'Microsoft',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-1093-B' => [
        'ua'         => 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft;Lumia 535 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
        'properties' => [
            'Browser_Name'            => 'IEMobile',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.0',
            'Platform_Codename'       => 'Windows Phone OS',
            'Platform_Marketingname'  => 'Windows Phone OS',
            'Platform_Version'        => '8.1.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Lumia 535',
            'Device_Maker'            => 'Microsoft Corporation',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'Lumia 535',
            'Device_Brand_Name'       => 'Microsoft',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
];
