<?php

return [
    'browscap-issue-012-a' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
        'properties' => [
            'Browser_Name'            => 'IE',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Microsoft Corporation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '11.0',
            'Platform_Codename'       => 'Windows NT 6.3',
            'Platform_Marketingname'  => 'Windows 8.1',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Trident',
            'RenderingEngine_Version' => '7.0',
            'RenderingEngine_Maker'   => 'Microsoft Corporation',
        ],
    ],
    'browscap-issue-012-b' => [
        'ua'         => 'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0',
        'properties' => [
            'Browser_Name'            => 'Firefox',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Mozilla Foundation',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '24.0',
            'Platform_Codename'       => 'Windows NT 6.3',
            'Platform_Marketingname'  => 'Windows 8.1',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => '24.0',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
