<?php

return [
    'browscap-issue-590-A' => [
        'ua'         => 'Mozilla/5.0 (compatible; HyperCrawl/0.2; +http://www.seograph.net/bot.html)',
        'properties' => [
            'Browser_Name'            => 'HyperCrawl',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'SEOGraph',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.2',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-590-B' => [
        'ua'         => 'iZSearch.com',
        'properties' => [
            'Browser_Name'            => 'iZSearch Bot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'iZSearch',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-590-C' => [
        'ua'         => 'Mozilla/2.0 (compatible; ARCHIVE.ORG.UA crawler)',
        'properties' => [
            'Browser_Name'            => 'Internet Archive',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'archive.org',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
