<?php

return [
    'browscap-issue-077-G' => [
        'ua'         => 'SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
        'properties' => [
            'Browser_Name'            => 'Google Bot Mobile',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Codename'       => 'Java',
            'Platform_Marketingname'  => 'Java',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Oracle',
            'Platform_Brand_Name'     => 'Oracle',
            'Device_Name'             => 'SGH-E250',
            'Device_Maker'            => 'Samsung',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => null,
            'Device_Dual_Orientation' => null,
            'Device_Code_Name'        => 'SGH-E250',
            'Device_Brand_Name'       => 'Samsung',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-077-F' => [
        'ua'         => 'DoCoMo/2.0 N905i(c100;TB;W24H16) (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
        'properties' => [
            'Browser_Name'            => 'Google Bot Mobile',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Codename'       => 'Linux Smartphone OS (Maemo)',
            'Platform_Marketingname'  => 'Linux Smartphone OS (Maemo)',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'N905i',
            'Device_Maker'            => 'NEC',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'N905i',
            'Device_Brand_Name'       => 'NEC',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-077-E' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
        'properties' => [
            'Browser_Name'            => 'Google Bot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '6.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-077-D' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)',
        'properties' => [
            'Browser_Name'            => 'Google Bot Mobile',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '6.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-077-C' => [
        'ua'         => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
        'properties' => [
            'Browser_Name'            => 'Google Bot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => null,
            'Device_Pointing_Method'  => null,
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-077-B' => [
        'ua'         => 'integrity/4',
        'properties' => [
            'Browser_Name'            => 'Integrity',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'Mac OS X',
            'Platform_Marketingname'  => 'Mac OS X',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'Macintosh',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Macintosh',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-077-A' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; en-us; KFTT Build/IML74K) AppleWebKit/535.19 (KHTML, like Gecko) Silk/3.11 Safari/535.19 Silk-Accelerated=true',
        'properties' => [
            'Browser_Name'            => 'Silk',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Amazon.com, Inc.',
            'Browser_Modus'           => 'Desktop Mode',
            'Browser_Version'         => '3.11',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Kindle Fire HD 7',
            'Device_Maker'            => 'Amazon.com, Inc.',
            'Device_Type'             => 'Tablet',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'KFTT',
            'Device_Brand_Name'       => 'Amazon',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
