<?php

return [
    'browscap-issue-908-A' => [
        'ua'         => 'GetintentCrawler getintent.com',
        'properties' => [
            'Browser_Name'            => 'Getintent Crawler',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'getintent.com',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-908-B' => [
        'ua'         => 'MonitorBacklinksWP (+http://monitorbacklinks.com/blog/incoming-links/)',
        'properties' => [
            'Browser_Name'            => 'Incoming Links - WordPress Plugin',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Monitor Backlinks Ltd.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-908-C' => [
        'ua'         => 'AddThis.com (http://support.addthis.com/)',
        'properties' => [
            'Browser_Name'            => 'AddThis.com robot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'AddThis.com',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => '',
            'Device_Pointing_Method'  => '',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
