<?php

return [
    'browscap-issue-1101-A' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X; en-US) AppleWebKit/537.51.1 (KHTML, like Gecko) Mobile/13G36 UCBrowser/10.8.4.865 Mobile',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.8',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '9.3.5',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-1101-B' => [
        'ua'         => 'Mozilla/5.0 (Linux; U; Ios 9.3; en-US; iphone 6s Build/KVT49L) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.5.2.582 U3/0.8.0 Mobile Safari/534.30',
        'properties' => [
            'Browser_Name'            => 'UC Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'UCWeb Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '10.5',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '9.3.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'U3',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'UCWeb Inc.',
        ],
    ],
];
