<?php

return [
    'browscap-issue-050-2' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux) AppleWebKit/531.2+ Midori/0.3',
        'properties' => [
            'Browser_Name'            => 'Midori',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Christian Dywan',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.3',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-050-1' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux) AppleWebKit/537.32 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/537.32 Midori/0.5',
        'properties' => [
            'Browser_Name'            => 'Midori',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Christian Dywan',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.5',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
