<?php

return [
    'browscap-issue-1044-A' => [
        'ua'         => 'Mozilla/4.0 (compatible; Lotus-Notes/5.0; Windows-NT)',
        'properties' => [
            'Browser_Name'            => 'Lotus Notes',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'IBM',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '5.0',
            'Platform_Codename'       => 'Windows NT 4.0',
            'Platform_Marketingname'  => 'Windows NT',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-1044-B' => [
        'ua'         => 'YahooMobileMail/1.0 (Android Mail; 1.3.10) (supersonic;HTC;PC36100;2.3.5/GRJ90)',
        'properties' => [
            'Browser_Name'            => 'Yahoo Mail Mobile',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Yahoo! Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Codename'       => 'Android',
            'Platform_Marketingname'  => 'Android',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Google Inc',
            'Platform_Brand_Name'     => 'Google',
            'Device_Name'             => 'EVO 4G',
            'Device_Maker'            => 'HTC',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'PC36100',
            'Device_Brand_Name'       => 'HTC',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-1044-C' => [
        'ua'         => 'Barca/2.8.2',
        'properties' => [
            'Browser_Name'            => 'Barca Mail Client',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Poco Systems Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.8',
            'Platform_Codename'       => 'Windows',
            'Platform_Marketingname'  => 'Windows',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-1044-D' => [
        'ua'         => 'BarcaPro/1.4.12',
        'properties' => [
            'Browser_Name'            => 'Barca Mail Client',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Poco Systems Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.4',
            'Platform_Codename'       => 'Windows',
            'Platform_Marketingname'  => 'Windows',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-1044-E' => [
        'ua'         => 'The Bat! 4.0.0.22',
        'properties' => [
            'Browser_Name'            => 'The Bat!',
            'Browser_Type'            => 'Email Client',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Ritlabs SRL.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'Windows',
            'Platform_Marketingname'  => 'Windows',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
