<?php

return [
    'browscap-issue-373-A' => [
        'ua'         => 'Mozilla/5.0 (Series30Plus; Nokia220/10.03.11; Profile/Series30Plus Configuration/Series30Plus) Gecko/20100401 S40OviBrowser/3.8.1.0.5',
        'properties' => [
            'Browser_Name'            => 'Nokia Proxy Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Nokia',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.8',
            'Platform_Codename'       => 'Nokia OS',
            'Platform_Marketingname'  => 'Nokia OS',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Nokia',
            'Platform_Brand_Name'     => 'Nokia',
            'Device_Name'             => 'Asha 220',
            'Device_Maker'            => 'Nokia',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => '220',
            'Device_Brand_Name'       => 'Nokia',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-373-B' => [
        'ua'         => 'Mozilla/5.0 (Series40; Nokia109/04.10; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/4.0.0.0.45',
        'properties' => [
            'Browser_Name'            => 'Nokia Proxy Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Nokia',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'Nokia OS',
            'Platform_Marketingname'  => 'Java',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Oracle',
            'Platform_Brand_Name'     => 'Oracle',
            'Device_Name'             => '109',
            'Device_Maker'            => 'Nokia',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => '109',
            'Device_Brand_Name'       => 'Nokia',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-373-C' => [
        'ua'         => 'Mozilla/5.0 (Series40; Nokia110/03.04; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/2.0.5.16.6',
        'properties' => [
            'Browser_Name'            => 'Nokia Proxy Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Nokia',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Codename'       => 'Nokia OS',
            'Platform_Marketingname'  => 'Java',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Oracle',
            'Platform_Brand_Name'     => 'Oracle',
            'Device_Name'             => '110',
            'Device_Maker'            => 'Nokia',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => '110',
            'Device_Brand_Name'       => 'Nokia',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-373-D' => [
        'ua'         => 'Mozilla/5.0 (Series40; Nokia112/03.26; Profile/MIDP-2.1 Configuration/CLDC-1.1) Gecko/20100401 S40OviBrowser/5.0.0.0.31',
        'properties' => [
            'Browser_Name'            => 'Nokia Proxy Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Nokia',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '5.0',
            'Platform_Codename'       => 'Nokia OS',
            'Platform_Marketingname'  => 'Java',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Oracle',
            'Platform_Brand_Name'     => 'Oracle',
            'Device_Name'             => '112',
            'Device_Maker'            => 'Nokia',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => '112',
            'Device_Brand_Name'       => 'Nokia',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
];
