<?php

return [
    'browscap-issue-562-A' => [
        'ua'         => 'Cyberduck/4.6.4 (16610) (Windows XP/5.1) (x86)',
        'properties' => [
            'Browser_Name'            => 'Cyberduck',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'iterate GmbH',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.6',
            'Platform_Codename'       => 'Windows NT 5.1',
            'Platform_Marketingname'  => 'Windows XP',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Platform_Brand_Name'     => 'Microsoft',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-562-B' => [
        'ua'         => 'Lynx/2.8.5rel.1 libwww-FM/2.15FC SSL-MM/1.4.1c OpenSSL/0.9.7e-dev',
        'properties' => [
            'Browser_Name'            => 'Lynx',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Thomas Dickey',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.8',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'general Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'general Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
