<?php

return [
    'browscap-issue-350-A' => [
        'ua'         => 'Mozilla/5.0 (compatible; XoviBot/2.0; +http://www.xovibot.net/)',
        'properties' => [
            'Browser_Name'            => 'XoviBot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Xovi GmbH',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-350-B' => [
        'ua'         => 'Mozilla/5.0 (compatible; 007ac9 Crawler; http://crawler.007ac9.net/)',
        'properties' => [
            'Browser_Name'            => '007AC9 Crawler',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'SISTRIX GmbH',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-350-C' => [
        'ua'         => 'Mozilla/5.0 (compatible; AOLbot/4.0; +http://www.aol-soft.com/)',
        'properties' => [
            'Browser_Name'            => 'AOLbot',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'AOL-SOFT.COM',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-350-D' => [
        'ua'         => 'Go 1.1 package http',
        'properties' => [
            'Browser_Name'            => 'GO HttpClient',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.1',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-350-E' => [
        'ua'         => 'Mozilla/5.0 (compatible; DomainSCAN/2.0; +http://domainscan.info/robot/)',
        'properties' => [
            'Browser_Name'            => 'DomainScan Server Monitoring',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'GH Software',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Name'           => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-350-F' => [
        'ua'         => 'Proxy Gear Pro/2.1 (Windows; N; Windows NT 6.1; en)',
        'properties' => [
            'Browser_Name'            => 'Proxy Gear Pro',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'proxy-base.org',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.1',
            'Platform_Name'           => 'Windows',
            'Platform_Version'        => '7.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Microsoft Corporation',
            'Device_Name'             => 'Windows Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Windows Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
