<?php

return [
    'browscap-issue-1035-A' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1',
        'properties' => [
            'Browser_Name'            => 'Safari',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '9.0',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '9.3.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-1035-B' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 [FBAN/FBIOS;FBAV/60.0.0.37.141;FBBV/34183777;FBRV/0;FBDV/iPhone6,1;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.2;FBSS/2;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]',
        'properties' => [
            'Browser_Name'            => 'Facebook App',
            'Browser_Type'            => 'Application',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Facebook',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '9.3.2',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-1035-C' => [
        'ua'         => 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34',
        'properties' => [
            'Browser_Name'            => 'Mobile Safari UIWebView',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Apple Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'iOS',
            'Platform_Marketingname'  => 'iOS',
            'Platform_Version'        => '9.3.3',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Apple Inc',
            'Platform_Brand_Name'     => 'Apple',
            'Device_Name'             => 'iPhone',
            'Device_Maker'            => 'Apple Inc',
            'Device_Type'             => 'Mobile Phone',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Code_Name'        => 'iPhone',
            'Device_Brand_Name'       => 'Apple',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
