<?php

return [
    'browscap-issue-081-G' => [
        'ua'         => 'Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)',
        'properties' => [
            'Browser_Name'            => 'Mail.Ru',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Mail.Ru Group',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '2.0',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-081-F' => [
        'ua'         => 'masscan/1.0 (https://github.com/robertdavidgraham/masscan)',
        'properties' => [
            'Browser_Name'            => 'Download Accelerator',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-081-E' => [
        'ua'         => 'ZmEu',
        'properties' => [
            'Browser_Name'            => 'ZmEu',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-081-D' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux i686; U;rv: 1.7.13) Gecko/20070322 Kazehakase/0.4.4.1',
        'properties' => [
            'Browser_Name'            => 'Kazehakase',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'unknown',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.4',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'Gecko',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Mozilla Foundation',
        ],
    ],
    'browscap-issue-081-C' => [
        'ua'         => 'woobot/1.1',
        'properties' => [
            'Browser_Name'            => 'WooRank',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'woorank.com',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '1.1',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-081-B' => [
        'ua'         => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36',
        'properties' => [
            'Browser_Name'            => 'Google PageSpeed Insights',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 64,
            'Browser_Maker'           => 'Google Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'Linux',
            'Platform_Marketingname'  => 'Linux',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 64,
            'Platform_Maker'          => 'Linux Foundation',
            'Platform_Brand_Name'     => 'Linux Foundation',
            'Device_Name'             => 'Linux Desktop',
            'Device_Maker'            => 'Various',
            'Device_Type'             => 'Desktop',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Code_Name'        => 'Linux Desktop',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
    'browscap-issue-081-A' => [
        'ua'         => 'Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)',
        'properties' => [
            'Browser_Name'            => 'Sogou Web Spider',
            'Browser_Type'            => 'Bot/Crawler',
            'Browser_Bits'            => 0,
            'Browser_Maker'           => 'Sogou Inc',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '4.0',
            'Platform_Codename'       => 'unknown',
            'Platform_Marketingname'  => 'unknown',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'unknown',
            'Platform_Brand_Name'     => 'unknown',
            'Device_Name'             => 'unknown',
            'Device_Maker'            => 'unknown',
            'Device_Type'             => 'unknown',
            'Device_Pointing_Method'  => 'unknown',
            'Device_Code_Name'        => 'unknown',
            'Device_Brand_Name'       => 'unknown',
            'RenderingEngine_Name'    => 'unknown',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'unknown',
        ],
    ],
];
