<?php

return [
    'browscap-issue-405-A' => [
        'ua'         => 'Mozilla/5.0 (PlayStation 4 1.75) AppleWebKit/536.26 (KHTML, like Gecko)',
        'properties' => [
            'Browser_Name'            => 'NetFront',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Access',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'CellOS',
            'Platform_Marketingname'  => 'CellOS',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Sony',
            'Platform_Brand_Name'     => 'Sony',
            'Device_Name'             => 'Playstation 4',
            'Device_Maker'            => 'Sony',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Playstation 4',
            'Device_Brand_Name'       => 'Sony',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-405-B' => [
        'ua'         => 'Mozilla/5.0 (PlayStation Vita 3.18) AppleWebKit/536.26 (KHTML, like Gecko) Silk/3.2',
        'properties' => [
            'Browser_Name'            => 'Silk',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Amazon.com, Inc.',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '3.2',
            'Platform_Codename'       => 'Java',
            'Platform_Marketingname'  => 'Java',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Oracle',
            'Platform_Brand_Name'     => 'Oracle',
            'Device_Name'             => 'PlayStation Vita',
            'Device_Maker'            => 'Sony',
            'Device_Type'             => 'Mobile Device',
            'Device_Pointing_Method'  => 'touchscreen',
            'Device_Dual_Orientation' => true,
            'Device_Code_Name'        => 'PlayStation Vita',
            'Device_Brand_Name'       => 'Sony',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
    'browscap-issue-405-C' => [
        'ua'         => 'Mozilla/5.0 (PLAYSTATION 3 4.60) AppleWebKit/531.22.8 (KHTML, like Gecko)',
        'properties' => [
            'Browser_Name'            => 'Playstation Browser',
            'Browser_Type'            => 'Browser',
            'Browser_Bits'            => 32,
            'Browser_Maker'           => 'Sony',
            'Browser_Modus'           => 'unknown',
            'Browser_Version'         => '0.0',
            'Platform_Codename'       => 'CellOS',
            'Platform_Marketingname'  => 'CellOS',
            'Platform_Version'        => '0.0.0',
            'Platform_Bits'           => 32,
            'Platform_Maker'          => 'Sony',
            'Platform_Brand_Name'     => 'Sony',
            'Device_Name'             => 'Playstation 3',
            'Device_Maker'            => 'Sony',
            'Device_Type'             => 'TV Device',
            'Device_Pointing_Method'  => 'mouse',
            'Device_Dual_Orientation' => false,
            'Device_Code_Name'        => 'Playstation 3',
            'Device_Brand_Name'       => 'Sony',
            'RenderingEngine_Name'    => 'WebKit',
            'RenderingEngine_Version' => 'unknown',
            'RenderingEngine_Maker'   => 'Apple Inc',
        ],
    ],
];
