<?php
/**
 * Layout f&uuml;r den Error-Contoller
 *
 * PHP version 5
 *
 * @category  Kreditrechner
 * @package   Views
 * @author    Marko Schreiber <marko.schreiber@unister-gmbh.de>
 * @author    Thomas Mueller <thomas.mueller@unister-gmbh.de>
 * @copyright 2007-2010 Unister GmbH
 * @license   http://www.unister.de  Unister License
 * @version   SVN: $Id: error.phtml 30 2011-01-06 21:58:02Z tmu $
 * @link      todo
 */
?>
<h1>An error occurred</h1>
<h2><?php echo $this->message; ?></h2>
<?php if (!in_array(APPLICATION_ENV, array('live'))) : ?>
<h3>Exception information:</h3>
<p>
<strong>Message:</strong> <?php echo $this->exception->getMessage(); ?>
</p>
<h3>Aufruf:</h3>
<pre><?php echo $this->request->getRequestUri(); ?></pre>
<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString(); ?></pre>
<h3>Request Parameters:</h3>
<pre><?php var_dump($this->request->getParams()) ?></pre>
<?php endif; ?>
<span>&nbsp;</span>